### ISSUE TITLE
Crash when report-aws-default.html is used by another process

### ISSUE THREAD

**Issue by Aboisier** [nccgroup/ScoutSuite#100]
The software crashes when then output target (`report-aws-default.html`) is used by another process.

It would be interesting to have a retry mechanism. This would allow the user to kill the other process if he/she wants to. This way, the user does not have to restart the scan.

**Comment by j4v** [comment]
A simpler and less disruptive approach could be to allow the user to give another name to the report?

**Comment by j4v** [comment]
> A simpler and less disruptive approach could be to allow the user to give another name to the report?

This is now implemented in `develop` with the `report-name` flag, closing the issue.
