### ISSUE TITLE
Public bucket objects not identified

### ISSUE THREAD

**Issue by allisonis** [nccgroup/ScoutSuite#101]
Currently the checks in buckets.py are looking solely at bucket level permissions. Since object level acl's can differ from bucket level permissions, publicly accessible objects are not identified. In order to determine if objects are publicly accessible acl's could be checked as well for the allUsers entity.

**Comment by j4v** [comment]
You are correct, this is also the case for AWS S3 bucket objects. The reason objects aren't being checked is that buckets may have thousands++ objects: checking each one of them could potentially make scans run forever.

Finding a solution to this is indeed in the pipeline, will keep this issue open for tracking.

**Comment by j4v** [comment]
Closing this and marking as `wontfix` as analyzing all of the objects in a bucket doesn't scale.
