### ISSUE TITLE
Optimize JSON object reading

### ISSUE THREAD

**Issue by spoilist** [nccgroup/ScoutSuite#1012]
Find a solution (library or else) to optimize the reading step of the JSON object.
We want to access the JSON file without reading the whole file.

- Look for a solution (library or else)
- Implement solution

**Comment by j4v** [comment]
Some options (by order of GH stars:
- https://github.com/kashifrazzaqui/json-streamer
- https://github.com/danielyule/naya
- https://github.com/AMDmi3/jsonslicer
- https://github.com/timedata-org/streamy

I'd start by generating a bogus report and resting response times for 1) loading the whole JSON and fetching data from it (downside is that this uses more memory) & 2) using one of these libraries to dynamically fetch data without ever loading the whole thing in memory (also test to confirm this is actually the case...). If the response time vs memory use tradeoff is considered worth it, then we can go down this route. What I don't like about these libraries is that they seem to have only moderate support, but in any event it would be easy to revert back to a vanilla implementation.
