### ISSUE TITLE
Update CLI

### ISSUE THREAD

**Issue by spoilist** [nccgroup/ScoutSuite#1014]
The CLI should be updated to accept the following options (TBD):
- ~~`-no-server` for no server when executing the program~~
- `-server-only` to only start the server without generating a new report (takes an existing JSON file as argument)
- `-report-only` to only generate a new JSON report file without starting the server for the front-end to run

The default option will generate a new report and start a local server to serve the data to the front-end.

**Comment by j4v** [comment]
What's the difference between `--no-server` and `--report-only`?

**Comment by spoilist** [comment]
Indeed, there is a problem...
We'll instead have 2 options rather `-server-only` that takes an argument which is the json file to be read and `-report-only` which will only generate a new report and no server would start.
