### ISSUE TITLE
the process getting killed why?

### ISSUE THREAD

**Issue by niksthehacker** [nccgroup/ScoutSuite#102]
Please have a look into attached image, the process getting killed in between before report. What could be the reason?
<img width="1626" alt="screen shot 2019-01-16 at 2 25 38 pm" src="https://user-images.githubusercontent.com/1374497/51237545-aa0ac000-199a-11e9-900b-ca3f5f2fdea8.png">

It happened each time.

**Comment by j4v** [comment]
My guess would be that you're running Scout on a machine that has limited memory - is this the case?

**Comment by niksthehacker** [comment]
certainly, thanks
