### ISSUE TITLE
More user feedback when using the --service flag

### ISSUE THREAD

**Issue by Aboisier** [nccgroup/ScoutSuite#104]
If the user writes an invalid service when using the `--service` flag (for example he/she writes `EC2` instead of `ec2`), all the services are scanned and there is no feedback.

It would be interesting to give the user some feedback. For example: 
> The `EC2` service does not exist. Here are the available services: ec2, cloudwatch, ...

**Comment by j4v** [comment]
Agreed, and listing existing services would be great, it's not trivial to find the options at the moment.
