### ISSUE TITLE
Update docker/bin/container-install-azure.sh script

### ISSUE THREAD

**Issue by danielrichdc** [nccgroup/ScoutSuite#1079]
MS has published an ubuntu focal build of azure-cli now, so the lines in container-install-azure.sh that set the CLI_REPO to eoan (which results in an apt error about an out of date libc and the azure-cli not being installed) are out of date:
```
# MSFT has no repo for focal yet, force the system to use eoan instead
if [[ ${CLI_REPO} -eq "focal" ]]; then
  CLI_REPO="eoan"
fi_
```
should be removed.

**Comment by j4v** [comment]
@rossja could you have a look at this please.

**Comment by rossja** [comment]
Seems legit. Fixed in https://github.com/nccgroup/ScoutSuite/pull/1096/commits/533ec302601ecdefa67eee566e66336375836e77

**Comment by j4v** [comment]
So this has already been resolved @rossja ?
