### ISSUE TITLE
GCP "Lack of Service Account Key Rotation" finding raises "SYSTEM_MANAGED" keys

### ISSUE THREAD

**Issue by x4v13r64** [nccgroup/ScoutSuite#1085]
The https://github.com/nccgroup/ScoutSuite/blob/master/ScoutSuite/providers/gcp/rules/findings/iam-lack-of-service-account-key-rotation.json finding should only flag `USER_MANAGED` keys (https://cloud.google.com/iam/docs/reference/rest/v1/projects.serviceAccounts.keys), as `SYSTEM_MANAGED` keys are "managed and rotated by Google"

**Comment by fernando-gallego** [comment]
Fixed in 5.12.0
