### ISSUE TITLE
Create a CentOS based container

### ISSUE THREAD

**Issue by rossja** [nccgroup/ScoutSuite#1097]
**Is your feature request related to a problem? Please describe.**

Had someone reach out to me directly asking if it would be possible to support a CentOS based docker container.

**Describe the solution you'd like**

Create a CentOS based docker container

**Describe alternatives you've considered**

The Ubuntu one works, but CentOS is desired

**Additional context**

N/A

**Comment by rossja** [comment]
this shouldn't be that hard -- really it's just a matter of swapping out the base image, and then tweaking the dependency and SDK install scripts in `bin`. 

May want to consider how this could impact things though: https://thenewstack.io/red-hat-deprecates-linux-centos-in-favor-of-a-streaming-edition/

**Comment by j4v** [comment]
Is this something we want to support ourselves though? We're getting enough issues relating to the container as is, and there's not really a benefit to officially supporting multiple container OS'?

@rossja  would a better option be to base the container off of a distroless image, since we really only need it to have python?

**Comment by rossja** [comment]
i don't think it's true that only python is needed -- the underlying cloud provider SDKs are also required, unless I misunderstand? those (and the dependancies for them) are what the scripts currently install.

**Comment by rossja** [comment]
from a support POV: keeping things simple is definitely ideal. i'm happy to defer to the team if it seems better to limit things to a single container type.

**Comment by j4v** [comment]
> the underlying cloud provider SDKs are also required

Yes of course.

I meant something like https://github.com/GoogleContainerTools/distroless, but it seems they still use Debian as a base so it won't make a difference.

**Comment by j4v** [comment]
> from a support POV: keeping things simple is definitely ideal. i'm happy to defer to the team if it seems better to limit things to a single container type.

I'd say let's offer one container image and maintain that, there's already as much going on as we can manage!
