### ISSUE TITLE
Feature Request - Rules to check the particular CloudWatch metrics exists

### ISSUE THREAD

**Issue by nsinnakkavadi** [nccgroup/ScoutSuite#11]
Scout2 have any rules to find out any particular cloudwatch / cloudtrail metrics exist, if not then raise a flag.

For example, to check if any metrics related to IAM policy changes exist. If not exist, then need to raise a flag.

**Comment by j4v** [comment]
Closing as this is part of https://github.com/nccgroup/ScoutSuite/pull/679.
