### ISSUE TITLE
Report Generation Error -  scoutsuite_results in provider.js

### ISSUE THREAD

**Issue by JonFurmanski** [nccgroup/ScoutSuite#110]
After the script has completed against my AWS account, the report is not loading and I'm seeing an error of when provider.js is referencing "return scoutsuite_results". The parameters given were 
--provider and --csv-credentials. 

![image](https://user-images.githubusercontent.com/32278834/51417629-766b9980-1b44-11e9-98f2-7ab51b8174ae.png)

**Comment by j4v** [comment]
Can you try deleting the reports directory and re-running Scout?

**Comment by JonFurmanski** [comment]
@j4v I'm going to have to go with user error on this one. Haven't been able to re-produce that error.
