### ISSUE TITLE
Root Account without MFA should never be triggered in GovCloud

### ISSUE THREAD

**Issue by iamjoeker** [nccgroup/ScoutSuite#1132]
Running Scout against a GovCloud account triggers the following findings which do not make sense for GovCloud given that the Root user is inaccessible:

1. Root Account without MFA
2. Root Account without Hardware MFA

Here is the credential report output for the root user in GovCloud
```
Credentials Report
Creation Date: Fri Feb 21 2020 09:38:49 GMT-0600 (CST)
Last Used Date: No date available
Password Enabled: not_supported
Password Last Used: No date available
Password Last Changed: Invalid Date
MFA Active: false
Hardware MFA Active: false
Access Key 1 Active: false
Access Key 1 Last Used: No date available
Access Key 1 Last Rotated: No date available
Access Key 2 Active: false
Access Key 2 Last Used: No date available
Access Key 2 Last Rotated: No date available
Signing Cert 1 Active: false
Signing Cert 2 Active: false
```

NB: the `Password Enabled` field is `not_supported` indicating that the root user cannot have a password.  It looks like this could be checked in combination with the MFA active field. I'm happy to provide a PR to fix.

**Comment by j4v** [comment]
> NB: the Password Enabled field is not_supported indicating that the root user cannot have a password. It looks like this could be checked in combination with the MFA active field. I'm happy to provide a PR to fix.

That seems like a valid option, otherwise we'd have to look at the `partition` but I'm not sure it's exposed to the rules.

> I'm happy to provide a PR to fix.

Please do!

**Comment by iamjoeker** [comment]
I'll get a PR over this weekend.

**Comment by alessandrogonzalez** [comment]
Code merged into develop branch
