### ISSUE TITLE
False Positive Alert for static S3 Websites

### ISSUE THREAD

**Issue by f1remind** [nccgroup/ScoutSuite#1144]
Policies which allow getObject for all users and are attached to an S3 bucket are flagged as an alert.

Often these buckets may also be used to host static websites and require this setting, in that case this would be a false positive.

Example:
```Static website hosting: Enabled``` with a policy similar to this:
```json
{
    "Id":  "some_bucket_id" ,
    "Statement":  [
        {
        "Action": [
            "s3:GetObject"
        ],
        "Effect": "Allow",
        "Principal": "*",
        "Resource": "arn:aws:s3:::example.com/*",
        "Sid": "PublicReadForGetBucketObjects"
        }
    ] ,
    "Version":  "2012-10-17" 
}
```

Due to this combination being mostly a false positive a lower classification **or** a hint about this being a common false positive in these situation would be helpful. If static website hosting is not enabled this should still be classified as an alert if possible.

**Comment by j4v** [comment]
In these cases we recommend creating an exception (https://github.com/nccgroup/ScoutSuite/wiki/Creating-and-Using-an-Exceptions-File).
