### ISSUE TITLE
Wrong classification of DocumentDB in the report

### ISSUE THREAD

**Issue by weddige** [nccgroup/ScoutSuite#1172]
**Describe the bug**

In the report AWS DocumentDB is sorted into "Database/RDS" instead of "Database/DocumentDB"
**To Reproduce**

The **exact** CLI parameters used to run Scout Suite: `scout aws`

The AWS account contains a Postgres instance and two DocumentDB instances. All of them are listed under "Database/RDS"

**Comment by j4v** [comment]
I'm not sure what you mean by "sorted", but there's a tight coupling between the two services which likely explains what you're observing.

e.g., refer to:
- https://docs.aws.amazon.com/documentdb/latest/developerguide/documentdb-arns.html
- https://aws.amazon.com/documentdb/faqs/ (Q: Why are Amazon RDS permissions and resources required to use Amazon DocumentDB?)

**Comment by weddige** [comment]
> I'm not sure what you mean by "sorted", but there's a tight coupling between the two services which likely explains what you're observing.

I'm ware, that there is a coupling on the side of AWS, but the ScoutSuite report has separate categories:

![image](https://user-images.githubusercontent.com/1119426/110805007-015a0180-8281-11eb-8457-a323ce93482a.png)

TBH, I don't care if they are in two different categories in the report, but to have an empty category "DocumentDB" ist IMHO confusing.

**Comment by j4v** [comment]
Reopening to have a look at it.
