### ISSUE TITLE
Azure with no subscription/s

### ISSUE THREAD

**Issue by CG-root** [nccgroup/ScoutSuite#1188]
Unable to run the tool in Azure environment without subscription.
I am now performing an audit and unable to execute the tool. It seems that the environment (using 365) does not have any valid subscriptions as described in [this ](https://www.jasonfritts.me/2020/04/07/what-is-the-access-to-azure-active-directory-subscription-for/) article.

Is there a way to get to tool run without subscription?

Thanks

**Comment by j4v** [comment]
This is a duplicate of https://github.com/nccgroup/ScoutSuite/issues/1030.
