### ISSUE TITLE
AWS: Add support "Lightspin AWS IAM Vulnerability"

### ISSUE THREAD

**Issue by x4v13r64** [nccgroup/ScoutSuite#1246]
References:
* https://blog.lightspin.io/aws-iam-groups-authorization-bypass
* https://github.com/lightspin-tech/red-shadow

Important bit:
```
At first glance it looks like it will provide very good protection since deny overrides any allows and if access is denied for a group than it also denied for the group members. But in fact, in AWS - it doesn’t. The deny implies ONLY for Group object actions and all other User object actions are still allowed.
```

As per the code, all we need is a finding that checks policies for a specific `Resource` (https://github.com/lightspin-tech/red-shadow/blob/main/red-shadow.py#L5) and `Actions` (https://github.com/lightspin-tech/red-shadow/blob/main/red-shadow.py#L6).

**Comment by alessandrogonzalez** [comment]
Code merged into develop branch
