### ISSUE TITLE
AWS: Classify the "scope" of an IAM Policy

### ISSUE THREAD

**Issue by seittema** [nccgroup/ScoutSuite#1265]
**Is your feature request related to a problem? Please describe.**

We are trying classify an IAM policy as either Customer Managed or AWS Managed.  If it's AWS Managed, we currently do not allow *FullAccess* or *Administrator* AWS Managed Policies to be added to roles. If it's Customer Manged, then we evaluate the customer created policy to determine eligibility.  Currently there is no "Scope" assigned to the policy to distinguish between AWS Managed and Customer Managed

**Describe the solution you'd like**

Would like to have "scope" added to the policy resource.  Valid values would either be "AWS" or "Local".  This would allow user to distinguish between an AWS Managed Policy and a Customer Managed Policy

**Describe alternatives you've considered**

N/A

**Additional context**

It appears that AWS does not currently return scope in it's list_polices API call. However it is available as a filter when making the [API call](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/iam.html#IAM.Paginator.ListPolicies).  Looking at the [policies.py resource](https://github.com/nccgroup/ScoutSuite/blob/master/ScoutSuite/providers/aws/resources/iam/policies.py) it _may_ be as simple of making the API call twice, with scope set to AWS/Local each time, and passing into parse_policy the scope, but I'll be honest I'm not sure if that's true or what downstream effects that may have.
ie something like:

```
class Policies(AWSResources):
    async def fetch_all(self):
        for scope in ["AWS", "Local"]:
            raw_policies = await self.facade.iam.get_policies(scope)
            for raw_policy in raw_policies:
                name, resource = self._parse_policy(raw_policy, scope)
                self[name] = resource

    def _parse_policy(self, raw_policy, scope):
        policy = {}
        policy['id'] = raw_policy.pop('PolicyId')
        policy['name'] = raw_policy.pop('PolicyName')
        policy['arn'] = raw_policy.pop('Arn')
        policy['PolicyDocument'] = raw_policy.pop('PolicyDocument')
        policy['attached_to'] = raw_policy.pop('attached_to')
        policy['scope'] = scope

        return policy['id'], policy
```

And update the iam facade to something like
```
     async def get_policies(self, scope):
        policies = await AWSFacadeUtils.get_all_pages(
            'iam', None, self.session, 'list_policies', 'Policies', Scope=scope, OnlyAttached=True)
        await get_and_set_concurrently([self._get_and_set_policy_details], policies)
        return policies
```

**Comment by alessandrogonzalez** [comment]
Code merged into develop branch
