### ISSUE TITLE
SSL error while running Scoutsuite for AWS scans in docker container

### ISSUE THREAD

**Issue by kavya-5** [nccgroup/ScoutSuite#1308]
Running scoutsuite in a docker container instance for AWS cloud gives the following error
`__main__.py L185: Authentication failure: SSL validation failed for https://sts.amazonaws.com/ EOF occurred in violation of protocol (_ssl.c:1125)`
Re running the container solves the issue. The scan will succeed once the container instance is re run.

command used is:
`scout aws --access-keys --access-key-id "$ACCESSKEY" --secret-access-key "$SECRETKEY"`

**Comment by lowSoA** [comment]
Could you please share `--debug` logs?

**Comment by lowSoA** [comment]
Closed due to lack of feedback.
