### ISSUE TITLE
Azure --cli not working

### ISSUE THREAD

**Issue by V1s3r1on** [nccgroup/ScoutSuite#1321]
**Describe the bug**

After I installed ScoutSuite and azure-cli and I signed in with az login and then when I run python3 scout.py azure --cli it gives me the following error:

Authentication failure: cannot import name 'status_tag_messages' from 'knack.util'.

Within az login I am signed in so I don't know why it says that the authentication failed.

**To Reproduce**

I followed the installation guide from the ScoutSuite wiki, then I installed azure-cli. From there I do the following:

1. az login
2. Follow the login process and sign in
3. python3 scout.py azure --cli 
4. It then gives me the error message that I described above.

**Additional context**

I installed this on a fresh and clean ubuntu 21.04, tried it on kali linux too but that did not work very well so I decided to try it on a fresh ubuntu 21.04 VM.

**Comment by lowSoA** [comment]
Could you please confirm what version of ScoutSuite you are running and also the Python version used?

**Comment by fernando-gallego** [comment]
No response. Closing issue.
