### ISSUE TITLE
Incorrect condition for rule: iam-managed-policy-allows-full-privileges.json 

### ISSUE THREAD

**Issue by bryme** [nccgroup/ScoutSuite#1323]
This rule currently fires for any AWS account - I believe that the condition for the rule is incorrect.  Currently, one of the conditions in the json is:

        [
            "iam.policies.id.arn",
            "notContainString",
            "arn:aws:iam::aws:policy/aws-service-role"
        ],

I'm guessing that this was intended to be "arn:aws:iam::aws:policy/AdministratorAccess"

**Comment by x4v13r64** [comment]
Nope, that condition is to exclude service-linked role policies. My guess it that all the accounts you've run Scout against have policies allowing full (`*`) permissions.
