### ISSUE TITLE
Depth checks

### ISSUE THREAD

**Issue by cgaudit** [nccgroup/ScoutSuite#1328]
Hi
Is there a possibility to achieve Inspector matching results to Scout report?
In addition, Is it possible to have more depth results? For example scanning containers?

BR

**Comment by x4v13r64** [comment]
>  Is there a possibility to achieve Inspector matching results to Scout report?

Inspector isn't currently supported

> Is it possible to have more depth results? For example scanning containers?

Not sure what you mean by this, Scout doesn't currently support container scanning.

**Comment by cgaudit** [comment]
Thank's
