### ISSUE TITLE
Flag publicly accessible AWS RDS instances

### ISSUE THREAD

**Issue by sushantmimani** [nccgroup/ScoutSuite#1333]
**Is your feature request related to a problem? Please describe.**
RDS has a `Public Access` flag. If this is set to `Yes`, Amazon EC2 instances and devices outside the VPC can connect to your database. This can lead to a potential leak of sensitive data

**Describe the solution you'd like**

I would like to add a new finding for publicly accessible RDS instances

**Describe alternatives you've considered**
N/A

**Comment by lowSoA** [comment]
Closing, this is merged in `develop`.
