### ISSUE TITLE
Update favicon

### ISSUE THREAD

**Issue by j4v** [nccgroup/ScoutSuite#134]
Update the favicon embedded in the HTML reports with the following:

[favicon.ico.zip](https://github.com/nccgroup/ScoutSuite/files/2818231/favicon.ico.zip)

**Comment by j4v** [comment]
The favicon is a base64'd image embedded in the report. This is bad, move it to a static file.

**Comment by vifor2** [comment]
> The favicon is a base64'd image embedded in the report. This is bad, move it to a static file.

Are you sure you checked on develop? It's already a static file on develop, [here's the commit where it happened](https://github.com/nccgroup/ScoutSuite/pull/238/commits/4f65bc4ca955876429cd8d93a71b218325f9a03b).

![image](https://user-images.githubusercontent.com/17322874/54460775-e65f6000-4740-11e9-9a00-b3b2a0dd940e.png)
