### ISSUE TITLE
Unable to view report.html file in any browser

### ISSUE THREAD

**Issue by vshah2ndwatch** [nccgroup/ScoutSuite#1340]
I ran the report with Scout2 and then with ScoutSuite. I am seeing the same issue where a report file is being generated (filename.html) in scoutsuite-report folder but when I try to open it in any browsers, I see this message on the browser: "Loading data, this may take a while...".
There is no update to the page and I have confirmed that Java is enabled on all my browsers where I tried.

**Comment by alessandrogonzalez** [comment]
Hi,

If the report is empty, it might be that the credentials used do not have sufficient permissions to access resources in your account. The following page lists the permissions needed for Scout Suite to run without incurring in authorization problems (assuming that you are using it for AWS):
•	https://github.com/nccgroup/ScoutSuite/wiki/Amazon-Web-Services#permissions

If the permissions are ok, and the report is still empty, do you have any error during the execution of the tool? 

A useful option to try to triage the problem might be to use the “ --debug" option, that will get you a full exception stack trace. 

If you don't want to post here the log for your execution, please send it to scoutsuite@nccgroup.com so we can have a look to this problem.

**Comment by vshah2ndwatch** [comment]
Hi Alessandro,
Thank you for getting back to me. Let me explain both the points you mentioned:

  1.  Permissions: The user I am logged with is an Admin user. So permissions are not an issue.
  2.  I do not think the report is empty. When I try to open the html file on the browser, it just displays "Loading data....". However when I cat or vi the file on Linux, I see content but it's not displayed in a way that I can make sense out of. Reading the file on Linux shows stuff including security groups, NACL's, etc. So I know the file is not empty. The issue is for the file to be read properly by the browser.

Thanks,
Vivek Shah
Cloud Consultant

From: alessandrogonzalez ***@***.***>
Sent: Thursday, September 2, 2021 3:43 AM
To: nccgroup/ScoutSuite ***@***.***>
Cc: Vivek Shah ***@***.***>; Author ***@***.***>
Subject: <External> Re: [nccgroup/ScoutSuite] Unable to view report.html file in any browser (#1340)


Hi,

If the report is empty, it might be that the credentials used do not have sufficient permissions to access resources in your account. The following page lists the permissions needed for Scout Suite to run without incurring in authorization problems (assuming that you are using it for AWS):
* https://github.com/nccgroup/ScoutSuite/wiki/Amazon-Web-Services#permissions<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnccgroup%2FScoutSuite%2Fwiki%2FAmazon-Web-Services%23permissions&data=04%7C01%7Cvshah%402ndwatch.com%7C2e0940d1806a4ad9a74b08d96dedb882%7C8242a0a9c4154206be3906637ad2817a%7C0%7C0%7C637661690059320587%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=XECxL2K%2Bx5SyRG9hnY5srzPn3dS%2BmoF3AqlcQNkJGkw%3D&reserved=0>

If the permissions are ok, and the report is still empty, do you have any error during the execution of the tool?

A useful option to try to triage the problem might be to use the " --debug" option, that will get you a full exception stack trace.

If you don't want to post here the log for your execution, please send it to ***@***.******@***.***> so we can have a look to this problem.

-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnccgroup%2FScoutSuite%2Fissues%2F1340%23issuecomment-911398675&data=04%7C01%7Cvshah%402ndwatch.com%7C2e0940d1806a4ad9a74b08d96dedb882%7C8242a0a9c4154206be3906637ad2817a%7C0%7C0%7C637661690059330563%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=3zpyxHHUa3cj9UE9y00q%2B%2F3oXwY7vjvzDOiPtNb2M%2Fk%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAT7H2YPESEHLPN526HTTG7LT742KTANCNFSM5DHPNFCQ&data=04%7C01%7Cvshah%402ndwatch.com%7C2e0940d1806a4ad9a74b08d96dedb882%7C8242a0a9c4154206be3906637ad2817a%7C0%7C0%7C637661690059330563%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=L42wEgLog7QiioAUL7mckCaXrDNRbc7EJGjthQB3v0c%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cvshah%402ndwatch.com%7C2e0940d1806a4ad9a74b08d96dedb882%7C8242a0a9c4154206be3906637ad2817a%7C0%7C0%7C637661690059340520%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Hn2nAOw8uO%2B8GurhN%2Fwz0dHTcjLZARCnw2HDW9NZ9lg%3D&reserved=0> or Android<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cvshah%402ndwatch.com%7C2e0940d1806a4ad9a74b08d96dedb882%7C8242a0a9c4154206be3906637ad2817a%7C0%7C0%7C637661690059340520%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=GAULStxjoPpmZplYBpWQTviKFRNDqtNaEOlxezapeKA%3D&reserved=0>.

**Comment by vshah2ndwatch** [comment]
Also since I ran the tool in my test environment, I don't mind sharing the report file. Please find it attached. I ran this report with -debug option.

Thanks,
Vivek Shah
Cloud Consultant

From: Vivek Shah
Sent: Thursday, September 2, 2021 8:07 AM
To: nccgroup/ScoutSuite ***@***.***>; nccgroup/ScoutSuite ***@***.***>; Alessandro Gonzalez ***@***.***>
Cc: Author ***@***.***>
Subject: RE: <External> Re: [nccgroup/ScoutSuite] Unable to view report.html file in any browser (#1340)

Hi Alessandro,
Thank you for getting back to me. Let me explain both the points you mentioned:

  1.  Permissions: The user I am logged with is an Admin user. So permissions are not an issue.
  2.  I do not think the report is empty. When I try to open the html file on the browser, it just displays "Loading data....". However when I cat or vi the file on Linux, I see content but it's not displayed in a way that I can make sense out of. Reading the file on Linux shows stuff including security groups, NACL's, etc. So I know the file is not empty. The issue is for the file to be read properly by the browser.

Thanks,
Vivek Shah
Cloud Consultant

From: alessandrogonzalez ***@***.******@***.***>>
Sent: Thursday, September 2, 2021 3:43 AM
To: nccgroup/ScoutSuite ***@***.******@***.***>>
Cc: Vivek Shah ***@***.******@***.***>>; Author ***@***.******@***.***>>
Subject: <External> Re: [nccgroup/ScoutSuite] Unable to view report.html file in any browser (#1340)


Hi,

If the report is empty, it might be that the credentials used do not have sufficient permissions to access resources in your account. The following page lists the permissions needed for Scout Suite to run without incurring in authorization problems (assuming that you are using it for AWS):
* https://github.com/nccgroup/ScoutSuite/wiki/Amazon-Web-Services#permissions<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnccgroup%2FScoutSuite%2Fwiki%2FAmazon-Web-Services%23permissions&data=04%7C01%7Cvshah%402ndwatch.com%7C2e0940d1806a4ad9a74b08d96dedb882%7C8242a0a9c4154206be3906637ad2817a%7C0%7C0%7C637661690059320587%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=XECxL2K%2Bx5SyRG9hnY5srzPn3dS%2BmoF3AqlcQNkJGkw%3D&reserved=0>

If the permissions are ok, and the report is still empty, do you have any error during the execution of the tool?

A useful option to try to triage the problem might be to use the " --debug" option, that will get you a full exception stack trace.

If you don't want to post here the log for your execution, please send it to ***@***.******@***.***> so we can have a look to this problem.

-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnccgroup%2FScoutSuite%2Fissues%2F1340%23issuecomment-911398675&data=04%7C01%7Cvshah%402ndwatch.com%7C2e0940d1806a4ad9a74b08d96dedb882%7C8242a0a9c4154206be3906637ad2817a%7C0%7C0%7C637661690059330563%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=3zpyxHHUa3cj9UE9y00q%2B%2F3oXwY7vjvzDOiPtNb2M%2Fk%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAT7H2YPESEHLPN526HTTG7LT742KTANCNFSM5DHPNFCQ&data=04%7C01%7Cvshah%402ndwatch.com%7C2e0940d1806a4ad9a74b08d96dedb882%7C8242a0a9c4154206be3906637ad2817a%7C0%7C0%7C637661690059330563%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=L42wEgLog7QiioAUL7mckCaXrDNRbc7EJGjthQB3v0c%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cvshah%402ndwatch.com%7C2e0940d1806a4ad9a74b08d96dedb882%7C8242a0a9c4154206be3906637ad2817a%7C0%7C0%7C637661690059340520%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Hn2nAOw8uO%2B8GurhN%2Fwz0dHTcjLZARCnw2HDW9NZ9lg%3D&reserved=0> or Android<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cvshah%402ndwatch.com%7C2e0940d1806a4ad9a74b08d96dedb882%7C8242a0a9c4154206be3906637ad2817a%7C0%7C0%7C637661690059340520%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=GAULStxjoPpmZplYBpWQTviKFRNDqtNaEOlxezapeKA%3D&reserved=0>.

**Comment by alessandrogonzalez** [comment]
Hi vshah2ndwatch,

The file you attached was only the HTML file of the report, which is only the "template". The actual scan data can be found in the`scoutsuite-report/scoutsuite-results/` folder. There should be some javascript files inside (look for a `scoutsuite_results*.js` file)

Could you please check if they are empty or do not exist? (to make sure it's not a permission problem)

Thanks,
Alessandro

**Comment by vshah2ndwatch** [comment]
The file does exist and I checked, it's not empty.

(venv) ***@***.*** scoutsuite-report]$ ll
total 188
-rw-rw-r-- 1 ec2-user ec2-user 192159 Sep  2 13:22 aws-727806681618.html
drwxrwxr-x 4 ec2-user ec2-user     27 Sep  1 20:04 inc-bootstrap
drwxrwxr-x 5 ec2-user ec2-user     43 Sep  1 20:04 inc-fontawesome
drwxrwxr-x 2 ec2-user ec2-user     34 Sep  1 20:04 inc-handlebars
drwxrwxr-x 2 ec2-user ec2-user     33 Sep  1 20:04 inc-jquery
drwxrwxr-x 3 ec2-user ec2-user    148 Sep  1 19:52 inc-scoutsuite
drwxrwxr-x 2 ec2-user ec2-user    101 Sep  1 20:04 scoutsuite-results
(venv) ***@***.*** scoutsuite-report]$

(venv) ***@***.*** scoutsuite-report]$ cd scoutsuite-results/
(venv) ***@***.*** scoutsuite-results]$ ll
total 4236
-rw-rw-r-- 1 ec2-user ec2-user      16 Sep  2 13:22 scoutsuite_exceptions_aws-727806681618.js
-rw-rw-r-- 1 ec2-user ec2-user 4330122 Sep  2 13:22 scoutsuite_results_aws-727806681618.js

I looked at the contents in this file and it's not empty.
(venv) ***@***.*** scoutsuite-results]$ vi scoutsuite_results_aws-727806681618.js

Thanks,
Vivek Shah
Cloud Consultant

From: alessandrogonzalez ***@***.***>
Sent: Thursday, September 2, 2021 10:55 AM
To: nccgroup/ScoutSuite ***@***.***>
Cc: Vivek Shah ***@***.***>; Author ***@***.***>
Subject: <External> Re: [nccgroup/ScoutSuite] Unable to view report.html file in any browser (#1340)


Hi vshah2ndwatch,

The file you attached was only the HTML file of the report, which is only the "template". The actual scan data can be found in thescoutsuite-report/scoutsuite-results/ folder. There should be some javascript files inside (look for a scoutsuite_results*.js file)

Could you please check if they are empty or do not exist? (to make sure it's not a permission problem)

Thanks,
Alessandro

-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnccgroup%2FScoutSuite%2Fissues%2F1340%23issuecomment-911830880&data=04%7C01%7Cvshah%402ndwatch.com%7C933daabf6ee44f470d5008d96e2a0c32%7C8242a0a9c4154206be3906637ad2817a%7C0%7C0%7C637661949169890087%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=zhdsa6qpjY%2Bvx1qtG1rZVCazIvW5CzYgbuapJKZQR5I%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAT7H2YONB7M363YWZSY67BLT76M57ANCNFSM5DHPNFCQ&data=04%7C01%7Cvshah%402ndwatch.com%7C933daabf6ee44f470d5008d96e2a0c32%7C8242a0a9c4154206be3906637ad2817a%7C0%7C0%7C637661949169900051%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=NmJvAI5TrvwYD96McrLWaXd%2B%2BS%2FClVHCbpY7wI0JVy4%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cvshah%402ndwatch.com%7C933daabf6ee44f470d5008d96e2a0c32%7C8242a0a9c4154206be3906637ad2817a%7C0%7C0%7C637661949169900051%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=AOsn%2BFbNrYHBZR%2F90Z8smHWfWG9cpdaXymIW%2FZa%2Fwoc%3D&reserved=0> or Android<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cvshah%402ndwatch.com%7C933daabf6ee44f470d5008d96e2a0c32%7C8242a0a9c4154206be3906637ad2817a%7C0%7C0%7C637661949169910006%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=C7mjcdY0HuFvnChfeAdpAO9Z%2BTKZXQTjKpjjeUTNkG0%3D&reserved=0>.

**Comment by alessandrogonzalez** [comment]
Hi,

From this output, I can see that the javascript file actually has some content, and also that you are running Scout Suite from an EC2 instance.

How are you viewing the report? are you downloading the report to your machine to open it on the browser?

If so, try to download the full scoutsuite-report folder with all its content, and not only the HTML file. 

Opening the HTML report in the browser will require the presence of all the other files to load correctly. If they are not present, the report will show as empty with the "Loading data" message.

**Comment by vshah2ndwatch** [comment]
Yes that was the problem. I was only downloading the html file and the output was not showing. Now after downloading the complete folder contents, I am able to view the report. Thank you very much.

Thanks,
Vivek Shah
Cloud Consultant

From: alessandrogonzalez ***@***.***>
Sent: Thursday, September 2, 2021 11:31 AM
To: nccgroup/ScoutSuite ***@***.***>
Cc: Vivek Shah ***@***.***>; Author ***@***.***>
Subject: <External> Re: [nccgroup/ScoutSuite] Unable to view report.html file in any browser (#1340)


Hi,

From this output, I can see that the javascript file actually has some content, and also that you are running Scout Suite from an EC2 instance.

How are you viewing the report? are you downloading the report to your machine to open it on the browser?

If so, try to download the full scoutsuite-report folder with all its content, and not only the HTML file.

Opening the HTML report in the browser will require the presence of all the other files to load correctly. If they are not present, the report will show as empty with the "Loading data" message.

-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnccgroup%2FScoutSuite%2Fissues%2F1340%23issuecomment-911861130&data=04%7C01%7Cvshah%402ndwatch.com%7Ca9aa576b59844169b23308d96e2f1049%7C8242a0a9c4154206be3906637ad2817a%7C0%7C0%7C637661970711533167%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=jc5lVuLDtXzRRLib3Y2AZRKjp0gK3F5z56nAFl2YY%2FQ%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAT7H2YP5XH2PUGJTUA2TA4TT76RETANCNFSM5DHPNFCQ&data=04%7C01%7Cvshah%402ndwatch.com%7Ca9aa576b59844169b23308d96e2f1049%7C8242a0a9c4154206be3906637ad2817a%7C0%7C0%7C637661970711543126%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=c2AZ3pRVMW298qbDnkZ%2B1%2B4VnSO2OVpIjil%2FhJ7glwY%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cvshah%402ndwatch.com%7Ca9aa576b59844169b23308d96e2f1049%7C8242a0a9c4154206be3906637ad2817a%7C0%7C0%7C637661970711543126%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=te9vUqRG%2FgULQFXSyg%2BHKX7qU9geOh8Johe9DzqXgL4%3D&reserved=0> or Android<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cvshah%402ndwatch.com%7Ca9aa576b59844169b23308d96e2f1049%7C8242a0a9c4154206be3906637ad2817a%7C0%7C0%7C637661970711553087%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=hIblIMcKFUxQNMktucZc0sSfhDLT0SinQ0h69i%2B9GSE%3D&reserved=0>.
