### ISSUE TITLE
Typo in description for Trail Is Not Integrated with CloudWatch

### ISSUE THREAD

**Issue by definity** [nccgroup/ScoutSuite#1350]
"real-time" is misspelled as "ral-time"

_The lack of integration with CloudWatch hinders **ral-time** and historic activity logging as well as not allowing the configuration of alarms and notifications for anomalous account activity._

https://github.com/nccgroup/ScoutSuite/blob/b9b8e201a45bd63835f611eec67fe3bb7c892a0a/ScoutSuite/providers/aws/rules/findings/cloudtrail-no-cloudwatch-integration.json#L3

**Comment by lowSoA** [comment]
Already implemented in #1327
