### ISSUE TITLE
Missing end of line in match conditions

### ISSUE THREAD

**Issue by bishopfaure** [nccgroup/ScoutSuite#1356]
**Describe the bug**

There an issue with the https://github.com/nccgroup/ScoutSuite/blob/master/ScoutSuite/providers/aws/rules/findings/route53-domain-transferlock-not-authorized.json finding detection, but the root cause might affect other findings as well. I think the matches are made improperly, causing Scoutsuite to detect invalid domains.

For instance, `mydomain.click` (sorry the real information is anonymized but it is very easy to understand) would be flagged by this rule because of this line : https://github.com/nccgroup/ScoutSuite/blob/b9b8e201a45bd63835f611eec67fe3bb7c892a0a/ScoutSuite/providers/aws/rules/findings/route53-domain-transferlock-not-authorized.json#L32, but the `click` TLD does support transfer lock.

**To Reproduce**

Register a domain under `.click`, run ScoutSuite against the environment and see that `Domain Transfer Lock Not Supported by TLD` finding is reported despite incorrect.

**Comment by x4v13r64** [comment]
Yep, looks like they should all end with a `$`, e.g. `.*\\.cl$`.

**Comment by Tzaoh** [comment]
Currently list of not supported domain list (+ regex included).

```
".*\\.ch$",
".*\\.cl$",
".*\\.co.nz$",
".*\\.co.uk$",
".*\\.co.za$",
".*\\.com.ar$",
".*\\.com.au$",
".*\\.de$",
".*\\.es$",
".*\\.eu$",
".*\\.fi$",
".*\\.fr$",
".*\\.it$",
".*\\.jp$",
".*\\.me.uk$",
".*\\.net.au$",
".*\\.net.nz$",
".*\\.nl$",
".*\\.org.nz$",
".*\\.org.uk$",
".*\\.qa$",
".*\\.ru$",
".*\\.se$",
".*\\.uk$"
```

The above list was generated from parsing the AWS documentation with [this python script](https://gist.github.com/Tzaoh/eb57e153b02e3822c294fec265d5bfa3). Maybe it could be worth to include the script in the release flow to verify the list on every new release.

I can foresee that the last one (and similar ones) might give us some trouble as there are multiple `uk` subdomains which would match the `".*\\.uk$"` expression if they are accepted in the future by Amazon (i.e. `.net.uk`). Full list of Second-level domains for `.uk` [here](https://en.wikipedia.org/wiki/.uk#Second-level_domains).
