### ISSUE TITLE
Various UI/UX bugs and enhancements Part 1

### ISSUE THREAD

**Issue by j4v** [nccgroup/ScoutSuite#136]
Font color in the nav bar is a bit off:

<kbd><img src="https://user-images.githubusercontent.com/4206926/52112211-255caa80-2606-11e9-925d-1190e9175742.jpg" /></kbd>

<kbd><img src="https://user-images.githubusercontent.com/4206926/52112212-255caa80-2606-11e9-965c-d2fc4bd45465.jpg" /></kbd>

The badges are a bit off for a number of elements with a "0" count. Ideally a gray badge should be used:

<kbd><img src="https://user-images.githubusercontent.com/4206926/52112213-255caa80-2606-11e9-96a3-bad32b354516.jpg" /></kbd>

<kbd><img src="https://user-images.githubusercontent.com/4206926/52112215-25f54100-2606-11e9-8f06-d29b21fdf989.jpg" /></kbd>

<s>The id_suffix highlighting is broken: </s> (fixed in #159 )

<kbd><img src="https://user-images.githubusercontent.com/4206926/52112217-25f54100-2606-11e9-9862-42f2bbb84d98.jpg" /></kbd>

The loading message is broken:

<kbd><img src="https://user-images.githubusercontent.com/4206926/52230453-b4dcb480-28b7-11e9-81c6-661c3b54ac53.jpg" /></kbd>

**Comment by j4v** [comment]
> The loading message is broken:

Most of the time this will only flash as loading is very quick, but for a large report it's a bit ugly to see.

**Comment by Aboisier** [comment]
Closing, implemented in #167 .
