### ISSUE TITLE
Azure Scanning

### ISSUE THREAD

**Issue by cgaudit** [nccgroup/ScoutSuite#1363]
Hi,
I got only one check on the Azure Active Directory Dashboard (Warning: Guest Users in Use).
Does the tool knows to scan for security misconfiguration also at the O365 Azure and VPN Gateway
Is it required additional permissions? Where can I see the list of checks that is made while testing the environment to each of the services?

BR

**Comment by x4v13r64** [comment]
> Does the tool knows to scan for security misconfiguration also at the O365 Azure and VPN Gateway

no

**Comment by cgaudit** [comment]
Thank's
Is this abilities are planned to be added in the future?
