### ISSUE TITLE
Can I know when Azure  will be available?

### ISSUE THREAD

**Issue by challs1** [nccgroup/ScoutSuite#137]
@j4v can i know when Azure will be available to use for Policy Complaince like AWS?

**Comment by j4v** [comment]
I'm not sure what you mean by "Policy Complaince"?

We're working on implementing CIS benchmark as well as additional findings, but I can't provide an ETA other then "it's in progress".

**Comment by challs1** [comment]
@j4v CIS standards only. Can i know the github link for Azure please?

**Comment by j4v** [comment]
> Can i know the github link for Azure please?

I'm not sure what you mean.

**Comment by challs1** [comment]
So can I able to use it by cloning the repository and run for azure ?? If
so what are the services that covered upto now as per CIS standards ??

**Comment by j4v** [comment]
Latest functionalities can be found in the `develop` branch. At his moment there are no findings for Azure, this is a work in progress. 

Covering the full Azure CIS benchmark won't be available for a few months.
