### ISSUE TITLE
 Initialization failure: module 'collections' has no attribute 'Callable'

### ISSUE THREAD

**Issue by mandeeps13k** [nccgroup/ScoutSuite#1370]
**Description**

- Upon starting the scoutsuite both with --user-account OR --service-account, I'm getting the following error :

2021-10-18 17:04:32 Mandeeps-MacBook-Pro.local scout[44655] INFO Launching Scout
2021-10-18 17:04:32 Mandeeps-MacBook-Pro.local scout[44655] INFO Authenticating to cloud provider
2021-10-18 17:04:33 Mandeeps-MacBook-Pro.local scout[44655] ERROR __main__.py L212: Initialization failure: module 'collections' has no attribute 'Callable'

**To Reproduce**

- python scout.py gcp --user-account , python scout.py gcp --service-account [Path_to_json]

**Additional context**

This happens just on installation and first run

**Comment by mandeeps13k** [comment]
Can anyone look at this issue?

**Comment by hilarex** [comment]
I have the same issue, where you able to find the cause ? Or how to fix it ?

**Comment by hilarex** [comment]
I was using python 3.10 in the virtual environment, I downgraded to 3.8.9 and now it is working

**Comment by starbuck3000** [comment]
For those who still reach this page through search engines: scout documentation indicates that scout is only compatible with Python 3.8 but recent distros install later versions (e.g., 3.10). Solution is to install Python3.8 alongside current version, then use virtualenv to switch to desired Python version.

Example on Fedora:
$sudo dnf install python3.8
$python3.8 -m venv env
$source env/bin/activate
$scout gcp --user-account
