### ISSUE TITLE
Unable to generate report on some aws resources

### ISSUE THREAD

**Issue by jkayodeabusi** [nccgroup/ScoutSuite#1376]
ERROR browser.py L107: Unable to get "sg-0911ded1e9f7b8593" from target object {'sg-00308e5bc9': {'name': 'fs-east-cluster-control-plane', 'id': 'sg-003008e5bc9', 'arn': 'arn:aws:ec2:us-east-1:4013716:security-group/sg-00356008e5bc9', 'description': 'Traffic to and from the fs-east-1-2 EKS control plane'

**Comment by fernando-gallego** [comment]
Hi @jkayodeabusi , are you still experiencing this issue on version 5.12.0?
