### ISSUE TITLE
AWS Minimal Privileges Policy Missing S3 Permission + Silent Failures

### ISSUE THREAD

**Issue by ncc-wenright** [nccgroup/ScoutSuite#1377]
## Description

The AWS Minimal Privileges Policy [listed in the wiki](https://github.com/nccgroup/ScoutSuite/wiki/AWS-Minimal-Privileges-Policy) lacks the 's3:GetBucketPublicAccessBlock' permission, which appears to be required by Scoutsuite for retrieving "Public Access Block Configuration" data for a given S3 bucket. Running Scoutsuite via an IAM role configured with this policy results in silent failures and a default value of "disabled" for all Public Access Block Configuration values in the report output for S3 buckets, resulting in false positive findings.

## Reproduction

1. Configure an AWS principal for use with Scoutsuite using the AWS Minimal Privileges Policy from the wiki.
2. In the same AWS account, create a new S3 bucket with default permissions. Ensure "Block all public access" setting is enabled.

<img width="1195" alt="bucket_configuration" src="https://user-images.githubusercontent.com/48224216/141189626-92c11a9b-4385-4bc3-84dd-4d497e909477.png">

3. Run Scoutsuite against the target account using the principal configured in step 1. (Note a lack of error messages relating to S3 permissions)
    **scout aws -p test --debug**
4. Inspect the results for the configured S3 bucket. Within the Public Access Block Configuration section, note that all values list "Disabled" despite being specifically enabled in step 2.

<img width="849" alt="bucket_scout_output" src="https://user-images.githubusercontent.com/48224216/141189621-286c5da6-7232-4735-b551-119365bdd168.png">

## Other Details

Python 3.9.0
Scout Suite 5.10.2
[scoutsuite_errors_aws-test.json.txt](https://github.com/nccgroup/ScoutSuite/files/7515754/scoutsuite_errors_aws-test.json.txt)

**Comment by n1t1nv3rma** [comment]
You may just rely on AWS built-in arn:aws:iam::aws:policy/SecurityAudit policy, which is RO too.
May combine arn:aws:iam::aws:policy/job-function/ViewOnlyAccess too "if needed".

**Comment by x4v13r64** [comment]
The https://github.com/nccgroup/ScoutSuite/wiki/AWS-Minimal-Privileges-Policy policy has been updated.
