### ISSUE TITLE
Can I talk to someone about the recurse and pass_conditions functions?

### ISSUE THREAD

**Issue by rtomlinson-latacora** [nccgroup/ScoutSuite#138]
https://github.com/nccgroup/ScoutSuite/blob/9139f5d9e9841ee783293ca707ebe4614dd9f9b5/ScoutSuite/core/utils.py

We have a gcp account with 1 million+ buckets. I want to understand what these functions are doing as I can only get so far by just looking at them on my own. Thanks.

**Comment by j4v** [comment]
These two methods are part of Scout's rule engine. They allow evaluating findings against resources.

Are you having issues running Scout against all those buckets? I'd think you'd run into memory issues.

**Comment by rtomlinson-latacora** [comment]
Yeah, memory and disk issues. If we just throw more resources at it it will eventually complete, but I was hoping to avoid doing that unless necessary.

**Comment by j4v** [comment]
This is an issue we've had in our TODO for a while, the main issue is having an environment to test with.

Could you please tell me:
- The exact amount of buckets in the Project you're scanning
- How much memory Scout ends up using
- The size of the JSON file being created
- How long it takes to run

If you don't want to share this publicly feel free to contact me at xavier.garceau-aranda[at]nccgroup.com, I'm quite keen to address this issue.

**Comment by rtomlinson-latacora** [comment]
This issue has been taken off github.
