### ISSUE TITLE
False positive for "No CloudWatch Alarm for IAM Policy Changes" 

### ISSUE THREAD

**Issue by edde80** [nccgroup/ScoutSuite#1382]
The AWS Check: "No CloudWatch Alarm for IAM Policy Changes" throws always a false positive.

The reason is a typo in the line mentioned below. There is an "extra dot" exactly here: ($..eventName=DeleteRolePolicy)

https://github.com/nccgroup/ScoutSuite/blob/db827e3d8e36e3bc7adcb8c62f2453960353c2ef/ScoutSuite/providers/aws/resources/cloudwatch/base.py#L45

This causes the result always to be False, even if there is a Cloudwatch Alarm is setup as recommended.

**Comment by fernando-gallego** [comment]
Fixed in version 5.12.0
