### ISSUE TITLE
Are we dead yet? No updates for a LONG time......

### ISSUE THREAD

**Issue by munntjlx** [nccgroup/ScoutSuite#1399]
**Is your feature request related to a problem? No

Can we get an update if this project is dead?

Wondering what has happened, or has this moved to another repo?

**Comment by liyun-li** [comment]
@munntjlx The project is very much alive. Check the `develop` branch.

**Comment by alessandrogonzalez** [comment]
@munntjlx it is true that we have not released an official version in a long time, but we are planning to. As @liyun-li commented, there is stuff happening in the `develop` branch, pending to be officially released.
