### ISSUE TITLE
Minimal AWS policy in wiki is out of date

### ISSUE THREAD

**Issue by rdegraaf** [nccgroup/ScoutSuite#1410]
Version 5.11 added some new capabilities to ScoutSuite but the minimal policy provided at https://github.com/nccgroup/ScoutSuite/wiki/AWS-Minimal-Privileges-Policy has not been updated to give permission for those checks.

The following need to be added to that list:

    cloudfront:ListDistributions
    codebuild:BatchGetPRojects
    codebuild:ListProjects

There may be other permissions needed as well; I did not attempt a full test pass.

**Comment by guardbadger** [comment]
Also, you can reduce a couple of duplicate entries:
elasticloadbalancing:DescribeListeners
elasticloadbalancing:DescribeLoadBalancerAttributes
elasticloadbalancing:DescribeLoadBalancers
elasticloadbalancing:DescribeTags

**Comment by n1t1nv3rma** [comment]
You may just rely on AWS built-in arn:aws:iam::aws:policy/**SecurityAudit** policy, which is RO too.

**Comment by x4v13r64** [comment]
The https://github.com/nccgroup/ScoutSuite/wiki/AWS-Minimal-Privileges-Policy policy has been updated.
