### ISSUE TITLE
AWS "Potential Secret in Instance User Data" false positives

### ISSUE THREAD

**Issue by rbailey-godaddy** [nccgroup/ScoutSuite#1417]
**Describe the bug**

"Potential Secret in Instance User Data" is easily triggered by innocuous strings that clearly are not actual secrets.

**To Reproduce**

In the case of "AWS Secret Access Key" detection, all that is required is for user data to contain a path name that is at least 40 characters long and doesn't have "non-encoding characters" (i.e. a space or dash or dot or similar). For example:

```ps
$WebClient.DownloadFile("https://inspector-agent.amazonaws.com/windows/installer/latest/AWSAgentInstall.exe","C:\temp\AWSAgentInstall.exe")
```

This results in the following detection:

```json
"user_data_secrets": {
    "AWS Secret Access Keys": [
        "com/windows/installer/latest/AWSAgentIns"
    ]
}
```

**Additional context**

The regular expression is insufficiently paranoid. Many (but not all) false positives could be avoided if we checked to avoid matching substrings of longer strings of text; it is unlikely that actual secrets will be unparseably embedded in longer sequences, and longer strings cannot be valid secrets (in the same way shorter strings already are excluded).

A PR with a proposed solution will be in your hands shortly.

**Comment by fernando-gallego** [comment]
Solved in version 5.12.0. Thank you for the PR!
