### ISSUE TITLE
Export entire findings to json/ csv

### ISSUE THREAD

**Issue by userbradley** [nccgroup/ScoutSuite#1440]
**Is your feature request related to a problem? Please describe.**

It would be nice to be able to export the entire findings to JSON and CSV.

Specifically with GCP, having multiple projects under the org, we would require the project name where the finding is reported. 

**Describe the solution you'd like**

An `export to json` button at the top, which exports all findings, or a json file that is automatically generated when the HTML report is created

**Describe alternatives you've considered**

~Crying my self to sleep~ Manually exporting each section

**Additional context**

Would be nice to have a CSV with simple descriptions, for exporting to Jira

**Comment by x4v13r64** [comment]
You can grab the JSON in the results file - https://github.com/nccgroup/ScoutSuite/wiki/Exporting-and-Programmatically-Accessing-the-Report#1-data-location-and-format.
