### ISSUE TITLE
Shell Command Error in Wiki

### ISSUE THREAD

**Issue by alex941115** [nccgroup/ScoutSuite#1441]
Instructions on how to parse results using tail and jq have an incorrect shell command

Please provide:

- The example shell command for processing a results file using tail (to skip the first line) and pipe to jq is incorrect
- See the two commands under the last heading #3 here -- https://github.com/nccgroup/ScoutSuite/wiki/Exporting-and-Programmatically-Accessing-the-Report

**To Reproduce**

$ tail /ScoutSuite/scoutsuite-report/scoutsuite-results/scoutsuite_results-<report name>.js -n +2 | jq '.' 

**Additional context**

The correct order of arguments is
$ tail -n +2 /ScoutSuite/scoutsuite-report/scoutsuite-results/scoutsuite_results-<report name>.js | jq '.'

**Comment by fernando-gallego** [comment]
Running those 2 commands produces the same output.
