### ISSUE TITLE
How to include other services to be audited by ScoutSuite

### ISSUE THREAD

**Issue by gidbalugo** [nccgroup/ScoutSuite#1442]
We have been using Scout Suite in our AWS stack but we've noticed that it is not displaying reports under **Container**.

I checked the wiki and I'm not sure where to check related issues with AWS service coverage.

![image](https://user-images.githubusercontent.com/7790353/182816124-e089a1c5-d767-49c4-a93d-5aba89328280.png)

Is this a bug or where do we start to cover this service in our audit?

**Comment by fernando-gallego** [comment]
Hi,

This does not seem to be an issue. There are currently checks and findings for ECR, ECS and EKS services. If you do not see findings for these services in your report there are a few possibilities: you do not have any resources of that type in the account you are scanning, or the credentials you supplied to ScoutSuite do not have enough read permissions on those services.
