### ISSUE TITLE
AWS VPC - Show all doesn't work

### ISSUE THREAD

**Issue by Aboisier** [nccgroup/ScoutSuite#146]
In the AWS VPC issues, the `Show all` doesn't seem to work (doesn't do anything anymore):

<kbd><img src="https://user-images.githubusercontent.com/4206926/52112219-25f54100-2606-11e9-8813-013a8c9a869b.jpg" /></kbd>

(Moved from #136 to a new issue)

**Comment by j4v** [comment]
Fixed in `develop`
