### ISSUE TITLE
ImportError: cannot import name 'AzureCliCredential' from 'azure.identity'

### ISSUE THREAD

**Issue by NikhilKeshwala** [nccgroup/ScoutSuite#1471]
Dear Team,

Trying to run ScoutSuite and getting the following error. Installed all of the requirements (pip install -r requirements.txt).

Tried downgrading the version of azure.identity put no luck.

Please see error below.

> user@ubuntu:~/ScoutSuite$ `python3 scout.py azure --cli --debug`
> 2022-10-13 13:59:41 ubuntu scout[76829] INFO Launching Scout
> 2022-10-13 13:59:41 ubuntu scout[76829] INFO Authenticating to cloud provider
> Traceback (most recent call last):
>   File "scout.py", line 8, in <module>
>     sys.exit(run_from_cli())
>   File "/home/pentest/ScoutSuite/ScoutSuite/__main__.py", line 33, in run_from_cli
>     return run(provider=args.get('provider'),
>   File "/home/pentest/ScoutSuite/ScoutSuite/__main__.py", line 130, in run
>     result = loop.run_until_complete(_run(**locals()))  # pass through all the parameters
>   File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
>     return future.result()
>   File "/home/pentest/ScoutSuite/ScoutSuite/__main__.py", line 181, in _run
>     auth_strategy = get_authentication_strategy(provider)
>   File "/home/pentest/ScoutSuite/ScoutSuite/providers/base/authentication_strategy_factory.py", line 22, in get_authentication_strategy
>     authentication_strategy = import_authentication_strategy(provider)
>   File "/home/pentest/ScoutSuite/ScoutSuite/providers/base/authentication_strategy_factory.py", line 12, in import_authentication_strategy
>     module = __import__(f'ScoutSuite.providers.{provider}.authentication_strategy', fromlist=[strategy_class])
>   File "/home/pentest/ScoutSuite/ScoutSuite/providers/azure/authentication_strategy.py", line 8, in <module>
>     from azure.identity import UsernamePasswordCredential, AzureCliCredential, ClientSecretCredential, \
> `ImportError: cannot import name 'AzureCliCredential' from 'azure.identity' (/usr/lib/python3/dist-packages/azure/identity/__init__.py`

**Comment by ai13f** [comment]
How did you resolve this? I am getting the same issue
