### ISSUE TITLE
ERROR __main__.py L211: Initialization failure: No module named 'msgraphcore'

### ISSUE THREAD

**Issue by arp-11** [nccgroup/ScoutSuite#1473]
I installed scoutsuite 5.12 from pip. When running a scan against Azure, it keeps failing at initialization about msgraphcore module. I can't see where that's referenced anywhere in the code. Verified that msgraph-core is installed. 

![image](https://user-images.githubusercontent.com/96440407/197053560-789df029-1c5f-4844-ac7a-21576edde2ac.png)

**Comment by ramooncamacho** [comment]
I've come across this issue as well.

In a fresh installation of ScoutSuite using `pip install scoutsuite`, everything works fine with **msgraph-core** version:

```
# pip list | grep msgraph-core
msgraph-core                   0.2.2
#
```

However, after upgrading  **msgraph-core** with `pip3 install --upgrade msgraph-core`, the error occurs.

Upgraded version:

```
# pip list | grep msgraph-core
msgraph-core                         1.0.0
#
```

Error message:

`ERROR __main__.py L240: Initialization failure: No module named 'msgraph.core'`

To avoid this error, you can containerize your ScoutSuite run.

**Comment by dwalters0** [comment]
I saw this error when running against azure too after doing a pip install in a venv. What worked for me was doing a git clone and running pip install -r requirements.txt in a venv.

**Comment by joeyqleq** [comment]
I had the same issue and its because scoutsuite installed with pip3 requires msggraph-core 0.2.2 and the installed version I had was version 1.1.0. To solve this issue I did:

`pip3 uninstall msggraph-core`
`pip3 install msggraph-core==0.2.2`

**Comment by dwalters0** [comment]
That didn't work for me. It was on a different computer but I did a pip list | grep msgraph.core and it told me 0.2.2 and still wasn't working. Cloning the repo instead of pip installing scoutsuite was the only thing that worked for me.
