### ISSUE TITLE
Minimal AWS IAM policy missing actions

### ISSUE THREAD

**Issue by chrisgilmerproj** [nccgroup/ScoutSuite#1490]
**Describe the bug**

In the wiki page here: https://github.com/nccgroup/ScoutSuite/wiki/AWS-Minimal-Privileges-Policy

The missing actions are:

```
"cloudfront:ListDistributions",
"codebuild:ListProjects",
"secretsmanager:GetResourcePolicy",
```

**To Reproduce**

Please provide:

Set up the policy in AWS per the wiki and run the tool. It should error out with warnings about missing policy actions.

**Comment by rdegraaf** [comment]
Looks like a duplicate of https://github.com/nccgroup/ScoutSuite/issues/1410?

**Comment by chrisgilmerproj** [comment]
@rdegraaf - similar but not quite the same. But they probably should be combined into one fix.

**Comment by chrisgilmerproj** [comment]
@rdegraaf - Apparently I didn't scroll down far enough, you are correct. Mine overlaps. I'll close this.
