### ISSUE TITLE
AWS Minimal Policy - lack of cloudfront:ListDistributions

### ISSUE THREAD

**Issue by Upgreydd** [nccgroup/ScoutSuite#1498]
Like in title

**Comment by zachfey** [comment]
Duplicate of https://github.com/nccgroup/ScoutSuite/issues/1410 - Use the AWS Manged Policy "SecurityAudit"

**Comment by x4v13r64** [comment]
The https://github.com/nccgroup/ScoutSuite/wiki/AWS-Minimal-Privileges-Policy policy has been updated.
