### ISSUE TITLE
Error when running ScoutSuite

### ISSUE THREAD

**Issue by Hafzan-250601** [nccgroup/ScoutSuite#1499]
![image](https://user-images.githubusercontent.com/54774679/220227777-4ceee4bf-249a-4546-b6fb-50c4442dee15.png)
 As you can see i tried running Scoutsuite but this bug has been bothering me for days. Please help me 

python version: 3.11.1

**Comment by mrtnrdl** [comment]
I have the same problem. Same python version. Kali `Linux kali 6.0.0-kali6-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.0.12-1kali1 (2022-12-19) x86_64 GNU/Linux`

**Comment by dpkeesling** [comment]
Same issue here. Same version of kali and same python version. I downgraded to python 3.10 by running:
`sudo apt install python3.10 python3.10-venv` and then started the venv with `virtualenv -p python3.10 venv`
Ran the other commands like normal, and it's working fine for me.

Not an ideal solution, but it works until they add support for python3.11

**Comment by mrtnrdl** [comment]
Thx a ton @dpkeesling - works for me as well.

**Comment by Hafzan-250601** [comment]
Thanks @dpkeesling  works for me!
