### ISSUE TITLE
FTP port open

### ISSUE THREAD

**Issue by andresriancho** [nccgroup/ScoutSuite#15]
```
 Ingress Rules 5

    TCP
        Ports:
            20
                EC2 security groups:
                    app-prd (sg-123456abc)
            21
                EC2 security groups:
                    app-prd (sg-123456abc)
...
```

The FTP port is indeed open, but I believe that this is not a security risk because only instances in `sg-123456abc` can connect to it. The rule should be improved.

**Comment by j4v** [comment]
Closing, I believe this is the case with current rules.
