### ISSUE TITLE
Failed to process rule defined in ec2-instance-in-security-group.json

### ISSUE THREAD

**Issue by wrightmalone** [nccgroup/ScoutSuite#1505]
**Describe the bug**

Please provide:

`ec2-instance-in-security-group.json` is missing a `dashboard_name`, causing exceptions to be written to the results file when running including that rule.

example of exception in result file:

```
{
      "additional_details": null,
      "exception": "Failed to process rule defined in ec2-instance-in-security-group.json: 'Rule' object has no attribute 'dashboard_name'",
      "file": "processingengine.py",
      "line": 56,
      "traceback": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/ScoutSuite/core/processingengine.py\", line 56, in run\n    rule.dashboard_name\nAttributeError: 'Rule' object has no attribute 'dashboard_name'\n"
},
```

**To Reproduce**

Please provide:

This rule is disabled in the default configuration, but when enabled returns this exception

**Additional context**

**Comment by fernando-gallego** [comment]
Hi @wrightmalone , we are unable to reproduce this issue. Could you post the results of a scan using the --debug flag, ScoutSuite version, branch and Python version?

**Comment by fernando-gallego** [comment]
Fixed in https://github.com/nccgroup/ScoutSuite/pull/1506
