### ISSUE TITLE
scout[51757] ERROR cloudformation.py L53: Failed to get CloudFormation stack policy: An error occurred (Throttling) when calling the GetStackPolicy operation (reached max retries: 4): Rate exceeded

### ISSUE THREAD

**Issue by selvasundhr48** [nccgroup/ScoutSuite#1530]
While generating Scout suite Report facing this issue...Even though scoutsuite having Necessary permissions to perform this task...There is Error 

scout[51757] ERROR cloudformation.py L53: Failed to get CloudFormation stack policy: An error occurred (Throttling) when calling the GetStackPolicy operation (reached max retries: 4): Rate exceeded

Task exception was never retrieved
future: <Task finished name='Task-1730' coro=<Stacks.fetch_all() done, defined at /root/venv/lib/python3.9/site-packages/ScoutSuite/providers/aws/resources/cloudformation/stacks.py:13> exception=KeyError('EnableTerminationProtection')>
Traceback (most recent call last):
File "/root/venv/lib/python3.9/site-packages/ScoutSuite/providers/aws/resources/cloudformation/stacks.py", line 16, in fetch_all
name, stack = self._parse_stack(raw_stack)
File "/root/venv/lib/python3.9/site-packages/ScoutSuite/providers/aws/resources/cloudformation/stacks.py", line 24, in _parse_stack
raw_stack['termination_protection'] = raw_stack['EnableTerminationProtection']
KeyError: 'EnableTerminationProtection'

**Comment by selvasundhr48** [comment]
Task exception was never retrieved
future: <Task finished name='Task-1730' coro=<Stacks.fetch_all() done, defined at /root/venv/lib/python3.9/site-packages/ScoutSuite/providers/aws/resources/cloudformation/stacks.py:13> exception=KeyError('EnableTerminationProtection')>
Traceback (most recent call last):
  File "/root/venv/lib/python3.9/site-packages/ScoutSuite/providers/aws/resources/cloudformation/stacks.py", line 16, in fetch_all
    name, stack = self._parse_stack(raw_stack)
  File "/root/venv/lib/python3.9/site-packages/ScoutSuite/providers/aws/resources/cloudformation/stacks.py", line 24, in _parse_stack
    raw_stack['termination_protection'] = raw_stack['EnableTerminationProtection']
KeyError: 'EnableTerminationProtection'

**Comment by selvasundhr48** [comment]
Do we have any Update?

**Comment by fernando-gallego** [comment]
Hi, could you try running this scan with the "--max-workers 5" argument? Or otherwise try some values with the --max-rate flag as described in the Wiki: https://github.com/nccgroup/ScoutSuite/wiki/Handling-Rate-Limiting

**Comment by bck01215** [comment]
Setting `--max-rate` to lower value worked for me.

**Comment by mishradhananjai117** [comment]
Getting similar error with many accounts while running this scout tool.
![image](https://github.com/nccgroup/ScoutSuite/assets/169744976/6aeb2e9d-8d03-4ad1-ae1e-fb0e142e4275)

**Comment by fernando-gallego** [comment]
@mishradhananjai117 this is due to AWS API throttling for client requests. The workaround has already been discussed in this thread.

**Comment by mishradhananjai117** [comment]
> @mishradhananjai117 this is due to AWS API throttling for client requests. The workaround has already been discussed in this thread.

Thank you, but as I am new in this so can you guide me where (which File or setting) I need to change this value.

**Comment by fernando-gallego** [comment]
Please have a look at the Wiki page regarding Rate Limiting: https://github.com/nccgroup/ScoutSuite/wiki/Handling-Rate-Limiting
