### ISSUE TITLE
Can't add exception for Load Balancer Allowing Clear Text (HTTP) Communication 

### ISSUE THREAD

**Issue by bradenwright** [nccgroup/ScoutSuite#1532]
We have 2 LB's showing up with a red item for Load Balancer Allowing Clear Text (HTTP) Communication, there isn't anywhere to click to set an exception.  I was trying to look at the exception file and determine how to manually add it myself but haven't been able to figure it out.

**Comment by bradenwright** [comment]
Any updates on how I can figure out how to add the exception?

**Comment by bradenwright** [comment]
Any updates?

**Comment by bradenwright** [comment]
I was able to ignore it by adding wildcard support quickly, I just editted my virtual env library for `ScoutSuite/core/exceptions.py` and updated line 25 to be `if item not in self.exceptions[service][rule] and "*" not in self.exceptions[service][rule]:`

**Comment by pichouk** [comment]
I had the same issue and I found a solution without directly using the UI. It's definitively not a good solution but might be a workaround if someone have the same issue.

On your scout HTML page for the findings of `Load Balancer Allowing Clear Text (HTTP) Communication` right click on your load balancer name and choose "Inspect element" (will open Developer Console).
![scout_lb](https://github.com/nccgroup/ScoutSuite/assets/8401692/cd2cd1e1-419b-4e67-b7bf-b214b7a62ee2)

Then look on the HTML for the `div` with an `id` looking like `services.elbv2.regions.eu-west-1.vpcs.vpc-999999999999999.lbs.scoutid999999999999999999999999999999999999999.view` (of course you'll have different IDs).
![scout_lb_div](https://github.com/nccgroup/ScoutSuite/assets/8401692/7736f10f-48ae-4cc2-8a04-59dfefc44619)

Then add an exception like this in your `exceptions.json` file :
```json
  "elbv2": {
    "elbv2-listener-allowing-cleartext": [
      "elbv2.regions.eu-west-1.vpcs.vpc-999999999999999.lbs.scoutid-scoutid999999999999999999999999999999999999999.listeners.80.Protocol"
    ]
  }
```
Note that we remove the `services.` prefix and replace `.view` at the end by `.listeners.80.Protocol`.

**Comment by ncc-akis** [comment]
I have fixed this and submitted a PR.
@bradenwright , feel free to checkout the following branch to see if this solves your problem:
https://github.com/ncc-akis/ScoutSuite/tree/bugfix/lb_exceptions

**Comment by booleanbetrayal** [comment]
> I had the same issue and I found a solution without directly using the UI. It's definitively not a good solution but might be a workaround if someone have the same issue.

Thank you @pichouk - This was very helpful! AFAIK, you can determine these string ID / property values by using the `path` and potentially `id_suffix` fields of findings JSON definitions here: https://github.com/nccgroup/ScoutSuite/blob/master/ScoutSuite/providers/aws/rules/findings

It's just a matter of translating the `id` properties values back to proper unique identifier values. 

So for [`iam-assume-role-lacks-external-id-and-mfa`](https://github.com/nccgroup/ScoutSuite/blob/master/ScoutSuite/providers/aws/rules/findings/iam-assume-role-lacks-external-id-and-mfa.json) which also lacks good UX and sets its `path` to `iam.roles.id.assume_role_policy.PolicyDocument.Statement.id` , you could add policy-specific exclusions with an entry to your exclusions file such as: 

```json
{
    "iam": {
        "iam-assume-role-lacks-external-id-and-mfa": [
            "iam.roles.ABC1234567890ABC.assume_role_policy.PolicyDocument.Statement.0",
            "iam.roles.CBA0987654321CBA.assume_role_policy.PolicyDocument.Statement.0"
        ]
    }
}
```
