### ISSUE TITLE
Issue #1511 not fixed

### ISSUE THREAD

**Issue by cyberqueenmeg** [nccgroup/ScoutSuite#1540]
Hi all,

When running ScoutSuite today against flaws.cloud with their given credentials, I get the same error mentioned in Issue 1511 (https://github.com/nccgroup/ScoutSuite/issues/1511), so it appears it is not fixed.

I am running Kali Linux as a VMWare Fusion VM on an M1 mac and running Scoutsuite in the default python3 venv (I copied and pasted the install instructions in the wiki). I tried using the python3.8 venv and that did not fix the issue

Code run:
`scout aws -p flaws`

Result:
`Error __main__.py L211: Initialization failure: global flags not at the start of the expression at position 6`

**Comment by genuisapp** [comment]
I have same issue on m1 macos and scout on aws

**Comment by fernando-gallego** [comment]
Note that the fix is for Python 3.9, 3.10 and 3.11; please try to reproduce it with the **develop** branch and any of the mentioned versions.

**Comment by cyberqueenmeg** [comment]
@fernando-gallego - can confirm the develop branch fixes the issue. I'm closing this issue and opening a new one proposing a merge
