### ISSUE TITLE
Various UI/UX bugs and enhancements Part 2

### ISSUE THREAD

**Issue by vifor2** [nccgroup/ScoutSuite#158]
- [x] Where policies are shown, ideally we would use `<code></code>`:
![image](https://user-images.githubusercontent.com/17322874/52437891-ffdc0f00-2ae5-11e9-8a49-a6a325cde204.png)

- [x] The spacing at the bottom isn't ideal. Now that we have BS4 it should be easier to implement:
![image](https://user-images.githubusercontent.com/17322874/52437917-108c8500-2ae6-11e9-8324-00480a433d08.png)

- [x] This is also the case for the top spacing (probably because of hidden account number):
![image](https://user-images.githubusercontent.com/17322874/52437931-1aae8380-2ae6-11e9-8d63-54b0549b0c86.png)

- [x] In this issue (and a few others), `No` is used - the convention should be `True/False`:
![image](https://user-images.githubusercontent.com/17322874/52437950-239f5500-2ae6-11e9-858b-f28f7dc426cc.png)

- [x] For long finding titles, the CSV/JSON buttons are superposed:
![image](https://user-images.githubusercontent.com/17322874/52437970-2f8b1700-2ae6-11e9-9ed8-acbab5ce1ee7.png)

Under the light theme, it's clear that resources with no instances (`Groups`) are disabled:
![image](https://user-images.githubusercontent.com/17322874/52438284-ebe4dd00-2ae6-11e9-9006-615c529aebd8.png)

- [x] Under the dark theme the highlight seems reversed:
![image](https://user-images.githubusercontent.com/17322874/52438296-f30beb00-2ae6-11e9-8dca-7ca6dfad2694.png)

**Comment by j4v** [comment]
It seems this has broken the "Display account ID on all pages" functionality, are you aware of this? I don't care much, just want to make sure this was intended.

I'm also seeing that that the bottom spacer seems off for GCP, but looks right for AWS. Any idea if there's something provider-specific going on?

This looks fine (AWS):

![sc_2019-02-11_12h49m45s](https://user-images.githubusercontent.com/4206926/52561525-ef84a680-2dfb-11e9-95ff-8f64da73a7be.jpg)

This looks off (GCP):

![sc_2019-02-11_12h50m00s](https://user-images.githubusercontent.com/4206926/52561521-ee537980-2dfb-11e9-8cd9-1c2da8b85623.jpg)

**Comment by vifor2** [comment]
> It seems this has broken the "Display account ID on all pages" functionality, are you aware of this? I don't care much, just want to make sure this was intended.

Sigh. no it was not intended, will look into it.

> I'm also seeing that that the bottom spacer seems off for GCP, but looks right for AWS. Any idea if there's something provider-specific going on?

I'll set up my env to run reports other than AWS and see why that happens.
 
> I'm not too crazy about the new code highlight, especially in the light theme. It breaks the theme's consistency:

> Can we revert back to the theme's default `<code></code>` CSS?

Alright, wasn't sure if you didn't want the default pink.

> Also for the `Inline role policy allows [x]` the "Role Trust Policy Details" isn't highlighted as code. That's the only occurrence I could find 👍.

Oky

**Comment by j4v** [comment]
> Sigh. no it was not intended, will look into it.

Like I said it really wan't a very useful feature. Might be easier to just remove the functionality altogether!
