### ISSUE TITLE
Feature request: check if default encryption for EBS Volumes is enabled.

### ISSUE THREAD

**Issue by rdegraaf** [nccgroup/ScoutSuite#1584]
**Is your feature request related to a problem? Please describe.**

By default, EBS Volumes are not encrypted.  However, there is an account-level (region-level?) setting to enable encryption of all new EBS Volumes using a specific KMS key.

**Describe the solution you'd like**

ScoutSuite should check if this setting is enabled.

**Comment by fernando-gallego** [comment]
Merged into develop.
