### ISSUE TITLE
Route53 audit only covers one "page"

### ISSUE THREAD

**Issue by znb** [nccgroup/ScoutSuite#163]
We have quite a few hosted domains in Route53. I noticed today that the Route53 audit only contains results from the first "page" (20 results) of results.

I suspect this may be a pagination issue when pulling the results.

[Error](https://imgur.com/a/Tan5Gqs)

**Comment by j4v** [comment]
Thanks, will look into it.

**Comment by misg** [comment]
#267 should fix any issue related to result pagination and will be available in the next release, in one week if everything goes well.

**Comment by Aboisier** [comment]
Can we close this, @misg ?

**Comment by j4v** [comment]
Closing as this is believed to be resolved. Will reopen if @znb or someone else experiences this issue again.
