### ISSUE TITLE
GCP CE/CloudSQL can't run with multiple threads

### ISSUE THREAD

**Issue by Aboisier** [nccgroup/ScoutSuite#166]
In computeengine.py and cloudsql.py (will soon be merged with PR #164 ) need to hardcode the thread config to 1, otherwise, we get SSL errors.

Repro steps:
 - Have more than one resource (eg. 2 vms, or 2 cloud SQL instances)
 - Start a scan
 - You should see errors in the console, or sometimes it hangs indefinitely

Here's different errors I got:
- `[SSL: BLOCK_CIPHER_PAD_IS_WRONG] block cipher pad is wrong (_ssl.c:2217)Failed to fetch backups for SQL instance xxxxxxxx: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:2217)`
- `python SSL: WRONG_VERSION_NUMBER`

**Comment by j4v** [comment]
Yep, this is an odd one. Will either require diving into the API's implementation or maybe wait until Google does a decent job with their own libraries...

**Comment by j4v** [comment]
Would be worth documenting this in the wiki.

**Comment by j4v** [comment]
This seems to be the explanation: https://stackoverflow.com/a/37236585

Looking at the following it isn't clear if CE/CloudSQL should now be thread safe:
https://github.com/googleapis/google-cloud-python/issues/1214
https://github.com/googleapis/google-cloud-python/pull/3674

**Comment by Remi05** [comment]
This is fixed in dev since the refactoring was merged!
