### ISSUE TITLE
Regions empty in CloudTrail

### ISSUE THREAD

**Issue by fkpp** [nccgroup/ScoutSuite#17]
Hi,

we are using the latest master version from GIT. ( checked out yesterday).
However, we are not able to see the regions in CloudTrail.
Neither in the top navigation (Management->CloudTrail) where the count is just empty "Regions ()"
nor on the CloudTrail page itself in the left side menu.

![image](https://user-images.githubusercontent.com/15727648/35333598-97646f0e-010f-11e8-8eca-db8830339ab8.png)

It looks like something does not get properly propagated.
I checked the metadata object in the aws_config JS file and determined, that the count attribute in metadata.management.cloudtrail.resources.regions seems to be missing.
 (it does exist for the trails resource).

Additionally, when inspecting the elements in the left side navigation, it kind of propagates the list entries, but as the regions are missing, it won't display in the browser.
services.cloudtrail.regions..link is found within all those list elements, as you can see the region part is missing.

![image](https://user-images.githubusercontent.com/15727648/35333531-5a86db6c-010f-11e8-8bd2-f019d6f8154a.png)

Thanks for your support!

Florian

**Comment by Aboisier** [comment]
Fixed in #123 .
