### ISSUE TITLE
minimum policy requriements

### ISSUE THREAD

**Issue by kbroughton** [nccgroup/ScoutSuite#171]
The README should specify what is the least privileged policy required to run ScoutSuite for each provider.  Scout2 had a minimum policy for AWS.

**Comment by j4v** [comment]
This is already done. As per https://github.com/nccgroup/ScoutSuite/blob/master/README.md:

# AWS

```
The following AWS Managed Policies can be attached to the principal used to run Scout in order to grant the necessary permissions:

ReadOnlyAccess
SecurityAudit
```

# GCP

```
The following roles can be attached to the member used to run Scout in order to grant necessary permissions:

Viewer
Security Reviewer
Stackdriver Account Viewer
```

# Azure

```
Scout will require the Reader role over all the resources you want to check. The easiest way is to give it Reader over the Subscription, as it will be inherited on all the resources.
```

If what you mean is a sample policy with the exact minimum privileges required that's not something we're going to do, as it's very hard to manage (and why we stopped for Scout2). In any event best practice is to leverage managed policies/roles.

**Comment by emtunc** [comment]
`ReadOnlyAccess` is excessive for what ScoutSuite actually needs to run. Can we please define a finer grained IAM policy for the tool? `ReadOnlyAccess` allows the role to actually download data from S3 buckets, Kinesis streams, SQS queues, etc. ScoutSuite doesn't need any of those to work.

**Comment by j4v** [comment]
The main reason why we recommend the `ReadOnlyAccess` Managed Policy is because it's much easier to setup and maintain. AFAIK there is no managed policy that covers all necessary permissions.

> ReadOnlyAccess allows the role to actually download data from S3 buckets, Kinesis streams, SQS queues, etc

That is correct, but other policies like `ViewOnly` don't grant access to metadata that Scout does analyze. If you want to lock these services down then I'd recommend assigning an additional policy with `Deny` statements to the user/role running Scout.

Also encrypting sensitive objects with KMS is always recommended and a good safeguard against loose IAM permissions :smile: .

**Comment by kbroughton** [comment]
As a pentester, I agree that keeping things simple is best for most
customers.  However, there are other customers who are not willing to grant
such wide-ranging access.
Would you accept a PR that defines a minimal policy required to run Scout
so that users can decide whether to request a managed policy
(ReadOnlyAccess) vs a finer-grained custom policy?

**Comment by j4v** [comment]
My main concern isn't so much with drafting such a policy (as we had in Scout2) so much as maintaining it when adding new services. I'm open to restoring it if you feel strongly this would be beneficial.

Maybe the wiki would be a good place for it?

**Comment by kbroughton** [comment]
Thanks. Wiki would work fine for me.

**Comment by emtunc** [comment]
Thanks for chiming in @j4v and @kbroughton.

I'll also check out the policy above and see if we run in to any issues.

We've managed to get it to work so far with the `SecurityAudit` and `AmazonSNSReadOnly` which is far better than the `ReadOnlyAccess`.

**Comment by j4v** [comment]
Closing this as a policy has been posted to https://github.com/nccgroup/ScoutSuite/wiki/AWS-Minimal-Privileges-Policy. Please open an issue/PR if you have further issues.
