### ISSUE TITLE
Remove Opinel Dependency

### ISSUE THREAD

**Issue by zer0x64** [nccgroup/ScoutSuite#181]
Extract conditions.py from the Opinel library.
After this, it will be possible to add conditions to the rule engine.

**Comment by j4v** [comment]
Should be pretty easy, they are all in https://github.com/nccgroup/opinel/blob/master/opinel/utils/conditions.py.

If you want to merge in Opinel progressively, you could just put all the code in an `opinel` folder in Scout, remove the requirement for the actual library, and voila. From there you can start slowly refactoring from within Scout.
