### ISSUE TITLE
Exceptions have no effect due to error in RuleExceptions class

### ISSUE THREAD

**Issue by crohacz** [nccgroup/ScoutSuite#207]
**What version of Scoutsuite:**
4.2.0 release 
 
**What version of Python are you using?** 
Tested on python versions 2.7 and 3.7

**What operating system and processor architecture are you using?**
* MacOS Mojave 10.14.1
* Also exhibited on Amazon Linux 2 EC2 instances

**What did you do and what did you expect to see?**
Exceptions were added from UI, exported into file, and included in the next run of Scoutsuite with the following command: 
```
python Scout.py aws --profile <profile_name> --thread-config 1 --exceptions ../path-to-exceptions.json
```

The exceptions file is simple for now, it looks like the following: 
```
exceptions =
{
    "iam": {
        "iam-managed-policy-allows-iam-PassRole": [
            "iam.policies.GUID.PolicyDocument.Statement.1"
        ]
    }
}
```

**What did you expect to see?**
I expected to see the iam-managed-policy-allows-iam-PassRole* finding ignored. We only have 1 occurence of this finding at the moment. Yet still, this finding is shown as a violation of the rulset.

**What did you see instead?**
The finding including in the exceptions is still shown as a violation. Using the `--debug` flag, I then see this error message: 

```Warning, failed to load exceptions. The file may not exist or may have an invalid format.```

Because that error message is printed for any exception when trying to load exceptions into Scoutsuite, I used the python debugger to investigate the specific exception that was the trigger. The actual error message originates from the RuleException class upon initialization of the JavaScriptReaderWriter class which uses the profile (given by `args.get('profile')`) and attempts to parse it like so on line 47 of the `Scoutsuite/output/js.py` file: 

```
self.profile = profile.replace('/', '_').replace('\\', '_')  # Issue 111
```

In this case, the `profile` variable passed into RuleExceptions class and JavaScriptReaderWriter class is a list and therefore, replace() is not a valid function of a list. When that line attempts to execute, we see the exception:

```
'list' object has no attribute 'replace'
```

I can fix this issue simply by changing the argument passed into the RuleExceptions. 

Instead of: (line 122 off __main__.py)
```
exceptions = RuleExceptions(args.get('profile'), args.get('exceptions')[0])
```

It should be: 
```
exceptions = RuleExceptions(args.get('profile')[0], args.get('exceptions')[0])
```
or 
```
exceptions = RuleExceptions(AWSProfiles.get(args.get('profile'))[0], args.get('exceptions')[0])
```

I  have tried both of these changes locally with success.

This is the commit hash that introduced the change: c326be0e96d63fed7676a78b059cdb19d131a209 and was released with version 4.2.0

If this is not already on your radar, I'm happy to submit a PR with the proposed change. Also possible another PR to support better error handling exceptions.

**Comment by j4v** [comment]
Thanks @crohacz, 10/10 on the issue description - will fix this today.

**Comment by j4v** [comment]
> Also possible another PR to support better error handling exceptions.

That would be :fire:

**Comment by j4v** [comment]
This should now be solved in the `develop` branch (which should be merged to `master` within a few weeks).
