### ISSUE TITLE
Feature Request - Add EC2/ELB name + DNS to the IP address in the external attack surface overview.

### ISSUE THREAD

**Issue by lgap** [nccgroup/ScoutSuite#22]
At the moment the external attack surface overview shows the external IP's and the exposed protocol/ports. However, we now need to map this external IP back to an EC2/ELB interface associated with it. Can more information be shown about the user/assigned system/DNS related with the IP? Maybe also add a click-through to the associated instance/rules?

**Comment by j4v** [comment]
Moving this up as it's indeed a pain to identify IPs/instances/ENIs across attack surface, instances, ENIs and SGs.

**Comment by j4v** [comment]
Closing, this is fixed in `develop`.
