### ISSUE TITLE
No github release for new 4.3.0 pypi release

### ISSUE THREAD

**Issue by gebailey** [nccgroup/ScoutSuite#233]
PyPI is serving up the 4.3.0 release, but there's no corresponding github release, and thus no release notes to read.

Looks like the .JS filenames changed that contain exceptions and results, which broke some scripting.

**Comment by j4v** [comment]
@gebailey we'll make the GH release shortly, thanks for the heads up.

Nothing has changed from 4.2.0 to 4.3.0 regarding the JS file names, could you confirm you updated from 4.2.0 and provide reproduction steps?

**Comment by gebailey** [comment]
Running ScoutSuite 4.2.post5:
```
pip install ScoutSuite==4.2.post5
Scout aws --no-browser
```
gives:
```
Saving data to scoutsuite-report/scoutsuite-results/scoutsuite_results-aws-default.js
Saving config...
Saving data to scoutsuite-report/scoutsuite-results/scoutsuite_exceptions-aws-default.js
Saving config...
Creating scoutsuite-report/report-aws-default.html ...
```

But, running ScoutSuite 4.3.0 gives:
```
pip install ScoutSuite
Scout aws --no-browser
```
gives:
```
Fetching CloudFormation config...
             regions             stacks
string indices must be integers      <==== not sure what this error message is from??
               16/16                0/1
[--snip--]
Saving data to scoutsuite-report/scoutsuite-results/scoutsuite_results-aws.js
Saving config...
Saving data to scoutsuite-report/scoutsuite-results/scoutsuite_exceptions-aws.js
Saving config...
Creating scoutsuite-report/report-aws.html ...
```

So the names of the results files are different:  `scoutsuite_results-aws-default.js` vs. `scoutsuite_results-aws.js`.  It's helpful to know if things like this change so that I can adjust postprocessing steps.

**Comment by Aboisier** [comment]
The report name for AWS is generated by concatenating `'aws'` with the profile name if there is one.  This algorithm did not change. The default profile name was changed from `'default'` to `None` though, hence the change in the *.js* and *.html* file names. 

We will add this to the release note, thank you for bringing this to our attention. I will close this for now, we can reopen if you need further information.

**Comment by j4v** [comment]
> The report name for AWS is generated by concatenating `'aws'` with the profile name if there is one.

Yeah apologies, there was a slight change here when removing the Opinel dependency. We indeed removed the "default" `default` for AWS.

**Comment by gebailey** [comment]
Thanks for the update!
