### ISSUE TITLE
Fix broken collapsibles

### ISSUE THREAD

**Issue by vifor2** [nccgroup/ScoutSuite#247]
There are quite a few collapsibles, at least on the AWS side that could be fixed or improved, here's a list of things to fix. Bare in mind that since I am working of a very fresh AWS account there aren't many ressources on it and therefore I am not testing all pages at the moment.

- [x] EC2 instances : the section *Network interfaces* is opened by default and pressing on the *Details* button causes it to close and then open almost instantly, afterwards it works as intended.
- [x] ELBv2 load balancers : the *Security groups* section has a button with the count of number of security groups in it, but clicking it launches an error in the console rather than making the section appear : `DOMException: Failed to execute 'querySelector' on 'Document': '#services.elbv2.regions.us-east-2.vpcs.vpc-d4f3****.lbs.5ca81197d3d5***********************************.security_groups' is not a valid selector.`
- [x] VPC vpcs : pressing on the number in the section *Network ACLs* does not make something appear, but does not throw an error either, is this intended? If so the button shouldn't suggest it is clickable (e.g. not change the cursor to a hand), else it should make the appropriate information appear.
- [x] S3 buckets : same issue as previous one for the sections *Groups with access via IAM policies* and *Roles with access via IAM policies*.

**Comment by j4v** [comment]
While they appear to be buttons/collapsibles they aren't / shouldn't be, no? Those are just counters.

Also seeing that `Details` collapsible for AWS IAM Roles acts oddly in Chrome, sometimes you need to refresh for it to open/close.

**Comment by Aboisier** [comment]
Can we close this? Seems like it was imlemented in #277?
