### ISSUE TITLE
Add direct link to S3 Bucket when flagged as world-listable

### ISSUE THREAD

**Issue by hardsec** [nccgroup/ScoutSuite#25]
One of the issues flagged by ScoutSuite is "Bucket world-listable (anonymous)". The way to verify the issue is to access the S3 bucket through the web browser, so it would be helpful to have a direct link to the bucket in the issue report.

**Comment by j4v** [comment]
Add the following to the UI:
```
http(s)://<bucket>.s3.amazonaws.com/
http(s)://s3.amazonaws.com/<bucket>/
```

**Comment by j4v** [comment]
Closing as this is a duplicate of https://github.com/nccgroup/ScoutSuite/issues/16.
