### ISSUE TITLE
Can't create exception for world listable buckets

### ISSUE THREAD

**Issue by hb3b** [nccgroup/ScoutSuite#26]
Hi,

I am unable to set a bucket exception for the _Bucket world-listable (anonymous)_ rule.

Creating the exception in the UI generates

```
exceptions = 
{
    "s3": {
        "s3-bucket-AllUsers-read": [
            ""
        ]
    }
}
````

I've tried entering:

1. services.s3.buckets.GUID
2. s3.buckets.GUID
3. buckets.GUID
4. GUID

Same output when using a custom ruleset to bump this rule to Danger. Using Scout2 from the master branch.

**Comment by j4v** [comment]
Closing as this was fixed in `develop`. Apologies for the delay @hb3b.
