### ISSUE TITLE
Human Readable CSV Findings Export

### ISSUE THREAD

**Issue by saryx123** [nccgroup/ScoutSuite#27]
Hi,

Although various export are available and the html/js report offers an impressive user experience, a lack of easy to use, human readable csv export of scout2 findings is perhaps the one thing that keeps it from being, hands down, the best aws audit tool.

I may be missing something, even though i've spent many hours on the issue throwing myself at the [ export wiki entry ](https://github.com/nccgroup/Scout2/wiki/HowTo:-Exporting-and-Programmatically-Access-of-Scout2-Data). 
Or perhaps it was never the intention to make scout2 easy to use for mere mortals.

Regardless, i'd love to walk out of this experience a bit wiser.
Enlighten me, would you kindly :) 
-A.G.

**Comment by j4v** [comment]
Closing this as CSV exporting is implemented.

**Comment by oracle85** [comment]
Hi wonder if anyone can help me please. I am trying to export Scout2 to csv, but i dont know how to do it.which command need to use etc. Thanks

**Comment by oracle85** [comment]
> @l01cd3v my take on this is that it is rather clear, scout2 is designed to help identify security faults with aws enviornments. To do that, a scout2 should provide (along the comprehensive platform) a report that is
> 
> * clear(simple, informatively and instinctively titled & structured),
> * human readable (English, simple csv or paragraph format)
> * concise (provide only the must-have info to begin remediation)
> * actionable (simple users must be able to read it, forward it via email, etc) - .csv or .pdf format
> 
> As for the output format, rows and cells, **attached is a draft format for your convenience**. MetaSploit, AWS Trusted advisor and others provide similar exports. But they're all lacking in other/similar areas, thats why i'm here.
> [Cloud Audit Desired Format.zip](https://github.com/nccgroup/Scout2/files/1611907/Cloud.Audit.Desired.Format.zip)
> 
> If I had a scout2 export in such a format a few months ago when I was working for a bank, I wouldnt have sent it over to ops for remediation and my CISO(informative cc) that very moment;
> ![image](https://user-images.githubusercontent.com/17128601/34676210-c5ac433c-f494-11e7-9dd6-db2984eeed78.png)
> 
> Tell me how I can help, if you believe that this aligns with Scout2 purpose and vision.
> 
> -sary.

Hi wonder if anyone can help me please. I am trying to export Scout2 to csv, but i dont know how to do it.which command need to use etc. Thanks

**Comment by j4v** [comment]
Scout2 or ScoutSuite?

**Comment by oracle85** [comment]
> Scout2 or ScoutSuite?

Scout2 please. Thanks

**Comment by j4v** [comment]
Scout2 is no longer maintained and doesn't support this feature. Please switch to Scout Suite.

**Comment by oracle85** [comment]
> Scout2 is no longer maintained and doesn't support this feature. Please switch to Scout Suite.

Thanks , would it be possible if you can help me how to export the data please? Thanks

**Comment by oracle85** [comment]
> Scout2 is no longer maintained and doesn't support this feature. Please switch to Scout Suite.

Thanks , would it be possible if you can help me how to export the data please? which command Thanks

**Comment by ramimac** [comment]
@oracle85 Scout2 is not maintained or supported (and hasn't been for a while). 

If you'd like a CSV export, we recommend using ScoutSuite. In that case, the "Export Summary" button in the report will generate the CSV for you.

**Comment by oracle85** [comment]
> @oracle85 Scout2 is not maintained or supported (and hasn't been for a while).
> 
> If you'd like a CSV export, we recommend using ScoutSuite. In that case, the "Export Summary" button in the report will generate the CSV for you.

Hi thanks I am using ScoutSuite, i have the report in HTML but I can not find the Export Summary button? Can you help me please. Thanks

**Comment by ramimac** [comment]
@oracle85 my apologies - it looks like that feature is slated for the upcoming 5.9.0 release. You'll need to switch to the `develop` branch if you'd like early access. (tip: you can use the `-l` flag to run locally, may save you re-hitting the APIs?)
