### ISSUE TITLE
Unable to execute Scout on a RHEL 7 EC2 Instance

### ISSUE THREAD

**Issue by julian-berks** [nccgroup/ScoutSuite#282]
I'm looking to move from Scout2 to ScoutSuite - on a RHEL 7 EC2 Instance. I've tested aws cli and it's working fine.
 I've tried installing through pip and even manually via git.
Whatever I do, running either virtualenv as documented, or via the /usr/bin/Scout program, all it does is wait a couple of seconds and return to the prompt. I've tried debug which also does nothing. There is no output and no errors. It' using Python2.7 currently - which the docs say is still supported.

(venv) [root@ip-10-1-10-50 ScoutSuite]#  python Scout.py aws --no-browser --report-dir /tmp --debug
(venv) [root@ip-10-1-10-50 ScoutSuite]# ls /tmp
systemd-private-002e6373ddc14b9fa94a7794e5b8d0ed-chronyd.service-audi6S
(venv) [root@ip-10-1-10-50 ScoutSuite]#

**Comment by j4v** [comment]
I'll try to reproduce but that's quite odd, "something" should always happen. Does running Scout2 in the same environment work?

**Comment by julian-berks** [comment]
Hi,
Yes, Scout2 is producing the report as normal.

**Comment by gebailey** [comment]
Just out of curiosity, what are the specs of the EC2 instance you're running it on?

I just ran ScoutSuite 4.3.0 on a RHEL7 t3.small EC2 instance, and it ran OK.

However, I periodically ran the `ps_mem` utility (installable via the `ps_mem` RPM), and see fairly high memory usage while ScoutSuite is collecting data (below was the largest value for memory usage that I saw):

```
[root@ip-172-31-47-42 ~]# ps_mem 
 Private  +   Shared  =  RAM used	Program 

104.0 KiB +  15.5 KiB = 119.5 KiB	rhnsd
264.0 KiB + 108.0 KiB = 372.0 KiB	agetty (2)
332.0 KiB +  42.5 KiB = 374.5 KiB	anacron
300.0 KiB +  88.0 KiB = 388.0 KiB	irqbalance
532.0 KiB +  68.5 KiB = 600.5 KiB	auditd
680.0 KiB +  64.0 KiB = 744.0 KiB	crond
708.0 KiB + 108.5 KiB = 816.5 KiB	chronyd
  1.0 MiB +  62.5 KiB =   1.0 MiB	systemd-logind
888.0 KiB + 268.5 KiB =   1.1 MiB	dbus-daemon
  1.1 MiB + 117.5 KiB =   1.2 MiB	master
  1.2 MiB + 417.5 KiB =   1.6 MiB	pickup
  1.0 MiB + 584.5 KiB =   1.6 MiB	systemd-journald
  1.2 MiB + 417.5 KiB =   1.6 MiB	qmgr
  1.2 MiB + 457.0 KiB =   1.7 MiB	su (2)
  1.6 MiB + 957.0 KiB =   2.5 MiB	bash (4)
  2.3 MiB + 854.0 KiB =   3.1 MiB	systemd-udevd
  2.9 MiB + 275.5 KiB =   3.2 MiB	dhclient
  2.3 MiB +   1.1 MiB =   3.4 MiB	sudo (2)
  3.8 MiB + 895.5 KiB =   4.6 MiB	systemd
  2.1 MiB +   3.3 MiB =   5.4 MiB	httpd (7)
  5.8 MiB + 632.0 KiB =   6.4 MiB	rsyslogd
  1.9 MiB +   4.6 MiB =   6.5 MiB	sshd (5)
  6.1 MiB +   1.1 MiB =   7.1 MiB	NetworkManager
  7.7 MiB + 968.5 KiB =   8.6 MiB	polkitd
 11.6 MiB +   1.4 MiB =  13.0 MiB	tuned
796.9 MiB +   1.3 MiB = 798.2 MiB	Scout
---------------------------------
                        875.3 MiB
=================================
```

If you're trying to run it on a nano or micro instance, and you have a lot of AWS resources, maybe it's running out of memory?

**Comment by j4v** [comment]
Yep, please refer to https://github.com/nccgroup/ScoutSuite#computing-resources. From experience depending on the size of the account you might need up to a few GB (for very large accounts).

**Comment by j4v** [comment]
@julian-berks can you advise?

**Comment by j4v** [comment]
Closing due to lack of feedback. This is most likely a FP.
