### ISSUE TITLE
Fetch all logging

### ISSUE THREAD

**Issue by Aboisier** [nccgroup/ScoutSuite#283]
The current logging that appears while fetching all the resources will disappear in #183 . It will be replaced by some very simple logging. It might be interesting to re-implement a more complete logging system.

**Comment by j4v** [comment]
@Aboisier I might be missing something, how does this differ from https://github.com/nccgroup/ScoutSuite/pull/281?

**Comment by Aboisier** [comment]
I was indeed referring to the counts. If it's not something we want, we can just close this. 👍

**Comment by j4v** [comment]
We can close for now, it's not something we'll be revisiting any time soon I think.
