### ISSUE TITLE
AWS EMR service fails to parse some clusters

### ISSUE THREAD

**Issue by misg** [nccgroup/ScoutSuite#299]
Running Scout Suite against AWS EMR service (`python Scout.py --provider aws --profile default --services emr --ruleset default --force`) shows some parsing failures regarding VPCs/clusters:

```console
Unable to determine VPC id for sg-0bc2fd786b0f56365
Failed to parse clusters in TODO in us-east-2
Failed to parse clusters in TODO in us-east-2

**Comment by j4v** [comment]
I think this is due to partial refactoring? See https://github.com/nccgroup/ScoutSuite/blob/develop/ScoutSuite/providers/aws/provider.py#L58.

**Comment by j4v** [comment]
Fixed in `develop`
