### ISSUE TITLE
Improve the code coverage

### ISSUE THREAD

**Issue by Aboisier** [nccgroup/ScoutSuite#308]
As of writing this issue, the code coverage is fairly low (34%). It would be interesting to improve it by unit testing the logic-heavy parts of the code. Testing the `provider.py` files is probably a good place to start. Testing the facades and the resources is probably not really relevant and should be covered by integration tests.

**Comment by j4v** [comment]
@JJmako assigning this to you. We'll close once you've merged all the opinel tests.

**Comment by j4v** [comment]
> We'll close once you've merged all the opinel tests.

Closing
