### ISSUE TITLE
FN for "No Export Sinks" finding with organizations

### ISSUE THREAD

**Issue by j4v** [nccgroup/ScoutSuite#31]
The `No Export Sinks` finding simply checks that there is a sink configured. When running Scout for an Organization or against multiple projects (i.e. with a Service Account that has access to multiple Projects), if there is 1 sink in the whole Organization/Project list, then the finding will not be flagged.

The finding should check that there is no Project that doesn't export logs to a sink.

**Comment by j4v** [comment]
In order to do this, https://github.com/nccgroup/ScoutSuite/issues/80 will have to be implemented. Currently all the resources are "flat" so it's not possible to write per-project rules.

**Comment by j4v** [comment]
Another issue here is that it's currently not possible to get the `project` attribute for a sink (for example in `parse_sinks` from `stackdriverlogging.py`). 

The reason for this is that in `/ScoutSuite/providers/gcp/configs/base.py` at L178, when the `_client` attribute is set to `None`, this messes with the object's properties and sets them to `NoneType`. 
The Sink properties currently don't have setters (see https://github.com/googleapis/google-cloud-python/blob/master/logging/google/cloud/logging/sink.py) so not sure how to solve this.

**Comment by Remi05** [comment]
This should be fixed with the new architecture. I do not currently have organisation-level to test it and confirm though. @j4v could you check if it is indeed fixed on develop when you have time please?

**Comment by j4v** [comment]
@Remi05 I'll test it out tomorrow but I do believe you have org-level access.

**Comment by j4v** [comment]
Implemented in `develop`.
