### ISSUE TITLE
get_value_at function at ScoutSuite/providers/base/configs/browser.py not handling lists correctly

### ISSUE THREAD

**Issue by benghaun** [nccgroup/ScoutSuite#317]
The get_value_at function which is used in the processing of signatures that use the `_GET_VALUE_AT_` functionality (an example would be the signature located at ScoutSuite/providers/aws/rules/findings/vpc-subnet-with-default-acls.json) does not handle list indices properly. When a list index is part of the key, it is not interpreted as an integer in some cases and will attempt to access element `"0"` of the list, which results in an `KeyError` since `"0"` is a string and not an int. 

One example where this problem arises is when the following key is provided:
`ec2.regions.id.vpcs.id.security_groups.id.used_by.ec2.resource_type.network_interfaces.id`
In this case, the `network_interfaces` object is a list, and the `id` after it is an integer. However, the function treats the `id` as a string, which results in a `KeyError`.

**Comment by benghaun** [comment]
The issue can be fixed by adding this extra condition when iterating through `target_path`:
```
if type(p) == list and p.isdigit():
    target_obj = target_obj[int(p)]
```

**Comment by j4v** [comment]
Thanks for this @benghaun, we'll review ASAP.

Did you notice this issue arising through an already-implemented rule/service, or where you adding functionality?

**Comment by benghaun** [comment]
I noticed this when trying to add a new rule, which uses `_GET_VALUE_AT(this)` where `this` refers to `ec2.regions.id.vpcs.id.security_groups.id.used_by.ec2.resource_type.network_interfaces.id`.

**Comment by j4v** [comment]
Merged into `develop`, thanks @benghaun !
