### ISSUE TITLE
CloudTrail - "Global services logging disabled"

### ISSUE THREAD

**Issue by samallisonds** [nccgroup/ScoutSuite#33]
We've started seeing the error "Global services logging disabled" in the CloudTrail section. When we click through on the report, the page is blank.

However I think this finding is a mistake, we do have "Management events" set to "Read/Write events
All". Which I think is the relevant setting. We have recently moved over to the Organizations integration with CloudTrail though - perhaps this is causing confusion?

**Comment by j4v** [comment]
A couple of points:
- There was indeed a bug in Scout when checking Global Services logging for trails in Organizations. This has been resolved in https://github.com/nccgroup/ScoutSuite/commit/2eef793ee779a1c964114d257d208cd504b79992, thanks!
- It should be noted that Global Service Events, Data Events and Management Events are three different things. Currently Scout only validates Global Service Events, Data/Management Events should be supported soon.
