### ISSUE TITLE
aws/ip-ranges/aws.json out of date?

### ISSUE THREAD

**Issue by rtomlinson-latacora** [nccgroup/ScoutSuite#336]
I was just wondering if you were checking for updates to the aws ips. I noticed the one in ScoutSuite is "createDate": "2017-10-17-15-42-12" and the one available at https://ip-ranges.amazonaws.com/ip-ranges.json is "createDate": "2019-04-08-20-59-04". Thanks.

Example: ScoutSuite/ScoutSuite/providers/aws/rules/findings/ec2-security-group-whitelists-aws.json

**Comment by rtomlinson-latacora** [comment]
I just compared the one saved in scoutsuite against the up-to-date published json by aws. There are 6 ips cidrs that are no longer in the newest published list and 346 of them that are missing from the old version in scoutsuite.

**Comment by j4v** [comment]
Thanks, should be resolved in `develop` shortly (https://github.com/nccgroup/ScoutSuite/pull/338).
