### ISSUE TITLE
GCP run fails with "no attribute aws_account_id"

### ISSUE THREAD

**Issue by ravenium** [nccgroup/ScoutSuite#34]
I'm trying a test run using a service account, using the command outlined in the readme:

python Scout.py --provider gcp --service-account --key-file /path/to/my/key/file

I get a number of errors thrown: 

Fetching Cloud Resource Manager config...
            projects
string indices must be integers
string indices must be integers
string indices must be integers
                 0/0
Fetching Cloud Storage config...
             buckets
string indices must be integers
string indices must be integers

and finally:

AttributeError: 'GCPProvider' object has no attribute 'aws_account_id'

I've tried both the pipenv install as well as cloning it from here, on osx.  I work with a few different AWS accounts, but none are actively in env when I run this.  GCP sdk is local to the folder, have tried brew cask as well.  Now to be fair there are only like 3 accounts in the project and no systems/buckets/etc.  What is going on here?

**Comment by j4v** [comment]
Thanks for this, it appears that when using a service account Scout doesn't detect the project to which the service account belongs to by default.

For now just indicate the account with the `--project-id` flag, will fix ASAP.

**Comment by j4v** [comment]
This should now be resolved.
