### ISSUE TITLE
IAM Inline Policies FPs

### ISSUE THREAD

**Issue by j4v** [nccgroup/ScoutSuite#340]
Getting a bunch of FPs for the following:
- Group with inline policies
- Role with inline policies
- User with inline policies

**Comment by Aboisier** [comment]
Is this new, or did this bug exist before (e.g. in 4.3.0?) The IAM refactoring was a bit of a hassle, it might have been introduced there.

**Comment by j4v** [comment]
Pretty sure it's new.

**Comment by Aboisier** [comment]
😥

**Comment by j4v** [comment]
Resolved in `develop`.
