### ISSUE TITLE
AWS VPC bugs

### ISSUE THREAD

**Issue by Aboisier** [nccgroup/ScoutSuite#345]
It seems like there is a path problem or something like that with some resources. For example, 
* The network ACLs do not appear in the sub menu, but they did when tested with 4.2.0.
* Some other resources are missing
* The vpc names do not appear

## 5.0.0-beta
![image](https://user-images.githubusercontent.com/6698529/55969366-a6aa6c00-5c4b-11e9-818d-38dad03fd87a.png)

![image](https://user-images.githubusercontent.com/6698529/55969727-4d8f0800-5c4c-11e9-8d83-114cf7bbc781.png)

## 4.2.post5
![image](https://user-images.githubusercontent.com/6698529/55969148-4ca9a680-5c4b-11e9-9f56-6344af39d38c.png)

**Comment by j4v** [comment]
Could be related to https://github.com/nccgroup/ScoutSuite/issues/346.

There are also some weird spaces in the left menu:

![sc_2019-04-11_18h11m18s](https://user-images.githubusercontent.com/4206926/55973199-57812d00-5c85-11e9-8e39-a1115b536ed7.jpg)

**Comment by j4v** [comment]
Closing as tracked in #346 and fixed in https://github.com/nccgroup/ScoutSuite/pull/373.

**Comment by j4v** [comment]
> The network ACLs do not appear in the sub menu, but they did when tested with 4.2.0.

This was due to https://github.com/nccgroup/ScoutSuite/issues/346.
