### ISSUE TITLE
FP for Cloud SQL "Instance with no backups" finding

### ISSUE THREAD

**Issue by j4v** [nccgroup/ScoutSuite#35]
Scout indicates `Last Backup: N/A` even though [automated] backups are present.

Unsure if this FP is due to not taking into account automated backups - to confirm.

**Comment by Aboisier** [comment]
I am unable to reproduce this bug.

![image](https://user-images.githubusercontent.com/6698529/51748226-c46b2a80-2079-11e9-8247-114e82cce19b.png)

![image](https://user-images.githubusercontent.com/6698529/51748328-157b1e80-207a-11e9-87b3-6344bf39fc76.png)

**Comment by j4v** [comment]
Have not been able to reproduce either. Closing for now, will re-open if issue arrises again.
