### ISSUE TITLE
Allow user to decide page size(s)

### ISSUE THREAD

**Issue by vifor2** [nccgroup/ScoutSuite#355]
Currently the page size is hard-coded in the first line of `pagination.js` : `const defaultPageSize = 2`. It would be nice to give the user the option to select the number of elements they want to see per page.

TODO : 
- [ ] Add a drop-down menu to select the page size (make it only visible on the same places as the next page buttons).
- [ ] Save the new value of the page size for the proper resource (the way Iv'e coded it atm each resource can have it's own page size).

**Comment by j4v** [comment]
Closing this as fixed-length pagination is common (unless it's for an API) and this isn't planned.
