### ISSUE TITLE
Handle multiple Azure subscriptions in one execution of Scout

### ISSUE THREAD

**Issue by misg** [nccgroup/ScoutSuite#359]
Currently, Azure support only handles a single subscription (there was not enough time to do more as part of #183). This could be improved to handle subscriptions the same way projects and organizations are handled respectively in GCP and AWS.

**Comment by j4v** [comment]
Potentially related to https://github.com/nccgroup/ScoutSuite/issues/337.

**Comment by xlash** [comment]
Workaround, you can set your default azure subscription with Azure CLI tools.
`
az account set --subscription <SUBSCRIPTION_ID>`
`
python scout.py --provider azure --tenant <TENANT_ID> --subscription <UNIMPLEMENTED_SUBSCRIPTION_ID> --cli
`

**Comment by j4v** [comment]
Brilliant, thanks @xlash I'll add this to the Wiki.

**Comment by j4v** [comment]
> --tenant <TENANT_ID> --subscription <UNIMPLEMENTED_SUBSCRIPTION_ID>

@xlash it should work without having to use these arguments. When running with `--cli` it infers those values from what's configured in azure-cli, so passing a subscription/tenant should not have any impact.

**Comment by j4v** [comment]
Closing, implemented in `develop`.
