### ISSUE TITLE
Enhancement/Revisit the --update functionality

### ISSUE THREAD

**Issue by j4v** [nccgroup/ScoutSuite#361]
It isn't very well explained and documented. Should ensure the implementation fits the intended purpose.

**Comment by l01cd3v** [comment]
The idea of the `--update` functionality was to allow fetching resources for a limited number of services without losing everything else. This is particularly helpful when dealing with large environments, where you may just want to get the updated configuration for a single, or few services.

Running the following command would make API calls to get the IAM resources, but would not destroy the resources that were previously-fetched for all other services:
```
./scout.py aws --update --services iam
```

Currently, it appears that use of the `--update` feature results in the data still being available in the JSON results, but not visible via the HTML report.

**Comment by j4v** [comment]
Closing, this is implemented in https://github.com/nccgroup/ScoutSuite/pull/924.
