### ISSUE TITLE
Assessing users in Azure

### ISSUE THREAD

**Issue by jagallardo19** [nccgroup/ScoutSuite#375]
Good Afternoon,
After some work, I have identified that I am currently unable to see whether a user (admin or otherwise) has implemented MFA for a particular subscription. I've used Managed Service Identities and AZ client.
 Please advise.

**Comment by j4v** [comment]
@jagallardo19 I'm unsure what exactly you are raising here? Are you just saying this is a feature that is currently missing from Scout?

**Comment by jagallardo19** [comment]
Correct, I apologize, that is what I am saying. I am unable to find it within Scout Suite. I believe I have been going through the tool a number of times to see if I missed it. So I believe this feature is missing from the Azure perspective.

**Comment by j4v** [comment]
There are a lot of issues "missing". The goal is currently to cover all issues in the CIS benchmark, but lack of support from the Azure APIs (including for the AD service) have been making this difficult to implement. 

This feature is planned but I can't provide a timeline.

**Comment by jagallardo19** [comment]
Thank you for the feedback! It's greatly appreciated.

**Comment by j4v** [comment]
Closing, tracked in https://github.com/nccgroup/ScoutSuite-Proprietary/issues/37.
