### ISSUE TITLE
External Rules

### ISSUE THREAD

**Issue by mattyjones** [nccgroup/ScoutSuite#394]
I am looking at how this is designed and the available options and was wondering if a feature that would allow rules and rulesets to be loaded from elsewhere would be accepted.

What I am thinking is that in a large org a security engineering team would be responsible for the application code in a specific repo but then a separate repo would just be rules and rulesets broken up by provider.
```
/REPO_ROOT
   /AWS
     /conditions
     /filters
     /findings
   /GCP
     /conditions
     /filters
     /findings
```

Something to the above effect.

The point being other teams and orgs could contribute rules to a central location that could be pulled down independently of ScoutSuite. When running ScoutSuite the ruleset would then contain  some sort of identifier of the rule location `rule-path: /path/to/rule`. If none was given then the current functionality of having the rule in the repo would be used. The ability to specify a path for all rules such as `--rule-path /path/to/rules` may also be used and if not present then the current default location would be used.

1. `rule-path: path/to/rule` 
2. `--rule-path path/to rules`
3. existing functionality

**Comment by j4v** [comment]
You can already specify an ruleset at an arbitrary location (`--ruleset`), but as you mention Scout will look for the actual rules in it's own folders. I'm not against a `--rules-path` arg that would allow telling Scout to look for rules in a separate directory.

I'd thing it would be easier to just sync your ruleset/rules repo content into your Scout directory (e.g. with https://pypi.org/project/dirsync/).

**Comment by mattyjones** [comment]
That is a path I will look at as well. I wasn't aware of that library. Thanks!
