### ISSUE TITLE
[GCP] serviceAccounts key not in raw_instance

### ISSUE THREAD

**Issue by mfr-itr** [nccgroup/ScoutSuite#396]
```
$ scout gcp --user-account
Task exception was never retrieved
future: <Task finished coro=<Instances.fetch_all() done, defined at /home/user/.local/lib/python3.7/site-packages/ScoutSuite/providers/gcp/resources/gce/instances.py:17> exception=KeyError('serviceAccounts')>
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.7/site-packages/ScoutSuite/providers/gcp/resources/gce/instances.py", line 20, in fetch_all
    instance_id, instance = self._parse_instance(raw_instance)
  File "/home/user/.local/lib/python3.7/site-packages/ScoutSuite/providers/gcp/resources/gce/instances.py", line 36, in _parse_instance
    instance_dict['service_accounts'] = raw_instance['serviceAccounts']
KeyError: 'serviceAccounts'
```
I'm using 5.0.post3. The report is generated properly.

The GCP account I audit is not my own so I can't give you access or raw data. Tell me if you need something else for debugging.

**Comment by j4v** [comment]
Thanks @mfr-itr, will look into it. Looks like the account might not have any service accounts.

Any way you can share the errors file (`scoutsuite-results/scoutsuite_errors_...`)? You can send it to scout@nccgroup.com.

**Comment by mfr-itr** [comment]
This file doesn't exist, and scoursuite_exceptions* is:
```
exceptions =
{}
```

**Comment by j4v** [comment]
No problem, that means that no exceptions were raised (other then the unhandled one you mention).

**Comment by mfr-itr** [comment]
Thanks for the quick answer ^^

**Comment by j4v** [comment]
Closing, fixed in `develop`.

**Comment by mfr-itr** [comment]
Nice, thanks

**Comment by mfr-itr** [comment]
Well, same error with `canIpForward` XD

**Comment by j4v** [comment]
Keep 'em coming :smile: . Thanks, will fix ASAP (feel free to submit a PR!).

**Comment by j4v** [comment]
Closing as merged into `develop`. Any other issues don't hesitate.
