### ISSUE TITLE
Enhancement/Default for `run()` function

### ISSUE THREAD

**Issue by j4v** [nccgroup/ScoutSuite#397]
Solve this:

```
Is there a reason the ScoutSuiteArgumentParser has to be used to get defaults instead of making the arguments to the run function optional with suitable defaults?

I would like to avoid using the ScoutSuiteArgumentParser if possible but seems the only way to currently do that would be to pass all of the 38 arguments with some sensible defaults (or create a ScoutSuiteArgumentParser just to get a dictionary of the default values and then override any that need changing)
```

By providing defaults in 'run()'.

**Comment by j4v** [comment]
Additionally, it looks like `--vpc` and `--resume` are present in the ArgumentParser but are not passed to `run()`. Should investigate if these were removed at some point, or never actually implemented.

**Comment by thommor** [comment]
From what I can tell `--vpc` and `--resume` are not currently implemented

**Comment by j4v** [comment]
Closing as `--vpc` and `--resume` are removed in https://github.com/nccgroup/ScoutSuite/pull/400. `--resume` will be worked on in https://github.com/nccgroup/ScoutSuite/issues/88.
