### ISSUE TITLE
Azure - Results filtering does not work

### ISSUE THREAD

**Issue by xlash** [nccgroup/ScoutSuite#402]
Got a report, drilling down on issues for Networking/Security rule allowing SSH inbound access in security group

All security groups are listed, displayed and no highlights of the problematic rules set.

Expected behavior : Only display, or highlight problematic Network Security Groups.

Quick code review, I was able to find the issue, there is a hideItem function in scoutsuite.js, which uses a regular expression to find all div to hide.

Here's a div which is not being hidden, because it contains a dot before the last .view section. The dot is caused by providers/Microsoft.Network.

**Problematic function in scoutsuite.js**
```javascript
 function hideItems(resourcePath) {
    let path = resourcePath.replace(/.id./g, '\.[^.]+\.') + '\.[^.]+\.view'
    $('div').filter(function () {
        return this.id.match(path)
    }).hide()
}

```
**Gist to test**
```javascript
"services.network.network_security_groups./subscriptions/888888888-8888-8888-8888-888888888888/resourceGroups/MYNAMEdevops-_eastus/providers/Microsoft.Network/networkSecurityGroups/MY_NSG_NAME-nsg.view
".match("services.network.network_security_groups.[^.]+.view")
> returns null
```

**Comment by j4v** [comment]
Thanks @xlash, I'm guessing there's an error in the partial for that resource.

**Comment by j4v** [comment]
> All security groups are listed, displayed 

This is now fixed, the resource IDs were breaking the regex.

> no highlights 

This isn't currently implemented, some more work is required for this functionality.

Closing as this is now fixed in `develop`.
