### ISSUE TITLE
AWS provider  RequestLimitExceeded errors

### ISSUE THREAD

**Issue by cjbischoff** [nccgroup/ScoutSuite#403]
- I receive several errors RequestLimitExceeded - (reached max retries: 4): Request limit exceeded.

**Comment by j4v** [comment]
Looks like your account is hitting an AWS limit, this isn't a Scout issue per se.

Are you running a lot of concurrent activities that require API requests? AWS limits API calls per-region/account.

I recommend running Scout with less workers with `--max-workers` (default is 10).

**Comment by cjbischoff** [comment]
- Thank you 
-- I will utilize that CLI option
