### ISSUE TITLE
Implementation of rds-postgres-instance-with-invalid-certificate.json

### ISSUE THREAD

**Issue by shivani-singhal** [nccgroup/ScoutSuite#410]
The aws check for Invalid SSL certificate (PostgreSQL), looks at the creation date of the instance instead of validTo field of a certificate and compares it to a hard coded date. I am unable to understand what is this check trying to do, it seems to be doing something different from what the description says. 
Can someone please clarify this?
https://github.com/nccgroup/ScoutSuite/blob/master/ScoutSuite/providers/aws/rules/findings/rds-postgres-instance-with-invalid-certificate.json

**Comment by j4v** [comment]
I'll look into it, thanks.

**Comment by j4v** [comment]
Looks like it's referring to:
- https://aws.amazon.com/about-aws/whats-new/2017/02/amazon-rds-for-sql-server-supports-forced-ssl/
- https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/SQLServer.Concepts.General.SSL.Using.html (Encrypting Specific Connections)

TBH I'm not too sure what to do with this. @shivani-singhal thoughts?

**Comment by shivani-singhal** [comment]
would it make sense for this check to first see whether an RDS instance has a certificate id linked to it, if yes check that the certificate expiration date is later than check date?

**Comment by j4v** [comment]
@shivani-singhal yep that makes sense, will do - thanks.

**Comment by j4v** [comment]
Updated finding title and added rationale (`develop` branch), considering this as closed.
