### ISSUE TITLE
GCP Errors

### ISSUE THREAD

**Issue by calvinkim93** [nccgroup/ScoutSuite#428]
When running on GCP, I am getting a ton of these errors after fetching stackdriver resources and before running the ruleset. It seems to continue past them and successfully check the rulesets, but I am unsure if these errors are limiting result findings.

> scout[11225] ERROR gce.py L66: Failed to retrieve project: Unable to find the server at www.googleapis.com
scout[11225] ERROR gce.py L36: Failed to retrieve compute instances: 'NoneType' object is not subscriptable
scout[11225] ERROR gce.py L66: Failed to retrieve project: Unable to find the server at oauth2.googleapis.com
scout[11225] ERROR gce.py L36: Failed to retrieve compute instances: 'NoneType' object is not subscriptable
scout[11225] ERROR gce.py L66: Failed to retrieve project: Unable to find the server at oauth2.googleapis.com
scout[11225] ERROR gce.py L36: Failed to retrieve compute instances: 'NoneType' object is not subscriptable
scout[11225] ERROR gce.py L66: Failed to retrieve project: Unable to find the server at oauth2.googleapis.com
scout[11225] ERROR gce.py L36: Failed to retrieve compute instances: 'NoneType' object is not subscriptable
scout[11225] ERROR gce.py L66: Failed to retrieve project: Unable to find the server at oauth2.googleapis.com
scout[11225] ERROR gce.py L36: Failed to retrieve compute instances: 'NoneType' object is not subscriptable
scout[11225] ERROR iam.py L15: Failed to retrieve service account IAM policy bindings: Unable to find the server at oauth2.googleapis.com
scout[11225] ERROR iam.py L27: Failed to retrieve service account keys: Unable to find the server at oauth2.googleapis.com
scout[11225] ERROR iam.py L13: Failed to retrieve service account IAM policy bindings: Unable to find the server at www.googleapis.com
scout[11225] ERROR iam.py L25: Failed to retrieve service account keys: Unable to find the server at www.googleapis.com
scout[11225] ERROR iam.py L13: Failed to retrieve service account IAM policy bindings: Unable to find the server at www.googleapis.com

**Comment by j4v** [comment]
First time I see this. Googling a bit it seems like this isn't an issue with the libs per se but rather that your host just can't resolve the API domains?

Have you confirmed that you *can* resolve www.googleapis.com and oauth2.googleapis.com?

**Comment by calvinkim93** [comment]
Hmm very odd I was getting this error the other day every time I ran, even though it was running successfully, but today I am not getting it. :)
