### ISSUE TITLE
Only 1 set of results can be saved

### ISSUE THREAD

**Issue by pageholder** [nccgroup/ScoutSuite#429]
While running multiple tests against different AWS accounts I've noticed that once a set of reports is generated into the 'scoutsuite-report' folder it will remain there even during additional runs.

I've found a workaround which is to delete to move the report folder out of the main directory and then running the second test, maybe have the ability to set an external folder to save multiple report sets in or allow multiples to be saved in the main directory.

**Comment by j4v** [comment]
I think the `--report-dir` CLI parameter does what you want? Just output each execution to a different directory.

**Comment by pageholder** [comment]
Thanks, couldn't find it in the wiki but this has led me to dig through the rest of the code to see the other options available!

**Comment by j4v** [comment]
Cheers, you can use the following commands to identify options:
`python scout.py -h`
`python scout.py aws -h`
