### ISSUE TITLE
Issue parsing IAM policies with empty document

### ISSUE THREAD

**Issue by j4v** [nccgroup/ScoutSuite#431]
Couple of potential issues to look into:

```
[
    {
        "additional_details": null,
        "exception": "Could not fetch iam configuration: 'PolicyDocument'",
        "file": "services.py",
        "line": 53,
        "traceback": "Traceback (most recent call last):\n  File \"/home/tester/venv/lib/python3.6/site-packages/ScoutSuite/providers/base/services.py\", line 53, in _fetch\n    await service_config.finalize()\n  File \"/home/tester/venv/lib/python3.6/site-packages/ScoutSuite/providers/aws/resources/iam/base.py\", line 37, in finalize\n    self._parse_inline_policies_permissions('roles')\n  File \"/home/tester/venv/lib/python3.6/site-packages/ScoutSuite/providers/aws/resources/iam/base.py\", line 66, in _parse_inline_policies_permissions\n    policy_id, policy['PolicyDocument'], 'inline_policies', resource_type, resource_id)\nKeyError: 'PolicyDocument'\n"
    }
]
```

```
Task exception was never retrieved
future: <Task finished coro=<IAMFacade._get_and_set_inline_policies() done, defined at /home/tester/venv/lib/python3.6/site-packages/ScoutSuite/providers/aws/facade/iam.py:187> exception=TypeError('string indices must be integers',)>
Traceback (most recent call last):
  File "/home/tester/venv/lib/python3.6/site-packages/ScoutSuite/providers/aws/facade/iam.py", line 220, in _get_and_set_inline_policies
    policy_document)
  File "/home/tester/venv/lib/python3.6/site-packages/ScoutSuite/providers/aws/facade/iam.py", line 228, in _normalize_statements
    if type(statement[action_string]) != list:
TypeError: string indices must be integers
```

Might be caused by an inline policy with no statement.

**Comment by j4v** [comment]
This appears to be caused by roles with an empty policy document (`"{}"`). The odd thing is that this is not possible through the web console / cli.

**Comment by phene** [comment]
I've also seen this happen if the `Statement` is a Hash instead of an Array, which is technically valid: (e.g.)

```json
{
  "Statement": {
    "Effect": "Allow",
    "Action": "s3:*"
    "Resource": "*"
  }
}
```

**Comment by Booyaka27** [comment]
Hi, don't know if it could help but, when I run scout.py for aws using --profile, I d'on't get the "TypeError: string indices must be integers" but if using --access-keys, I got it ....

**Comment by Booyaka27** [comment]
> Hi, don't know if it could help but, when I run scout.py for aws using --profile, I d'on't get the "TypeError: string indices must be integers" but if using --access-keys, I got it ....

No in fact, I think this u-is linked of access role behind the access, through access key, I have less access rights than from profile ... sorry

**Comment by dgifork** [comment]
Have you got updates on it ?
I have the same issue.
How to find the policy with document ("{}") ?

**Comment by Booyaka27** [comment]
Maybe it has to be confirmed, but when I used a user account with full access, I don't get errors, if I used a user account with read all I get it.

**Comment by j4v** [comment]
> Have you got updates on it ?

@dgifork we have not looked into it yet.

> Maybe it has to be confirmed

@Booyaka27 please test before submitting potential FPs.

**Comment by j4v** [comment]
@dgifork this should now be fixed in `develop` branch, please reopen if the issue is not resolved on your end.
