### ISSUE TITLE
GCP False Positive Detection on CloudSQL Replicated Resources 

### ISSUE THREAD

**Issue by rusty-martin** [nccgroup/ScoutSuite#437]
Currently the tool is detecting the below items on CloudSQL failover instances. Since there is no way to configure these options on a failover instance the tool should ignore that type or have a more defined ruleset for failover options.

- Automatic backup disabled
- Binary logging disabled
- Instance with no backups
- SSL not required

**Comment by j4v** [comment]
Thanks for this @rusty-martin. I've pushed a fix to the `develop` branch, could you please confirm this resolves the issue?

**Comment by rusty-martin** [comment]
Confirmed fixed failover instances no longer show as findings!
