### ISSUE TITLE
Smart Quote character in README.md sometimes causes pip install failure

### ISSUE THREAD

**Issue by gebailey** [nccgroup/ScoutSuite#44]
I'm attempting to migrate from (the now deprecated) AWSScout2, and in some cases, a pip install of scoutsuite can fail due to a smart-quote character in README.md.  Using the following `Dockerfile`:
```
FROM bitnami/minideb:stretch
RUN install_packages curl jq patch uuid-runtime python3-pip && pip3 install setuptools wheel && pip3 install awscli boto3
RUN pip3 install scoutsuite
```
yields:
```
$ sudo docker build -t scoutsuite .
Sending build context to Docker daemon 22.53 kB
Step 1/3 : FROM bitnami/minideb:stretch
 ---> 2a1cee458dac
Step 2/3 : RUN install_packages curl jq patch uuid-runtime python3-pip && pip3 install setuptools wheel && pip3 install awscli boto3
 ---> Using cache
 ---> b25d3c56f96e
Step 3/3 : RUN pip3 install scoutsuite
 ---> Running in 24d0638f56e6

Collecting scoutsuite
  Downloading https://files.pythonhosted.org/packages/8e/96/d87a0b6910ca51f3def0d623c586bb9eaed385ea90e74047a2f51c5b9a16/ScoutSuite-4.0.3.tar.gz (384kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-5xzyk4e7/scoutsuite/setup.py", line 24, in <module>
        long_description=open('README.md').read(),
      File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 4377: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-5xzyk4e7/scoutsuite/
The command '/bin/sh -c pip3 install scoutsuite' returned a non-zero code: 1
```

It appears that line 118 (or 119, depending on the version) of `README.md` contains a smart quote character that's not handled in the docker build environment.

If I manually run pip within a virtual environment on CentOS 7, the module installation completes successfully.  Not sure if it's related to `LANG` or `LC_ALL` being set/unset, but it seems that replacing the smart quote with an apostrophe is the most straightforward fix.

Also, the release management process is a bit confusing, as the GitHub repo only has a version 4.0.2 tag, while PyPI shows 4.0.0, 4.0.1, 4.0.2, and 4.0.3.  As a result, it's not clear what commits are present in the various PyPI versions.

**Comment by j4v** [comment]
Can you confirm that merging the PR solved the issue?

You are right about releases, I'll be more consistent with them. Thanks for the feedback!

**Comment by gebailey** [comment]
Yes, the following `Dockerfile` appears to work by grabbing master:
```
FROM bitnami/minideb:stretch
RUN install_packages curl jq patch uuid-runtime python3-pip && pip3 install setuptools wheel && pip3 install awscli boto3
#RUN pip3 install scoutsuite
RUN pip3 install https://github.com/nccgroup/ScoutSuite/archive/master.zip
```
thanks!

**Comment by gebailey** [comment]
> Can you confirm that merging the PR solved the issue?

There's obviously a workaround, but I'm assuming we should leave this issue open until a new module is published to PyPI?

**Comment by j4v** [comment]
Updated PyPi and generated a new GH release.
