### ISSUE TITLE
When using profiles to role switch to other accounts Scout scans the default profile

### ISSUE THREAD

**Issue by FishermansEnemy** [nccgroup/ScoutSuite#449]
I have a default profile with AWS ID and Secret Key set in credentials (deafult). I have two profiles in config, profilea and profileb which I role switch into to get access to their accounts. AWS cli works fine and when using these profiles from AWS cli I can see the three different accounts.

When I run scout with the --profile profilea or --profile profileb it runs and produces the same report for the default profile, along with the same account number.

**Comment by j4v** [comment]
I think this is the same as https://github.com/nccgroup/ScoutSuite/issues/425. 

Can you show what you mean by "AWS cli works fine"? We're using boto3's implementation for authentication (https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html) so in theory it should work.

**Comment by FishermansEnemy** [comment]
That does look like the same issue as I am having. By “AWS Cli works fine” I mean I can issue commands as one of my two profiles and see contents from the accounts that each profile have a role in.

**Comment by j4v** [comment]
Thanks @FishermansEnemy, will have to look into how boto3 handles this as it might not be as straightforward as what their doc says.
Using the config file and "source_profile" seems to be part of the issue.

**Comment by j4v** [comment]
@FishermansEnemy this should now be resolved in branch https://github.com/nccgroup/ScoutSuite/tree/bugfix/aws-session-handling - could you please test?

**Comment by j4v** [comment]
Closing, this should be resolved by https://github.com/nccgroup/ScoutSuite/pull/460. If not please reopen the issue.
