### ISSUE TITLE
exposing Scout html report to a Nginx webserver

### ISSUE THREAD

**Issue by chitender** [nccgroup/ScoutSuite#459]
hi,

we recently used the Scout and got the report generated. now we have requirement where we need to present it as Dashboard to Infra/devops stakeholders. so that on upon any abnormality a necessary action can be taken by the respective stake holders.

now we have a plan to schedule the cron job on EC2 linux machine to generate the Scout report and once report is generated we will be exposing it to Nginx webserver to make it available to the internal stake holders.

any suggestions on this will be highly appreciated. or if we already have some sort have module top do this then let us know.

looking forward to receive feedback on this soon.

**Comment by j4v** [comment]
Closing this as it is outside of the scope of the open source project.
