### ISSUE TITLE
RuleExceptions not applied

### ISSUE THREAD

**Issue by smonfort-cacd2** [nccgroup/ScoutSuite#46]
When I create an exception list from the UI and run the scan again with the exception file, it seems that RuleExceptions are not applied because of the following line.

https://github.com/nccgroup/ScoutSuite/blob/2eef793ee779a1c964114d257d208cd504b79992/ScoutSuite/core/exceptions.py#L35

Changing the line to the following seems to fix the issue.

`cloud_provider.services[service]['findings'][rule]['flagged_items'] = len(cloud_provider.services[service]['findings'][rule]['items'])
`

**Comment by j4v** [comment]
Brilliant, thank you for raising this and providing the fix.

**Comment by j4v** [comment]
Updated PyPi/releases, closing.
