### ISSUE TITLE
Cross-account AssumeRole policy lacks external ID and MFA

### ISSUE THREAD

**Issue by heydonovan** [nccgroup/ScoutSuite#466]
Our kubernetes nodes/pods assume roles whenever they need to using kube2iam. Multi factor auth doesn't make sense for an external role, as it's an automated process. Are we sure this shouldn't be an OR instead of an AND? Also, isn't an external ID set here?

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "Service": "ec2.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    },
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::12345:root"
      },
      "Action": "sts:AssumeRole",
      "Condition": {
        "StringLike": {
          "aws:PrincipalArn": "arn:aws:iam::12345:role/production*"
        }
      }
    }
  ]
}
```

**Comment by j4v** [comment]
@heydonovan just had a look at the rule's implementation and it's checking whether none of either MFA or External ID are implemented. So if you have one of these the rule shouldn't get triggered. Is this not the case?

**Comment by j4v** [comment]
Closing due to lack of feedback - will reopen if anything changes.

**Comment by j4v** [comment]
I'm not sure what you're actually raising. Are you assuming roles cross-account?

**Comment by heydonovan** [comment]
@j4v I'm running into this one again, so I'd like to reopen.

>Report generated with Scout Suite version 5.8.1

```
"Statement":  [
{
  "Action": [
    "sts:AssumeRole"
  ],
  "Condition": {
    "StringLike": {
      "sts:ExternalId": "REDACTED"
    }
  },
  "Effect": "Allow",
  "Principal": {
    "AWS": "arn:aws:iam::REDACTED:user/REDACTED"
  },
  "Sid": ""
}
  ] ,
  "Version":  "2012-10-17"
```

The `Cross-account AssumeRole policy lacks external ID and MFA` policy is the one that triggers, even though an `ExternalId` is clearly defined in the policy. A kubernetes pod (kube2iam) can't use an MFA device, so it could never fulfill this one.

**Comment by j4v** [comment]
@heydonovan are you certain this is the policy that is being flagged? I'll try to reproduce.

> A kubernetes pod (kube2iam) can't use an MFA device, so it could never fulfill this one.

Sure, hence why a external ID should be used.

**Comment by j4v** [comment]
Thanks for raising this @heydonovan - we weren't checking `StringLike`, only `StringEquals`. I've fixed the rule and one other occurrence of this.
