### ISSUE TITLE
Feature Request - List supported services

### ISSUE THREAD

**Issue by museadmin** [nccgroup/ScoutSuite#467]
Hi

You support skipping services in AWS via these options:

  --services SERVICES [SERVICES ...]
                        Name of in-scope services.
  --skip SKIPPED_SERVICES [SKIPPED_SERVICES ...]
                        Name of out-of-scope services.

Can you add an option to list supported services that you can skip or include?

My thinking is that it would make it simple for the user to use the correct service name format when using the above options. Also, as people add in services, it could dynamically update the list of services available to skip or include.

**Comment by j4v** [comment]
Thanks @museadmin, I agree it would be a good improvement. A bit tricky to implement as services are loaded dynamically but I'm sure we can figure it out.

**Comment by j4v** [comment]
> A bit tricky to implement as services are loaded dynamically but I'm sure we can figure it out. 

Not that tricky if we check this dynamically though...

**Comment by j4v** [comment]
Closing, implemented in `develop`.
