### ISSUE TITLE
AssumeRole with Ec2InstanceMetadata credential_source fails to get security token

### ISSUE THREAD

**Issue by phene** [nccgroup/ScoutSuite#470]
I am trying to run scoutsuite on an instance running an AWS that has a config like such:

## AWS Config
```
[profile foo]
region = us-west-2
metadata_service_num_attempts = 5
credential_source = Ec2InstanceMetadata
role_arn = arn:aws:iam::1234567891234:role/MyRoleWithNecessaryAccess
```
## Running:

`scout aws --profile foo`

## Produces:

`An error occurred (InvalidClientTokenId) when calling the ListStacks operation: The security token included in the request is invalid`

## Hypothesis

aws cli commands have no problem performing an assume role with the credential_source `Ec2InstanceMetadata`, but I suspect scout is not properly configured to handle that authentication scenario. I have similarly had to handle that cause with custom libraries that perform authentication using the instance profile credentials to assume a role.

**Comment by j4v** [comment]
Scout leverages boto3, please have a look at https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html#assume-role-provider on how to configure this and please provide feedback.

**Comment by phene** [comment]
Adding a `--region` argument to the command invocation made it work despite my profile specifying a a region. Perhaps the docs need to be updated to indicate its required?

**Comment by j4v** [comment]
Looks like you were running into issue https://github.com/nccgroup/ScoutSuite/issues/381 then.

Scout doesn't look at the default region you have specified in your configs because by default it runs against all regions.

**Comment by phene** [comment]
Oh, we have some regions disabled, so that is likely the cause. Thanks!
