### ISSUE TITLE
Route53 hosted zones

### ISSUE THREAD

**Issue by benghaun** [nccgroup/ScoutSuite#473]
The `hosted_zones` resource for route53 was removed in #267, and a case was made to bring it back in #298. However, #298 was closed although the resource has not been added back. Aside from the fact that `hosted_zones` are viewable in the ScoutSuite report, having information about all DNS records in Route53 has also been helpful for further security checks.

Are there plans to add the `hosted_zones` resource back? If no one is working on it, I will be happy to take it up. 

Thank you!

**Comment by j4v** [comment]
Looks like there was some confusion in the issue(s)/PR(s) and indeed they weren't brought back. No objection to doing so, we just haven't gotten around to doing it.

@benghaun if you can submit a PR I'll be happy to review/merge.

**Comment by j4v** [comment]
Closing as implemented in https://github.com/nccgroup/ScoutSuite/pull/493.
