### ISSUE TITLE
Security Issue / Feature Request - Can we have a redact option?

### ISSUE THREAD

**Issue by museadmin** [nccgroup/ScoutSuite#474]
At the moment, the ScoutSuite HTML report publishes the AWS account ID on the head of its landing page. This is a security issue, severely limiting the number of people who can view the report.

It would be good to have a cmd line switch to redact this. 

I haven't reviewed the entire report with this in mind, but it might be a good idea to extend this to any sensitive content in the detailed report, or perhaps produce a more generic statistical report that simply tells the users what areas of the platform are experiencing issues, without reporting any IDs or other sensitive information.

This would be useful for stakeholders who don't need to know that level of detail anyway, who are primarily interested in seeing if the trends are going up or down for vulnerabilities, rather than identifying those vulnerable components.

**Comment by j4v** [comment]
While I understand that there are some cases where this could be beneficial, the cost of implementing this doesn't make it worth it. If the account ID is too sensitive to show/distribute then all of the content of the report would also be.

I think options such as https://github.com/nccgroup/ScoutSuite/issues/438 (ability to export a summary of findings in other formats such as CSV) is a better way to go, as this will be easier to modify/redact.
