### ISSUE TITLE
Bug in "iam-inline-policy-allows-non-sts-action.json" reference

### ISSUE THREAD

**Issue by rscottbailey** [nccgroup/ScoutSuite#477]
I see that ScoutSuite/providers/aws/rules/findings/iam-inline-policy-allows-non-sts-action.json includes: (among other things)

`"key": "iam-inline-_ARG_0_-policy-allows-non-sts-action",`

which based on other rules suggests it is meant to be called with arguments. But both default.json and detailed.json in ScoutSuite/providers/aws/rules/rulesets specify only:

```
        "iam-inline-policy-allows-non-sts-action.json": [
            {
                "enabled": false,
                "level": "danger"
            }
        ],
```

I am too wet behind the ears with both AWS and ScoutSuite to guess confidently what missing arguments should be provided. This is messing with the mind of a script that processes ScoutSuite's JSON output because I cannot guess what finding(s) might be generated by this rule.

As the affected code appears to be the same in both master and develop, I am guessing nobody else has reported this problem yet.

**Comment by j4v** [comment]
Thanks @rscottbailey, will look into this. Wouldn't be the first time a rule is expecting params that aren't provided so will confirm the issue.

**Comment by j4v** [comment]
This should be fixed in `develop`, although I'm not sure what the rule is for...
