### ISSUE TITLE
No test for if ec2 snapshots are encrypted

### ISSUE THREAD

**Issue by get-fooby** [nccgroup/ScoutSuite#484]
On the EC2 dashboard, there is no test listed for if a snapshot is encrypted. Other toolsets check if this is the case. The details for snapshots in my environment was successfully returned (211 snapshots) but no test for if encrypted is made.

**Comment by j4v** [comment]
You're right, we're currently checking if volumes are encrypted but not snapshots.

**Comment by j4v** [comment]
TODO: move from prop to pub.
