### ISSUE TITLE
How to exclude one region ap-east-1 for cloud trail when running profilefor multiple accounts?

### ISSUE THREAD

**Issue by challs1** [nccgroup/ScoutSuite#487]
@j4v I am running profiles for multiple regions but i want to eliminate one region in cloudtrail. how to do that?

**Comment by j4v** [comment]
Currently the `--region` flag allows to include a subset of regions but there is no flag that allows excluding regions. If this is deemed useful then it could be added.

**Comment by challs1** [comment]
@j4v : Excellent! Thanks

**Comment by challs1** [comment]
@j4v :Can u add that feature please?

**Comment by j4v** [comment]
@challs1 this will be added as part of release 5.4.0, no ETA atm.

**Comment by j4v** [comment]
@challs1 this is implemented in https://github.com/nccgroup/ScoutSuite/pull/495 and should be merged into `master` this week. Please test.

**Comment by j4v** [comment]
Closing as merged in `develop`.

**Comment by challs1** [comment]
Will test and let u know the results
