### ISSUE TITLE
AWS - Exceptions for elbv2-no-deletion-protection does not work

### ISSUE THREAD

**Issue by museadmin** [nccgroup/ScoutSuite#488]
I have exported exceptions for six warnings about lack of deletion protection:

> "elbv2": {
          "elbv2-no-deletion-protection": [
              "elbv2.regions.eu-west-2.vpcs.vpc-00ebca69.lbs.142613befb6693222fb07d5d426bf3b3804f7378.attributes.4",
              "elbv2.regions.eu-west-2.vpcs.vpc-00ebca69.lbs.231d22355c8c99db3d2a4dc00c790ae582a7535c.attributes.4",
              "elbv2.regions.eu-west-2.vpcs.vpc-00ebca69.lbs.542a182a61f339f347f43c50ad3841c15a389c44.attributes.4",
              "elbv2.regions.eu-west-2.vpcs.vpc-00ebca69.lbs.7b88a6e0065347ad908c38c00a14f460d8075e36.attributes.4",
              "elbv2.regions.eu-west-2.vpcs.vpc-00ebca69.lbs.b600ced8b4ef431762019eba9d054a8fb9128933.attributes.4",
              "elbv2.regions.eu-west-2.vpcs.vpc-00ebca69.lbs.d6659e1a5e9ce711d2bbc10cf2e1577a303372e5.attributes.4",

But this has not resulted in those same six issues not being reported in the ScoutSuite "ELBv2/Lack of deletion protection" report.

> Attributes
access_logs.s3.enabled: true
access_logs.s3.bucket: ds-aud-nonprod-elb-logs
access_logs.s3.prefix: APP-INT-PUB-SUBMIT-ALB
idle_timeout.timeout_seconds: 60
deletion_protection.enabled: false
routing.http2.enabled: true

I assume the 4 on the end of each line is an index to a 0 based array pointing to the line deletion_protection.enabled: false?

**Comment by alessandrogonzalez** [comment]
I have tested it with version 5.7.0 and I could not reproduce the issue.

Please, reopen the issue if this is still a problem for you.
