### ISSUE TITLE
Use non zero exit code in case of warnings

### ISSUE THREAD

**Issue by LSwiatek** [nccgroup/ScoutSuite#491]
ScoutSuite should exit with non zero code if there were any issues detected - it is a common practice for unix programs to use non zero code in case of any issues

This would simplify integration with other tools and automated processes (for example CI tools). If ScoutSuite were to be a part of automated process, non zero exit code could be used to inform the users of some problems, without the need of manually verifying the report every time

**Comment by j4v** [comment]
From your perspective, should any exception raised result in a non zero code?

**Comment by thommor** [comment]
If any exception in the run causes a non zero error code these codes would need to be well defined and documented.

If exceptions are thrown for certain services these error codes should be different to exceptions such as credentials being incorrect.

**Comment by j4v** [comment]
It would be hard to implement this consistently. @thommor would you be happy with a non-zero code if any errors have been raised, considering these are all included in the errors file?

The rationale is that if a non-zero code is returned, reviewing the errors file should provide all the info needed.

**Comment by thommor** [comment]
The best approach would probably be to define a specific error code which when return indicates the scan succeeded but errors were raised during the run.

Then the errors file can be checked for more details.

**Comment by j4v** [comment]
@thommor how about:
- `0` no errors, everything ran fine
- `1` something went terribly wrong
- `2` the run completed but some errors were handled

**Comment by thommor** [comment]
Could we do something like:

- `0` no errors, everything ran fine
- `1XX` something went terribly wrong
- `2XX` the run completed but some errors were handled

This would help us understand exactly what went wrong. Not too much of an issue for `2XX` but would be very useful for `1XX` such as invalid credentials

**Comment by j4v** [comment]
Sounds good, for now I'd only implement blanket `100` & `200` and we can add more specific codes going forward.

**Comment by thommor** [comment]
👍

**Comment by LSwiatek** [comment]
consider having separate codes based on severity of findings in report

**Comment by j4v** [comment]
> consider having separate codes based on severity of findings in report

Not sure how that's relevant to the execution code?

**Comment by j4v** [comment]
Closing, implemented in `develop`.
