### ISSUE TITLE
Configurable rate limiting

### ISSUE THREAD

**Issue by thommor** [nccgroup/ScoutSuite#492]
In #91 the scenario was given where running a scan with ScoutSuite on a cloud account that makes alot of API calls itself could cause the API rate limit to be hit and cause inconsistencies in the cloud account

> I'm specifically hitting issues with autoscaling failing because AWS draws no distinction between the scanner making API calls on the CLI and their own autoscaling feature making API calls. Because the latter then fails to bring up the instance, the environment ends up in an indeterminate mess and the platform team have to scramble.

I believe it would be worth investigating being able to configure a rate limit inside of ScoutSuite that can be set through the cli which could be changed depending on how many internal API calls are made by the cloud account.

Perhaps something like [ratelimit](https://pypi.org/project/ratelimit/) could be useful

**Comment by j4v** [comment]
Closing as merged into `develop`.
