### ISSUE TITLE
Improvable Default SG Rules

### ISSUE THREAD

**Issue by j4v** [nccgroup/ScoutSuite#5]
`ec2-default-security-group-in-use.json`
- Checks that the `default` SG is in use, but not that the SG hasn't been modified to be secure.
- Add a `is_default_configuration` parameter to validate.

`ec2-default-security-group-with-rules.json`:
- Check that the `default` SG is in use and that is isn't empty, but not that it has the default configuration. Apply same check as previous.

**Comment by dagmawim** [comment]
@j4v Is this issue still open? I would like to work on it, if it is.

**Comment by j4v** [comment]
@dagmawim yes, we haven't gotten around to this one yet. Happy for you to work on it and submit a PR!

**Comment by dagmawim** [comment]
@j4v Great! Could you possibly give me a bit more context on the problem? (newbie problems)

**Comment by j4v** [comment]
The issue is in the 2 rules above (https://github.com/nccgroup/ScoutSuite/tree/master/ScoutSuite/providers/aws/rules/findings), that don't check exactly what they should.

**Comment by j4v** [comment]
This has been resolved in `develop`.
