### ISSUE TITLE
Custom Rules

### ISSUE THREAD

**Issue by lordcf** [nccgroup/ScoutSuite#500]
Hi, 
I want to create a new separate rule to check whether VPC flow logging is enabled or not, and display it on end HTML report, although we have the rule to check on subnet level.
I have added vpc-without-flow-log.json file in ScoutSuite/providers/aws/rules/findings as follows:
{
    "description": "VPC without a flow log",
        "rationale": "Description:",
    "path": "vpc.regions.id.vpcs.id",
    "dashboard_name": "VPC",
    "id_suffix": "NoFlowLog",
    "conditions": [ "or",
        [ "this", "withoutKey", "flow_logs"],
        [ "flow_logs", "empty", "" ]
    ]
}

and also added following code in default.json
 "vpc-without-flow-log.json": [
            {
                "enabled": true,
                "level": "warning"
            }
Is there anything extra to be added?
Can you please guide me with this.

**Comment by j4v** [comment]
@lordcf sorry this fell through the cracks. Is this issue still relevant?

**Comment by Kiramart** [comment]
Hi, 

Can I reopen the topic, I want to know if we only need to had the json file and add some code in the default file.
Moreover, for exemple, if I want to add a new rules about sns encryption, how can I find the right path ?

Can you please explain the steps to add a new rule

**Comment by ramimac** [comment]
@Kiramart Hi, I'd recommend looking to the documentation for rule creation: https://github.com/nccgroup/ScoutSuite/wiki/HowTo:-Create-a-new-rule
