### ISSUE TITLE
Improve CLI guidance

### ISSUE THREAD

**Issue by Seegras** [nccgroup/ScoutSuite#506]
We've got stuff running in several regions, but not all of them. Namely, we don't have the newer regions me-south-1 and ap-east-1 enabled, and don't intend to.

Is there a way to just disable regions?

**Comment by Seegras** [comment]
Found it. 

Compare: 

>  ./scout.py --help 
> usage: scout.py [-h] [-v] {aws,gcp,azure} ...
> 
> optional arguments:
>   -h, --help       show this help message and exit
>   -v, --version    show program's version number and exit
> 
> The provider you want to run scout against:
>   {aws,gcp,azure}
>     aws            Run Scout against an Amazon Web Services account
>     gcp            Run Scout against a Google Cloud Platform account
>     azure          Run Scout against a Microsoft Azure account

But: 

>  ./scout.py aws --help 
> usage: scout.py aws [-h] [-f] [-l] [--debug] [--quiet] [--logfile [LOG_FILE]]
>                     [--update] [--ruleset [RULESET]] [--no-browser]
>                     [--max-workers MAX_WORKERS] [--report-dir REPORT_DIR]
>                     [--report-name REPORT_NAME] [--timestamp [TIMESTAMP]]
>                     [--services SERVICES [SERVICES ...]]
>                     [--skip SKIPPED_SERVICES [SKIPPED_SERVICES ...]]
>                     [--exceptions [EXCEPTIONS]]
>                     [--result-format {json,sqlite}] [--serve [DATABASE_NAME]]
>                     [--host HOST_IP] [--port HOST_PORT] [-p PROFILE]
>                     [-r REGIONS [REGIONS ...]]
>                     [--ip-ranges IP_RANGES [IP_RANGES ...]]
>                     [--ip-ranges-name-key IP_RANGES_NAME_KEY]
> 

etc. 

Which isn't really intuitive.

**Comment by j4v** [comment]
This is because a number of CLI parameters are per-provider.

**Comment by Seegras** [comment]
Maybe you want to change the text to tell you that, if given no provider.

**Comment by PaulDMendoza** [comment]
It would be really helpful if you could expose this easier in the --help results somehow.

**Comment by j4v** [comment]
> Maybe you want to change the text to tell you that, if given no provider.

Do this.

**Comment by ramimac** [comment]
@j4v  I think folks looking for a specific callout that nested help menus exist. We could add this easily with an argparser epilog https://docs.python.org/3/library/argparse.html#epilog

**Comment by j4v** [comment]
Guess it's easy enough yeah.

**Comment by j4v** [comment]
Closing, this is implemented in `develop`.
