### ISSUE TITLE
Proposal for new key 'aws_partition' along with 'account_id' in scoutsuite_result for identification of gov-cloud

### ISSUE THREAD

**Issue by rams3sh** [nccgroup/ScoutSuite#510]
Currently scout-suite result has aws account details through following keys :-

```
account_id
environment
```

It would be nice to have a key named partition either as a separate key or under account_id / environment or any place for maintaining a standard across multiple clouds showing which aws partition (aws / aws-us-gov) the current account belongs.

This helps when I am analyzing multiple aws accounts , it becomes easier to segregate all the results of gov clouds separately and normal ones separately for level of analysis to be done for each type.

**Comment by j4v** [comment]
Will do, shouldn't be hard to add.

**Comment by j4v** [comment]
The `partition` field has been added to the `develop` branch. It's a top level field for AWS reports.
