### ISSUE TITLE
Bundle fonts with other resources

### ISSUE THREAD

**Issue by LSwiatek** [nccgroup/ScoutSuite#512]
Consider bundling fonts ("https://fonts.googleapis.com/css?family=Lato:400,700,400italic") with other resources or make it optional and fall back to some other fonts which should always be available

This may be an issue when displaying the report as iframe in jenkins which uses CSP

if for any reason font cannot be loaded, it will stop report from being loaded 
![image](https://user-images.githubusercontent.com/6343173/63584900-323eec80-c59e-11e9-9b0f-17e46ac192c1.png)

**Comment by j4v** [comment]
That stems from a "new" FF security feature which disallows loading local fonts. Not sure there's anything we can do about it.

**Comment by LSwiatek** [comment]
I've bundled the font with the rest of resources, and it loaded just fine on latest firefox

also, if im not mistaken then, scoutsuite.css overwrites the font family anyway and lato is never used
https://github.com/nccgroup/ScoutSuite/blob/7116810c7cb54e905e24d82a7f9610b1ae6932f7/ScoutSuite/output/data/inc-scoutsuite/css/scoutsuite.css#L12

**Comment by j4v** [comment]
> I've bundled the font with the rest of resources, and it loaded just fine on latest firefox

Thanks, I'll look into it.

**Comment by j4v** [comment]
I've been unable to reproduce this locally.

> if im not mistaken then, scoutsuite.css overwrites the font family anyway and lato is never used

That's correct, it's part of a bootstrap theme we're overwriting.

> I've bundled the font with the rest of resources, and it loaded just fine on latest firefox

Care to provide a PR?

**Comment by j4v** [comment]
Fonts are now included as a fallback (see https://github.com/nccgroup/ScoutSuite/pull/529). 

If this issue is not resolved please reopen.
