### ISSUE TITLE
Replace iampoliciesgonewild dependency

### ISSUE THREAD

**Issue by jeffxf** [nccgroup/ScoutSuite#516]
ScoutSuite still uses the module `iampoliciesgonewild` which was put together by Patrick Kelley (previously @monkeysecurity but changed his github handle to @scriptsrc at some point) who works for Netflix. The `iampoliciesgonewild` module was merged into Netflix's [policyuniverse](https://github.com/Netflix-Skunkworks/policyuniverse) package and can be found at https://github.com/Netflix-Skunkworks/policyuniverse/blob/master/policyuniverse/expander_minimizer.py which is a drop in replacement for `iampoliciesgonewild`.

Two reasons for updating are:
1. `iampoliciesgonewild` is no longer maintained.
2. An org that wants to use ScoutSuite but also reviews dependencies will approve ScoutSuite quicker if it uses more reputable and maintained dependencies.

I will have a followup PR to replace the module with `policyuniverse`.

**Comment by j4v** [comment]
Thanks for raising this and providing a fix. Apologies for the delay (I was on leave), have a :cake:!

**Comment by scriptsrc** [comment]
Woohoo!
