### ISSUE TITLE
Managed policy allows iam:PassRole * when the policy/roles are managed by AWS

### ISSUE THREAD

**Issue by rramos1980** [nccgroup/ScoutSuite#518]
Some AWS policies appear under 'Managed policy', these roles/policies cannot be changed.

<img width="1233" alt="Captura de pantalla 2019-09-10 a las 17 33 41" src="https://user-images.githubusercontent.com/5574362/64628333-7e3cbe80-d3f1-11e9-89ef-4e9b0d67cdfa.png">

**Comment by j4v** [comment]
Even though these are AWS Managed Policies, they still present opportunity for abuse (usability != security). Having visibility on which of these is in use is relevant from a security standpoint.
