### ISSUE TITLE
AWS Redshift

### ISSUE THREAD

**Issue by lee5i3** [nccgroup/ScoutSuite#526]
I am getting 2 findings for AWS Redshift, however we don't use Redshift

Findings are:
* User activity logging disabled
* SSL not required

They are coming from the Default parameter group for redshift-1.0, which I am unable to remove in AWS or modify the default parameter group, should they be flagging as a finding or anyway to remove it?

**Comment by j4v** [comment]
That just sounds like a cluster was created at some point and these artefacts remain (which are being flagged). Doesn't look like a Scout issue.
