### ISSUE TITLE
Default policy provided doesnt' work without security_audit role

### ISSUE THREAD

**Issue by munntjlx** [nccgroup/ScoutSuite#528]
Using the 'minimal' security policy fails if you don't include 'security audit' in the role attachments.

**Comment by j4v** [comment]
Can you provide details on the exact errors you're running into? I'm guessing it's just missing a [few] privilege[s].

Also make sure you're running the latest version and not running into https://github.com/nccgroup/ScoutSuite/issues/381.

**Comment by munntjlx** [comment]
I was using a machine role assigned to a single ec2 instance. I used the https://github.com/nccgroup/ScoutSuite/wiki/AWS-Minimal-Privileges-Policy by itself (no other privs) and scoutsuite couln't retrieve any information. I then added the security-audit to the policy, and everything worked.
