### ISSUE TITLE
Incorrect date keyword used in findings

### ISSUE THREAD

**Issue by clanderson0521** [nccgroup/ScoutSuite#531]
In the file rds-postgres-instance-with-invalid-certificate.json

There is a condition that uses DataPriorTo that appears to be incorrect as core/conditions.py does not have any logic to handle this condition.  Seems this should be altered to priorToDate so it gets handled correctly - currently seeing an error about unknown condition.

In ScoutSuite/providers/aws/rules/findings/rds-postgres-instance-with-invalid-certificate.json
`{
    "description": "Invalid SSL certificate (PostgreSQL)",
    "path": "rds.regions.id.vpcs.id.instances.id",
    "dashboard_name": "Instances",
    "conditions": [ "and",
        [ "rds.regions.id.vpcs.id.instances.id.Engine", "equal", "postgres" ],
        [ "rds.regions.id.vpcs.id.instances.id.DBInstanceStatus", "notEqual", "creating" ],
        [ "rds.regions.id.vpcs.id.instances.id.InstanceCreateTime", "DatePriorTo", "08/05/2014" ]
    ],
    "id_suffix": "pgsslcert"
}`

Change the third condition to use priorToDate

**Comment by j4v** [comment]
Thanks, will review ASAP.

**Comment by j4v** [comment]
Should be fixed in `develop` branch, appreciate if you can test.

**Comment by clanderson0521** [comment]
I pulled the develop branch and tested - thanks - passed my test cases.
