### ISSUE TITLE
ScoutSuite Fails To Evaluate All Inline Policies Attached To An IAM Entity

### ISSUE THREAD

**Issue by wstrei** [nccgroup/ScoutSuite#533]
The `_get_and_set_inline_policies` function within `/providers/aws/facade/iam.py` scopes the `policy_name` variable such that `get_policy_method` is called with the same name for every policy attached to the IAM entity. The result is that only one inline policy ever gets fetched and evaluated by ScoutSuite, potentially missing overly-permissive inline policies.

The fix simply requires defining an argument to the lambda function with a default value, as in the following pull request I submitted: https://github.com/nccgroup/ScoutSuite/pull/532#issue-320491419.

Thanks for taking a look at this issue!

**Comment by j4v** [comment]
Thanks for raising and submitting a PR @wstrei, will review ASAP.

**Comment by j4v** [comment]
Thanks @wstrei, your fix has been pushed into `develop`.
