### ISSUE TITLE
New feature w/ PR: Check for RDS certificate authorities being deprecated by Amazon Web Services (i.e. rds-ca-2015)

### ISSUE THREAD

**Issue by scianos** [nccgroup/ScoutSuite#546]
Greetings -

Amazon Web Services is deprecating the RDS Certificate Authority created in 2015 (rds-ca-2015). Any endpoints using TLS to protect RDS communications will fail after March 5th, 2020.

Pull request https://github.com/nccgroup/ScoutSuite/pull/545 has been filed adding a check for RDS instances still utilizing CA identifier rds-ca-2015.

Thanks so much,
Stu

**Comment by j4v** [comment]
Thanks Stu, merged into `develop`.
