### ISSUE TITLE
Wanting to change valid rds backup retention period from 30 days to 10 days

### ISSUE THREAD

**Issue by jdsjr** [nccgroup/ScoutSuite#549]
First of all I've been very impressed by ScoutSuite.  It has helped immensely in running some of my AWS setup issues to ground.

I'm likely missing something but I don't see how to do this through a custom ruleset.  It appears this could be changed by cloning the project and changing the json at a lower level.

What is the right approach to make this "minor" change.

**Comment by j4v** [comment]
You're right that the 30 days are currently hardcoded into https://github.com/nccgroup/ScoutSuite/blob/master/ScoutSuite/providers/aws/rules/findings/rds-instance-short-backup-retention-period.json.

You can either modify that file directly or make it an argument and pass it through a custom ruleset.

Ideally these values would all be passed as arguments through a ruleset.

**Comment by j4v** [comment]
Closing due to lack of feedback, feel free to reopen.
