### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by kreatemore** [nccgroup/ScoutSuite#551]
Hi!

I wanted to experiment with ScoutSuite, and I have created a Dockerfile so I can run it without virtualenv - is this something you might be interested in?

I'll create a PR shortly, and then you can decide if we should pursue this.

On another note, I must say ScoutSuite is quite nice, I'm quite pleased with the generated report!

**Comment by j4v** [comment]
Happy you've found the tool useful @kreatemore.

I don't really see the benefit of leveraging docker to run ScoutSuite, considering it's pretty trivial with virtualenv/pip. Maybe I'm missing something / specific use cases?

**Comment by kreatemore** [comment]
Thanks for the quick reply - I think it might be a highly subjective use-case, I personally prefer working in Docker, rather than having packages installed on my host.

Apart from this - and I'm still exploring this - it might be useful if you want to run this as part of an automated workflow.

The PR stands ready, if you'd like to see it, I'll submit - but if you don't feel the need for this, feel free to close this issue, and I won't create a PR

**Comment by thommor** [comment]
I don’t think it would hurt to have one.

The maintenance and upkeep of a Dockerfile is minimal.

**Comment by j4v** [comment]
> I don’t think it would hurt to have one.

Ok then @kreatemore feel free to submit a PR :smile: 

> I personally prefer working in Docker, rather than having packages installed on my host.

That's why you use virtual environments!!!

**Comment by j4v** [comment]
Thanks for the contribution @kreatemore, this is now merged!
