### ISSUE TITLE
FR: Dynamically pull AWS IP ranges

### ISSUE THREAD

**Issue by aph3rson** [nccgroup/ScoutSuite#554]
There are past issues (e.g. #335 and #336) where the list of AWS IP ranges is called out as out-of-date. At the moment, it hasn't been updated since April.

AWS publishes their most up-to-date IP ranges at https://ip-ranges.amazonaws.com/ip-ranges.json. It might be easier to load the file contents from their website, rather than loading it from a static copy in the repo. Some caching logic might be good here, at least for the duration of the scan, but otherwise it should be minimally impactful on scan duration.

**Comment by j4v** [comment]
Thanks, putting this on the stack - feel free to submit a PR :smile:.

**Comment by klauern** [comment]
So it looks like it's here, which seems pretty deeply nested within a lot of other nesting, so I'm thinking that there will need to be a lot more tests to support it.

https://github.com/nccgroup/ScoutSuite/blob/6cadac7096cb80e5b26d66b219c3e464c9a4faa5/ScoutSuite/core/rule.py#L107-L123

**Comment by j4v** [comment]
@klauern a CI job to pull/update the file would work, just have to get down to implementing it.

**Comment by j4v** [comment]
Closing, this has been included in the release process.
