### ISSUE TITLE
AWS: Subnet names are shown as IDs in subnet output

### ISSUE THREAD

**Issue by aph3rson** [nccgroup/ScoutSuite#556]
When running a report on an AWS account, if subnets are shown which have a `Name` value associated with them, that name is shown in place of the subnet ID (i.e. `subnet-1a2b3c4`). This can cause some confusion when subnets have the same name in multiple accounts.

**Comment by j4v** [comment]
This should now be resolved in `develop` branch: we're showing both the `Name` and `ID` in the resource details. Resource title still defaults to the `Name` if it exists, otherwise `ID`.

Also fixed the `CidrBlockv6` which wasn't displaying correctly.

**Comment by j4v** [comment]
BTW you guys have a great blog, some really good content :100: .

**Comment by aph3rson** [comment]
Awww, shucks... We work very hard on our blog! 

Feel free to shoot me an 📧 if you have any direct questions.
