### ISSUE TITLE
HTML report missing affected resource summary for EBS volumes without encryption

### ISSUE THREAD

**Issue by ashley-cox-ncc** [nccgroup/ScoutSuite#557]
The left side bar is missing if a scout report finds volumes without encryption. This makes enumerating the affected volumes cumbersome. It seems to be fine on everything else. Bug with CSS (attribute set to hidden)

```
 <div id="services.cloudtrail.regions.id.trails.list" style="display:none">
(content redacted)
</div>
```

The style attribute needs to be removed or changed to display:block

**Comment by j4v** [comment]
Thanks @ashley-cox-ncc, this should now be resolved in the `develop` branch.
