### ISSUE TITLE
Lack of ability to run ScoutSuite as a binary

### ISSUE THREAD

**Issue by northdpole** [nccgroup/ScoutSuite#563]
Thank you for ScoutSuite, it's something sorely needed!
I'm trying to use it as part of automated security monitoring infrastructure and to do that I can either build a Dockerfile with scoutsuite baked in it using something like:

`RUN apk add --update -q --no-cache pip3 install -q scoutsuite==5.4.0 && \
    apk del --purge -q build-base libffi-dev libressl-dev python3-dev
`

or,  I can build ScoutSuite as a binary and then I can use it in Docker without needing to add python and thus increasing attack surface and container complexity.

PR: https://github.com/nccgroup/ScoutSuite/pull/562  deals with this by adding a 1-line shell script and a .pex file generated from the script

**Comment by j4v** [comment]
I've decided not to go forward with this because:
1. It adds overhead to our release process
1.1 Only option here I'd see is if it was integrated in the CI/CD process, although not sure how to proceed.
2. It is very easy for users to do themselves

Happy to reopen if anything changes.
