### ISSUE TITLE
Add metadata to AWS API calls to indicate ScoutSuite is making the call

### ISSUE THREAD

**Issue by klauern** [nccgroup/ScoutSuite#567]
It would be nice to be able to indicate in AWS API calls that ScoutSuite is making the calls.  For auditing and tracking cross-region logging of API calls, it should be possible to add some metadata to the user agent in Boto3:

https://stackoverflow.com/a/44049350

Right now, we can track that API calls coming from Boto3 are being made, but it would simplify filtering when running ScoutSuite to be able to find that word in the User Agent field, too:

![Search___Splunk_7_2_5](https://user-images.githubusercontent.com/4735/68492286-e43a9c00-0210-11ea-8229-01a58b32c897.png)

**Comment by j4v** [comment]
Not sure I see the use case here. If you're trying to do auditing, this should be done based on the identity of the principal making the API calls? 

For security purposes, the user agent field is pretty useless since it can be tampered.

**Comment by klauern** [comment]
Well, with the request throttling, it would be useful to know if we're performing a DoS from our own services.  We have had to disable several checks just to get ScoutSuite to complete at all, as SES, EMR are very touchy with the amount of requests it will accept at one time.

**Comment by j4v** [comment]
This seems like an edge case. I'd assume you're using a specific role to run Scout, so you should be able to apply whatever rules you want based on that specific identity/principal - adding a specific user agent check is at best security by obscurity.
