### ISSUE TITLE
AWS - add support for ACM

### ISSUE THREAD

**Issue by ramimac** [nccgroup/ScoutSuite#576]
Consider adding support for auditing ACM. 
[Prowler](https://github.com/toniblyx/prowler) currently has 2 checks:

1. [check724](https://github.com/toniblyx/prowler/blob/master/checks/check_extra724) validates that CT logging has been enabled [see AWS](https://aws.amazon.com/blogs/security/how-to-get-ready-for-certificate-transparency/)

2. [check730](https://github.com/toniblyx/prowler/blob/master/checks/check_extra730) checks for certificates with <7 days to expiry

These are both low-risk issues, but likely merit inclusion and would increase coverage.

**Comment by j4v** [comment]
Closing, this is implemented in `develop`.
