### ISSUE TITLE
Failure to retrieve information protection policies (404 error)

### ISSUE THREAD

**Issue by mfinkel-bf** [nccgroup/ScoutSuite#585]
I am getting data returned for other functions, but there seems to be an error for the Virtual Machines part. Using the Azure GUI, I can access VM details.

**Command Run**
python3 ~/Tools/ScoutSuite/scout.py azure --cli

**Errors**
scout[26803] INFO Fetching resources for the Virtual Machines service
scout[26803] ERROR securitycenter.py L41: Failed to retrieve information protection policies: 404 Client Error: Not Found for url: https://management.azure.com/%2Fsubscriptions%2F{scope}/providers/Microsoft.Security/informationProtectionPolicies?api-version=2017-08-01-preview
scout[26803] ERROR L41: Failed to retrieve information protection policies: 404 Client Error: Not Found for url: https://management.azure.com/%2Fsubscriptions%2F{scope}/providers/Microsoft.Security/informationProtectionPolicies?api-version=2017-08-01-preview

**Comment by j4v** [comment]
Thanks @mfinkel-bf, I believe I've seen this before - will look into it.

You can ignore the message for now as it won't impact the execution results.

**Comment by mfinkel-bf** [comment]
Thanks for the quick response! 

When I check the results, it found no resources for Virtual Machines.

**Comment by j4v** [comment]
> When I check the results, it found no resources for Virtual Machines.

I doubt that's related to the above error. Where any other errors generated? Are you positive there are VMs in the scanned subscription?

**Comment by mfinkel-bf** [comment]
You are correct, the subscriptions in the errors don't have VMs. There were no other errors. The other question would be why VMs in other subscriptions are not showing up as a resource, but that would be a different issue than this one.

If you just have any quick tips where I could print out the subscription IDs ScoutSuite scans, then I can check if subscriptions with VM are being scanned, and can report in a new issue.

**Comment by mfinkel-bf** [comment]
Yep. You are correct. User error. I needed to include a subscription ID with my original command. I had to use --user-account instead of --cli as well. However, still have the same L41 errors as originally put above.

Also I need to figure out why my results file is 186M and I can't open the html file, but that is a different issue.

**Comment by j4v** [comment]
Closing, this should now be fixed in `develop` branch - will be merged ASAP.
