### ISSUE TITLE
UI improvement - Bootstrap version and highlights

### ISSUE THREAD

**Issue by j4v** [nccgroup/ScoutSuite#59]
- Update Bootstrap to 4.1.3 (currently uses 3.0.3)
- Update jQuery to 3.3.1 (currently uses 1.11.2)

Use Bootstrap colors for titles (https://getbootstrap.com/docs/4.0/utilities/colors/). This is especially important as text-on-titles doesn't show very well:
![sc_2018-12-14_15h26m44s](https://user-images.githubusercontent.com/4206926/50008517-b9ba7180-ffb4-11e8-8898-a85966ad7868.jpg)

**Comment by vifor2** [comment]
This is proving to be much longer/tedious than I intended, still WIP.

**Comment by j4v** [comment]
Yep, it may not be as easy as it seems:
- Upgrading BS probably breaks the theme. If it's a valid solution you could swap the themes for pre-made light/dark themes (e.g. https://bootswatch.com/).
- In the current UI architecture, the label's class is used for drawing & logic. This is really messy and shouldn't be the case, so using proper BS success/warning/danger labels will probably involve decoupling these two elements.

**Comment by vifor2** [comment]
Yes Iv'e already upgraded the themes, but haven't applied your second point yet, thank you for the suggestions 👍 .

The main issue with upgrading Bootstrap is that the current classes used for styling either no longer exist, have been renamed or have different properties, therefore it's what I am currently adjusting and it's starting to look more like what it is supposed to look like!

One annoyance that I haven't managed to fix **yet** is the collapsible sub-menu, on the current version on develop it expands towards the bottom of the navbar, while on my version it expands on the right. Still searching for a way to force it to expand towards the bottom without having to change the structure in the .html. 

Before expanding : 
![image](https://user-images.githubusercontent.com/17322874/51548208-e2484d80-1e35-11e9-9a10-201b739a4e9f.png)

After expanding : 
![image](https://user-images.githubusercontent.com/17322874/51548230-ef653c80-1e35-11e9-87cc-ce9d2134373b.png)

**Comment by j4v** [comment]
@vifor2 has the "Bootstrap colors for titles" been implemented, or are you moving this to a separate issue?
