### ISSUE TITLE
how to identify HEADLESS IAM users?

### ISSUE THREAD

**Issue by shivani-singhal** [nccgroup/ScoutSuite#591]
https://github.com/nccgroup/ScoutSuite/blob/master/ScoutSuite/providers/aws/rules/findings/iam-service-user-with-password.json, in this check ScoutSuite takes in an argument that has value "_LIST_(AllHeadlessUsers)” defined in https://github.com/nccgroup/ScoutSuite/blob/master/ScoutSuite/providers/aws/rules/rulesets/detailed.json. 
Can someone please clarify what are HeadlessUsers and how to identify them?

**Comment by j4v** [comment]
A headless user would typically be a user that doesn't have a password setup, and hence can only authenticate through API keys.

That said, I've looked in the codebase for `AllHeadlessUsers` and it isn't defined anywhere, looks like some legacy code which should be removed.

**Comment by shivani-singhal** [comment]
does this mean that the check https://github.com/nccgroup/ScoutSuite/blob/master/ScoutSuite/providers/aws/rules/findings/iam-service-user-with-password.json also mentioned above is not relevant since if the headless users will never have passwords they will by default have no login profile and this check will always fail.

**Comment by j4v** [comment]
Most likely, will have to look into it.

**Comment by jonathanwcrane** [comment]
What you guys are calling "headless" we typically call "Service Accounts."  Meaning, accounts that only do automated tasks against the API as opposed to visit the console via a browser.

**Comment by j4v** [comment]
@jonathanwcrane sure, I guess the question here was how this is being checked/implemented in Scout.

**Comment by j4v** [comment]
Upon review, `AllHeadlessUsers` in https://github.com/nccgroup/ScoutSuite/blob/master/ScoutSuite/providers/aws/rules/rulesets/detailed.json#L636 is an arbitrary group name that you would want to check. Same as `AllHumanUsers` and `AllHeadlessUsers` in https://github.com/nccgroup/ScoutSuite/blob/master/ScoutSuite/providers/aws/rules/rulesets/detailed.json#L663.

You would want to edit the ruleset if the groups in your own AWS accounts had different names.

**Comment by j4v** [comment]
Closing this as it isn't really an issue.
