### ISSUE TITLE
Consider integrating/cleaning up based on LGTM

### ISSUE THREAD

**Issue by ramimac** [nccgroup/ScoutSuite#596]
LGTM has identified a number of easy code-cleanup tasks: https://lgtm.com/projects/g/nccgroup/ScoutSuite/?mode=list

On an ongoing basis, would be nice to take advantage of the 0-cost integration: https://github.com/marketplace/lgtm

**Comment by thommor** [comment]
I’ll take a look into this next week

**Comment by j4v** [comment]
Didn't know of this CI, would be worth integrating it indeed.

**Comment by thommor** [comment]
@j4v You will need to add LGTM to the PR checks as I dont have permission. I'm working on the issues it flagged now

**Comment by j4v** [comment]
@thommor LGTM is now integrated.

**Comment by j4v** [comment]
Closing as this has been done in https://github.com/nccgroup/ScoutSuite/pull/599.
