### ISSUE TITLE
AWS Multi Account using roles

### ISSUE THREAD

**Issue by julian-berks** [nccgroup/ScoutSuite#597]
Converting from Scout2 to ScoutSuite.
with a .aws/config file of 
```
[profile perftest]
role_arn = arn:aws:iam::250xxxxxxxx:role/_Scout2Role
source_profile = default

[default]
region = eu-west-2
```

I am able to run
`scout2 --profile perftest `
and using the access keys the instance gets from its IAM role, scout2 switches to the perftest account, adopts the rights of the _Scout2Role and is able to perform all the checks.

If I try the same with ScoutSuite I get
```
python3 scout.py aws --profile perftest 
ERROR __main__.py L187: Authentication failure: The source profile "default" must have credentials.
```

As the credentials are provided by the instance's role, there are no credentials to put in the profile.

I couldn't find the profile method documented in the wiki - is there a doc on how to get ScoutSuite working cross account without hard coded credentials like Scout2 does?

Thanks.

**Comment by j4v** [comment]
We no longer implement authentications ourselves but rather rely on boto3's implementation.

Looking at https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html#assume-role-provider, I'd think you can do this by using `credential_source` rather then `source_profile`.

Please test this and update the issue.

**Comment by julian-berks** [comment]
Thanks for the quick response.

Per your suggestion, I updated the config to

[profile perftest]
role_arn = arn:aws:iam::25xxxxxxxx:role/_Scout2Role
credential_source = Ec2InstanceMetadata

and it now works a treat.

Thanks for your help.
