### ISSUE TITLE
Incorrect HTML for VPC Network ACLs

### ISSUE THREAD

**Issue by j4v** [nccgroup/ScoutSuite#6]
The id of the subnet as well as that of the instances in that subnet are empty:

![sc_2018-07-27_12h01m33s](https://user-images.githubusercontent.com/4206926/43315069-26f8e008-9195-11e8-93bf-9b3c7037a239.jpg)

**Comment by Aboisier** [comment]
> Similar issue when checking the usage for SGs (e.g. when looking at the `Non-empty rulesets for default security groups` issue):
> 
> ![sc_2018-07-28_18h58m30s](https://user-images.githubusercontent.com/4206926/43358832-4cfaee5a-9298-11e8-8ac5-8248020f444b.jpg)
> 
> A seen above, the counter indicates "12" but there aren't any interfaces in the list.
> 
> Additional occurence:
> Click on Compute>EC2>Security Groups and click on an SG

I moved this to another issue since it does not seem to be related to the original bug.
