### ISSUE TITLE
UI improvement - multiple changes

### ISSUE THREAD

**Issue by j4v** [nccgroup/ScoutSuite#61]
# 1

In the top bar, clicking once opens the menu but there's no way to close it without selecting an option:

![sc_2018-12-18_16h12m43s](https://user-images.githubusercontent.com/4206926/50183344-d5d55000-02df-11e9-8b7c-8a04c815cdfe.jpg)

There should be a way to close this (either a specific button and/or by clicking outside of the menu).

# 2

In the initial view, the run information (last run, datetime, ruleset) are shown at the bottom. This should be moved to an additional tab of the "about" section (top right) and should include some additional info (account ID, scope (account/project), provider, etc.).

# 3 

In the Dashboard section, clicking "+" expands the issue, should then show "-" to collapse:

![sc_2018-12-18_16h04m10s](https://user-images.githubusercontent.com/4206926/50183007-e6d19180-02de-11e9-9185-180c7fe48d2f.jpg)

# 4

In the service issue pages, it's unclear that issue titles are links:

![sc_2018-12-18_16h19m19s](https://user-images.githubusercontent.com/4206926/50183680-c86c9580-02e0-11e9-9b12-2556b0d8bb17.jpg)

Moving the mouse over an issue should underline it (as for the main dashboard), to show it's a link.

# 5
This left sidebar looks a bit heavy

![image](https://user-images.githubusercontent.com/6698529/51765158-0c537700-20a5-11e9-92f5-4aab46db696a.png)

**Comment by j4v** [comment]
Regarding element 3, it would be nice if you could click anywhere on the panel, not only the `+` symbol. Maybe changing the implementation to something like https://getbootstrap.com/docs/4.1/components/collapse/#accordion-example would be better.

**Comment by Aboisier** [comment]
Blocked by #115

**Comment by Aboisier** [comment]
Implemented in #132 .
