### ISSUE TITLE
Improve finding format

### ISSUE THREAD

**Issue by j4v** [nccgroup/ScoutSuite#611]
Current:

```json
{
    "description": "...",
    "rationale": "<b>Description:</b><br><br>...<br><br><b>References:...",
    "dashboard_name": "...",
    "path": "...",
    "display_path": "...",
    "conditions": [ "and", ],
    "id_suffix": "..."
}
```

Desired:

```json
{
    "description": "<title to display in the dashboard>",
    "rationale": "<content of the description>",
    "remediation": "<general steps to remediate the findings>",
    "compliance": [{"name": "CIS Microsoft Azure Foundations", "version": "1.1.0", "reference": "2.1"}, ...],
    "references": ["<URL 1>", "<URL 2>", "<URL 3>"],
    "dashboard_name": "...",
    "path": "...",
    "display_path": "...",
    "conditions": [ "and", ],
    "id_suffix": "..."
}
```

Report:
- [x] Report generation should take care of the formatting. 
- [x] If some fields are blank, report generation should take care of not including them.

Additional tasks:
- [x] Document this better in the wiki
  - [x] Ensure all potential values are described
     - including legacy keys `key` & `args_names` (from rule generator
- [x] Add a format findings tool 
  - [x] Revert `title` to `description`
  - [x] Ensure the order of entries is the same in all finding files
  - [x] check if `_ARG_X_` in description is replaced in other fields (e.g. compliance) (it is)
  - [x] Mention it in the wiki

Progress:
- [x] AWS reformat
- [x] AWS review titles
- [x] Azure reformat
- [x] Azure review titles
- [x] GCP reformat
- [x] GCP review titles
- [x] Aliyun reformat
- [x] Aliyun review titles
- [x] OCI reformat
- [x] OCI review titles

**Comment by j4v** [comment]
Related to https://github.com/nccgroup/ScoutSuite/issues/611.

**Comment by klauern** [comment]
I mentioned this in #651, but for [rulesets](https://github.com/nccgroup/ScoutSuite/wiki/HowTo:-Use-with-a-custom-ruleset), what options are exposed that downstream users can add on to in order to add context for an organization's use of a particular set of rules?

**Comment by j4v** [comment]
> I mentioned this in #651, but for rulesets, what options are exposed that downstream users can add on to in order to add context for an organization's use of a particular set of rules?

Currently none, as that hasn't been taken into account yet. You can only set the criticallity level, as well as specific parameters expected by the rule.

**Comment by j4v** [comment]
Closing, implemented in `develop`.
