### ISSUE TITLE
AWS NLB - Lack of Access log (false positive)

### ISSUE THREAD

**Issue by fabiodouek** [nccgroup/ScoutSuite#617]
Scout is giving a false positive on "Lack of Access Log" for NLB configured without a TLS listener.

It's not possible to configure Access log with the above configuration

As per AWS documentation: https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-access-logs.html

"Access logs are created only if the load balancer has a TLS listener and they contain information only about TLS requests."

**Comment by j4v** [comment]
Thanks, will look into it.

**Comment by j4v** [comment]
This is now fixed in `develop`.
