### ISSUE TITLE
Default rule incorrect for "Short Auditing Retention Period for SQL Databases"

### ISSUE THREAD

**Issue by thomascannon** [nccgroup/ScoutSuite#618]
Azure rule for SQL DB audit retention flags a warning if retention period is less than 90 days (default policy), but a value of zero is "unlimited retention" according to:

https://docs.microsoft.com/en-us/azure/sql-database/sql-database-auditing

Possibly applies to other rules as well.

**Comment by j4v** [comment]
Closing, this is fixed in `develop` branch.
