### ISSUE TITLE
False positive for rule "Azure Active Directory Admin Not Configured for SQL Servers"

### ISSUE THREAD

**Issue by thomascannon** [nccgroup/ScoutSuite#619]
Getting this warning even though AD admin is configured for SQL server

![Screenshot from 2020-01-24 15-54-50](https://user-images.githubusercontent.com/1297160/73082719-e46a3f80-3ec1-11ea-8786-24f7627b3d4d.png)

**Comment by j4v** [comment]
Thanks, will look into it.

**Comment by j4v** [comment]
Thanks for raising this @thomascannon - this is now fixed in the `develop` branch.
