### ISSUE TITLE
False positive - Unused security groups for CodeBuild

### ISSUE THREAD

**Issue by fabiodouek** [nccgroup/ScoutSuite#620]
Scout report false positives regarding security groups associated with CodeBuild.

To reproduce the issue, just associate a security group to a CodeBuild project, and when you run Scout, you will see the Security Group being reported as Unused.

**Comment by j4v** [comment]
Right, by "unused" it means that there aren't any EC2 instances deployed in it. Will have to reevaluate.

**Comment by fabiodouek** [comment]
Thanks @j4v !

**Comment by alessandrogonzalez** [comment]
Code merged into develop branch
