### ISSUE TITLE
Incomplete assessment: "Bucket access logging disabled"

### ISSUE THREAD

**Issue by fabiodouek** [nccgroup/ScoutSuite#622]
Scout reports and issue when Bucket access logging is disabled.
I would recommend for Scout to also check if CloudTrail S3 object logging is enabled. The rule should be if both of them are disabled, do highlight the problem, otherwise is a false positive.

**Comment by j4v** [comment]
Why is it a false positive if the bucket isn't meant to store CloudTrail logs?

**Comment by fabiodouek** [comment]
Hi @j4v , when data event is configured for a S3 bucket, the S3 API operations will log access to the S3 objects to CloudTrail.
CloudTrail will then persist the CloudTrail data in a separate S3 bucket, dedicate for CloudTrail.

What I was trying to say is that the end goal of Bucket access logging (which is to have an access log in a separate bucket logging all access to the bucket data), can be achieved with CloudTrail Data events, and there are advantages in taking this approach.

Therefore, Scout assessment should be on the outcome of either of the two methods available. I have the same issue with AWS Trusted Advisor , which I've raised a ticket for an enhancement request.

**Comment by j4v** [comment]
Yes, I see what you mean. It's a bit hard to implement as this is cross-service but will keep it in the stack.

**Comment by fabiodouek** [comment]
Hi @j4v , I agree with you, it might be hard to implement it.
Perhaps a note in the findings, could help to clarify the warning?

**Comment by ramimac** [comment]
I'll update https://github.com/nccgroup/ScoutSuite/blob/master/ScoutSuite/providers/aws/rules/findings/cloudtrail-no-data-logging.json and https://github.com/nccgroup/ScoutSuite/blob/master/ScoutSuite/providers/aws/rules/findings/s3-bucket-no-logging.json to warn about this

**Comment by ramimac** [comment]
Closing as this is in develop from #786
