### ISSUE TITLE
False positive for AWSCloudFormationStackSetExecutionRole

### ISSUE THREAD

**Issue by fabiodouek** [nccgroup/ScoutSuite#623]
When using CloudFormation Stacksets, a role is used in each account where will be executed. Typically this role is called AWSCloudFormationStackSetExecutionRole.

Scout is reporting "Cross-account AssumeRole policy lacks external ID and MFA". However, the Scout recommended configuration is not an option, as the role is being assumed by another role in the trusted account, which can be assumed by CloudFormation service.

There are other controls which can be put in place, but the MFA recommendation is not an option.

**Comment by j4v** [comment]
You're right, for this finding we should check that the role isn't a "service role".

**Comment by j4v** [comment]
@fabiodouek is the `AWSCloudFormationStackSetExecutionRole` from a separate AWS account?

We tried to reproduce but if it's in the same one it's not getting flagged (as expected), and if it's not it is (expected).

**Comment by fabiodouek** [comment]
Hi @j4v , that's correct. The role AWSCloudFormationStackSetAdministrationRole is on the Master organizations account. For each member AWS account, we have   AWSCloudFormationStackSetExecutionRole with the trusted entity: arn:aws:iam::<MASTER_ORG_ACCOUNT_NUMBER>:role/AWSCloudFormationStackSetAdministrationRole , which locks down the execution to only the master org account, from the AWSCloudFormationStackSetAdministrationRole role.

**Comment by j4v** [comment]
Right, so in that case the rule is working as it should.

As this is a specific scenario, you should use an exception (refer to https://github.com/nccgroup/ScoutSuite/wiki/HowTo:-Create-and-use-a-list-of-exceptions).

Closing this as an FP.
