### ISSUE TITLE
Review top menu options

### ISSUE THREAD

**Issue by j4v** [nccgroup/ScoutSuite#647]
As part of the refactoring:

- [x] The top `Regions` filtering should be removed, as it is AWS-specific.
- The top `Filters` menu should be 
  - [x] Understood, it's not clear what filters do at this point
  - [ ] ~~Potentially removed~~

**Comment by paurisa** [comment]
Just created a pull request for the first item of this issue. #652 
We should discuss what to do with the `Filters` menu before continuing with this enhancement.

**Comment by j4v** [comment]
The only mention of filters is in https://github.com/nccgroup/ScoutSuite/wiki/HowTo:-Create-a-new-rule#type-of-rules. 

Basically they allow filtering resources according to predefined criteria. e.g. there's a filter that's shown when displaying S3 buckets, which allows only showing buckets which have the static website enabled. 

This is currently broken in Scout Suite, and seems partially broken in Scout2. This functionality will be removed as it's legacy, not completely functional and will be available in the new report format when refactored.

**Comment by j4v** [comment]
Fixed the Filter implementation in https://github.com/nccgroup/ScoutSuite/pull/668. Keeping it for now, but will be removed/replaced as part of https://github.com/nccgroup/ScoutSuite/issues/226.
