### ISSUE TITLE
GCP Domain-scoped projects improperly passed to filter

### ISSUE THREAD

**Issue by apleshak** [nccgroup/ScoutSuite#655]
**Description**
(You have already fixed this in https://github.com/nccgroup/G-Scout/blob/master/gscout.py line 58. The comments above that line describe this issue exactly.)

GCP domain-scoped projects (e.g. 'something:something') cannot be scanned due to the filter value (project_id) containing a ':' character. The error returned is: 

`2020-02-25 18:24:52 heap.local scout[96988] ERROR base.py L115: Unable to list accessible Projects: <HttpError 400 when requesting https://cloudresourcemanager.googleapis.com/v1/projects?filter=id%3Asomething%3Asomething&alt=json returned "field [query] has issue [Invalid filter query: resourceType="cloudresourcemanager.projects" AND (projectId = something:something)]">`

(no --debug since it's you are already aware of the root cause)

**To Reproduce**

python3 scout.py gcp --service-account "path" --project-id "something:something"

**Additional context**

Fixed by adding double-quotes around the string format at ScoutSuite/providers/gcp/facade/base.py on line 102 a la:

... list(filter='id:"%s"' % parent_id)

**Comment by j4v** [comment]
Thanks @apleshak, will look into it ASAP.

**Comment by j4v** [comment]
This should now be fixed in the `develop` branch.
