### ISSUE TITLE
Provide a way to manually throttle the amount of API requests to AWS

### ISSUE THREAD

**Issue by joekir** [nccgroup/ScoutSuite#67]
This tool seems to gracefully handle "rate-limit exceeded" responses (https://github.com/nccgroup/opinel/blob/master/opinel/utils/aws.py#L142) 

However Scout exceeding API rate-limits can have an impact on the rest of the assets deployed in an AWS account.

Could we add a flag to manually throttle to a some `n` requests per second?

**Comment by j4v** [comment]
You can use the `--thread-config` option to limit concurrency. Set it to `1` for minimal impact.

**Comment by joekir** [comment]
> You can use the `--thread-config` option to limit concurrency. Set it to `1` for minimal impact.

That is true, though that does not necessarily throttle the client to `n-requests-per-unit-time` does it?
