### ISSUE TITLE
Implement class_suffix attribute for findings

### ISSUE THREAD

**Issue by paurisa** [nccgroup/ScoutSuite#680]
**Is your feature request related to a problem? Please describe.**

Currently there is only implemented the `id_suffix` attribute to highlight specific fields in the HTML report when a finding is being described. However, this attribute only allows one field to be highlighted instead of several fields in a single HTML partial.

**Describe the solution you'd like**

Implement a similar feature to `id_suffix` but for classes.

**Additional context**

For an example of this new attribute, you can check PR #679 
Specifically the finding located here: https://github.com/nccgroup/ScoutSuite/blob/0852793281a5924ae9d985809a7cb3b403280f69/ScoutSuite/providers/aws/rules/findings/iam-unused-credentials-not-disabled.json
And the associated HTML partial located here: https://github.com/nccgroup/ScoutSuite/blob/0852793281a5924ae9d985809a7cb3b403280f69/ScoutSuite/output/data/html/partials/aws/services.iam.credential_reports.html

Also validate this is correctly working for https://github.com/nccgroup/ScoutSuite-Proprietary/pull/173 & https://github.com/nccgroup/ScoutSuite-Proprietary/pull/180.

**Comment by j4v** [comment]
Implemented in `develop` and tested.
