### ISSUE TITLE
AWS credentials report HTML view does not render individual users

### ISSUE THREAD

**Issue by paurisa** [nccgroup/ScoutSuite#682]
**Describe the bug**

The AWS report for the IAM service does not allow to show specific users in the **Credentials Report** section of the results report.

**To Reproduce**

Launch scout with:

`scout.py aws --access-keys --access-key-id X --secret-access-key X -f --services iam`

When the report has been generated, go to the top menu -> Security -> IAM -> Credential reports
The default view shows all the users and there is a sidebar to select only specific users to view. However, if any of the users in the sidebars are selected the page does not render the expected results.

**Comment by j4v** [comment]
Fixed in `develop`. This was due to the ID of resources being the `name`, which had a "." - this breaks the URL / reference. Resolved by generating unique IDs.
