### ISSUE TITLE
Hardcoded AWS Region

### ISSUE THREAD

**Issue by j4v** [nccgroup/ScoutSuite#685]
**Describe the bug**

The implementation of https://github.com/nccgroup/ScoutSuite/blob/master/ScoutSuite/providers/aws/facade/base.py hardcodes the use of the `eu-west-1` region. If this region is disabled, or there are policies which disallow calling endpoints from that region, then Scout will fail.

This has been observed for an account which had policies restricting all API calls **not** made to `us-east-1`.

**To Reproduce**

Set a policy that disallows all calls not made to `us-east-1` and run Scout with a principal that has that policy attached.

**Solution**

- Change default to `us-east-1` as it can't be disabled (https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_enable-regions.html#id_credentials_region-endpoints)
- If this fails and regions are explicitly passed (`--regions`) try with those

**Comment by klauern** [comment]
Related, you could use the API calls for describe regions that shows the OptInStatus: https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-regions.html

That would show which regions are accessible.  It might not catch specific policy limits, but it would get you closer.

**Comment by j4v** [comment]
@klauern that's exactly what we're doing, but you still need to hit a specific region/endpoint to make that call.

**Comment by rommate** [comment]
I got a related issue, I also had to change "/ScoutSuite/providers/aliyun/utils.py" used for S3 ListBuckets operation : 

`diff --git a/ScoutSuite/providers/aliyun/utils.py b/ScoutSuite/providers/aliyun/utils.py
index de8c576a..3106dd6b 100755
--- a/ScoutSuite/providers/aliyun/utils.py
+++ b/ScoutSuite/providers/aliyun/utils.py
@@ -6,7 +6,7 @@ from ScoutSuite.core.console import print_exception
 
 def get_client(credentials, region=None):
     try:
-        client = AcsClient(credential=credentials.credentials, region_id=region if region else 'cn-hangzhou')
+        client = AcsClient(credential=credentials.credentials, region_id=region if region else 'eu-west-3')
         return client
 
     except Exception as e:
diff --git a/ScoutSuite/providers/aws/facade/base.py b/ScoutSuite/providers/aws/facade/base.py
index 5b81f3ad..c98f16b3 100755
--- a/ScoutSuite/providers/aws/facade/base.py
+++ b/ScoutSuite/providers/aws/facade/base.py
@@ -53,7 +53,7 @@ class AWSFacade(AWSBaseFacade):
                                                                                                         partition_name))
 
         # identify regions that are not opted-in
-        ec2_not_opted_in_regions = self.session.client('ec2', 'eu-west-1')\
+        ec2_not_opted_in_regions = self.session.client('ec2', 'eu-west-3')\
             .describe_regions(AllRegions=True, Filters=[{'Name': 'opt-in-status', 'Values': ['not-opted-in']}])
 
         not_opted_in_regions = []`

**Comment by j4v** [comment]
@rommate for aliyun?

**Comment by rommate** [comment]
Yes, I got a case where only **eu-west-3** was allowed : 

```
python3 scout.py aws --services {ec2,elb,elbv2,iam,vpc,s3,route53} --debug --max-workers 1 -r {eu-west-3,eu-central-1}

2020-04-06 14:40:43 HOME.local scout[17055] ERROR s3.py L15: Failed to list buckets: An error occurred (AccessDenied) when calling the ListBuckets operation: Access Denied
Traceback (most recent call last):
  File "/ScoutSuite/ScoutSuite/providers/aws/facade/s3.py", line 15, in get_buckets
    buckets = await run_concurrently(lambda: client.list_buckets()['Buckets'])
  File "/ScoutSuite/ScoutSuite/providers/utils.py", line 24, in run_concurrently
    return await run_function_concurrently(function)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/ScoutSuite/ScoutSuite/providers/aws/facade/s3.py", line 15, in <lambda>
    buckets = await run_concurrently(lambda: client.list_buckets()['Buckets'])
  File "/ScoutSuite/venv/lib/python3.7/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/ScoutSuite/venv/lib/python3.7/site-packages/botocore/client.py", line 626, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the ListBuckets operation: Access Denied
````

**Comment by rommate** [comment]
My bad, this was not the good diff, I had a case were only **eu-west-3** was allowed through Organization SCP, I had to change "/ScoutSuite/providers/aws/facade/base.py" as you mentioned and  "/ScoutSuite/ScoutSuite/providers/utils.py" providing the Client for the s3 facade.

The original error : 
```
# python3 scout.py aws --services {ec2,elb,elbv2,iam,vpc,s3,route53} --debug --max-workers 1 -r {eu-west-3,eu-central-1}
2020-04-06 14:40:43 HOME.local scout[17055] ERROR s3.py L15: Failed to list buckets: An error occurred (AccessDenied) when calling the ListBuckets operation: Access Denied
Traceback (most recent call last):
  File "/ScoutSuite/ScoutSuite/providers/aws/facade/s3.py", line 15, in get_buckets
    buckets = await run_concurrently(lambda: client.list_buckets()['Buckets'])
  File "/ScoutSuite/ScoutSuite/providers/utils.py", line 24, in run_concurrently
    return await run_function_concurrently(function)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/ScoutSuite/ScoutSuite/providers/aws/facade/s3.py", line 15, in <lambda>
    buckets = await run_concurrently(lambda: client.list_buckets()['Buckets'])
  File "/ScoutSuite/venv/lib/python3.7/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/ScoutSuite/venv/lib/python3.7/site-packages/botocore/client.py", line 626, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the ListBuckets operation: Access Denied
```

Which was corrected by the following patch :
```
diff --git a/ScoutSuite/providers/aws/facade/base.py b/ScoutSuite/providers/aws/facade/base.py
index 5b81f3ad..d3047fc5 100755
--- a/ScoutSuite/providers/aws/facade/base.py
+++ b/ScoutSuite/providers/aws/facade/base.py
@@ -44,7 +44,7 @@ class AWSFacade(AWSBaseFacade):
     async def build_region_list(self, service: str, chosen_regions=None, excluded_regions=None, partition_name='aws'):
 
         service = 'ec2containerservice' if service == 'ecs' else service
-        available_services = await run_concurrently(lambda: Session(region_name='eu-west-1').get_available_services())
+        available_services = await run_concurrently(lambda: Session(region_name='eu-west-3').get_available_services())
 
         if service not in available_services:
             raise Exception('Service ' + service + ' is not available.')
@@ -53,7 +53,7 @@ class AWSFacade(AWSBaseFacade):
                                                                                                         partition_name))
 
         # identify regions that are not opted-in
-        ec2_not_opted_in_regions = self.session.client('ec2', 'eu-west-1')\
+        ec2_not_opted_in_regions = self.session.client('ec2', 'eu-west-3')\
             .describe_regions(AllRegions=True, Filters=[{'Name': 'opt-in-status', 'Values': ['not-opted-in']}])
 
         not_opted_in_regions = []
diff --git a/ScoutSuite/providers/aws/facade/utils.py b/ScoutSuite/providers/aws/facade/utils.py
index 3f9e31f4..8f2558aa 100755
--- a/ScoutSuite/providers/aws/facade/utils.py
+++ b/ScoutSuite/providers/aws/facade/utils.py
@@ -78,7 +78,7 @@ class AWSFacadeUtils:
         return resources
 
     @staticmethod
-    def get_client(service: str, session: boto3.session.Session, region: str = None):
+    def get_client(service: str, session: boto3.session.Session, region: str = "eu-west-3"):
         """
         Instantiates an AWS API client
```

Sorry to do not provide you the full patch for dynamic regions selection, but I plan to contribute to ScoutSuite as soon as possible ;)

**Comment by j4v** [comment]
Closing, this should now be resolved in `develop`. See https://github.com/nccgroup/ScoutSuite/pull/705 for new logic.
