### ISSUE TITLE
Implement checks for AWS ELBv2 drop_invalid_header_fields attribute

### ISSUE THREAD

**Issue by AndreyRainchik** [nccgroup/ScoutSuite#686]
**Is your feature request related to a problem? Please describe.**

The AWS ALB routing.http.drop_invalid_header_fields.enabled attribute was introduced to [indicate whether HTTP headers with invalid header fields are removed by the load balancer (true) or routed to targets](https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_LoadBalancerAttribute.html). Leaving the attribute as its default `false` [may open up](https://medium.com/@emilefugulin/http-desync-attacks-with-python-and-aws-1ba07d2c860f) a vulnerable backend server to request smuggling attacks.

**Describe the solution you'd like**

Include a check for the drop_invalid_header_fields attribute. This can be achieved by calling the ELBv2 [describe-load-balancer-attributes](https://docs.aws.amazon.com/cli/latest/reference/elbv2/describe-load-balancer-attributes.html) and checking the value for the `routing.http.drop_invalid_header_fields.enabled` key.

**Describe alternatives you've considered**

Alternative features could include checking whether a load balancer is an Application Load Balancer, as the attribute is only present on ALBs.

**Additional context**

```
> python3
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import boto3
>>> client = boto3.client('elbv2')
>>> client.describe_load_balancer_attributes(LoadBalancerArn='arn:aws:elasticloadbalancing:us-east-1:[REDACTED]:loadbalancer/app/[REDACTED]')
{'Attributes': [[TRUNCATED] {'Key': 'routing.http.drop_invalid_header_fields.enabled', 'Value': 'false'}], 'ResponseMetadata': [TRUNCATED]}
```

**Comment by j4v** [comment]
If you're going to write such a precise issue we might as well implement it :medal_military:

**Comment by ramimac** [comment]
Closing, as this is merged into develop!
