### ISSUE TITLE
Improve README sexyness

### ISSUE THREAD

**Issue by j4v** [nccgroup/ScoutSuite#688]
Would be good to make the landing page more attractive. The main improvement I'd see is an embedded GIF that displays running a job and viewing a report.

Add README to tools folder.

**Comment by ramimac** [comment]
Happy to get a GIF together:
1. Record the terminal running a job
2. Navigate the report
2a. Go into a service
2b. Expand the description for a finding
2c. Got into a finding and show details

Any other features you'd want expressed?

**Comment by ramimac** [comment]
I'd also recommend adding the PyPI download badge https://img.shields.io/pypi/dm/scoutsuite

**Comment by ramimac** [comment]
Threw together quick terminal gifs, one for installation (from pip) and one for running scoutsuite on aws

asciinema -> ttygif -> gifsicle (for improving the delay, cutting a couple long frames)

![scoutsuite_installation](https://user-images.githubusercontent.com/13310971/77860292-718c8600-71dc-11ea-96d6-cb6bdac54eea.gif)
![scoutsuite_running](https://user-images.githubusercontent.com/13310971/77860294-72bdb300-71dc-11ea-9200-c5f55ce7fd59.gif)

**Comment by ramimac** [comment]
And a quick screencast, using https://ramimac.github.io/sadcloud-reports/scoutsuite-reports/scoutsuite-report_03_2020/aws.html

![screencast](https://user-images.githubusercontent.com/13310971/77861662-342bf680-71e4-11ea-8eed-ccaeb78c5f45.gif)

**Comment by j4v** [comment]
Brilliant @ramimac, will include all of the above in the README / wiki.

For the sadcloud screencast I'll include a ref to the project.

**Comment by j4v** [comment]
Closing as all the above is done.

@ramimac is it possible to make the CLI gifs a bit shorter (cut the vertical space a bit)?

**Comment by ramimac** [comment]
![small_scout_install](https://user-images.githubusercontent.com/13310971/78389081-209bd980-75b0-11ea-9a17-dc75c639db2a.gif)
![small_scout_use_delayed](https://user-images.githubusercontent.com/13310971/78389085-22659d00-75b0-11ea-9f22-ea6fcaa6a1cd.gif)

**Comment by j4v** [comment]
Cheers @ramimac, updated both gifs.
