### ISSUE TITLE
How to run this in AWS Lambda?

### ISSUE THREAD

**Issue by nikhilkumarbol** [nccgroup/ScoutSuite#690]
I want to upload this tool as a zip file to AWS Lambda and want to invoke this periodically using CRON expressions and store the reports in S3. How do I go about this? Is there any other way without Lambda that achieves this?

**Comment by rracterr** [comment]
The problems with doing what you describe are myriad... you would be much better served using AWS batch instead of Lambda.

**Comment by nikhilkumarbol** [comment]
Thanks I'll definitely try this out, but will this run for sure? And would it generate the report files and where?

**Comment by j4v** [comment]
Closing as this is outside of the scope of this project.

**Comment by klauern** [comment]
We have this set up for ourselves, but haven't done anything to get it published or merged upstream as part of the open source project.  We probably should do some work on this, but we haven't prioritized anything ScoutSuite related until later this year.
