### ISSUE TITLE
Dark theme broken on latest Chrome

### ISSUE THREAD

**Issue by j4v** [nccgroup/ScoutSuite#706]
The black theme no longer works on Chrome, the browser complains that:
```
Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
```

This is likely the case because the report is a static/local file.

**Comment by vmncc** [comment]
Is this still an issue? Seems to work fine on latest chrome (Version 83.0.4103.61). Is this referring to a plugin that enables black theme, or system defaults?

**Comment by j4v** [comment]
> Is this referring to a plugin that enables black theme

This refers to the "Dark theme" option in the top right menu.

Still seeing this, albeit on chromium `Version 80.0.3987.162 (Developer Build)`.

**Comment by j4v** [comment]
This no longer happens and couldn't be reproduced for other browsers, closing issue.
