### ISSUE TITLE
ProxyError nodename nor servname provided, or not known

### ISSUE THREAD

**Issue by aus** [nccgroup/ScoutSuite#719]
This is probably not a ScoutSuite bug, but rather a bug with one of its dependencies or my environment. I'm just posting here in case someone else runs into the same thing.

During a run against a large Azure environment, Scout will start spewing the following error at a seemingly random point in the run:

```
ProxyError(MaxRetryError("HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/REDACTED/providers/Microsoft.Security/regulatoryComplianceStandards?api-version=2019-01-01-preview (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10b29dc90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')))"))
```

The error seems to indicate that the DNS lookup for the proxy has failed, however previous requests to the proxy in the same run worked fine. It just randomly fails requests. I also don't see the alleged failing DNS request/response in Wireshark.

After a lot of debugging, I never got to the bottom of the issue. I suspect this had to do something with my environment of:

- MacOS
- Python 3.7.4
- Corporate VPN
- Corporate HTTP proxy with intercepting SSL

I ran the same Scout command on Linux and did not encounter this issue. The Linux machine still required the same corporate HTTP proxy, but was on-prem.

**Comment by j4v** [comment]
Is this reproducible?

The only non-network reference I've found mentioned that it was due to the # of open files in the system. Could you try to increase with `ulimit -Sn 1000` (see https://github.com/nccgroup/ScoutSuite/issues/443) and see if that solves the issue?

**Comment by aus** [comment]
Good call! I was hitting the open files ulimit on MacOS. On Linux, I had the same problem but a different error message. I didn't correlate the two. The Linux error was much more descriptive. Something like `Too many files open`, which was pretty straight forward to fix. Thanks!

**Comment by j4v** [comment]
Do you know if this was due to a specific Azure service?

**Comment by aus** [comment]
Sorry for the delay response. I think this was mostly addressed in #698. Will test.

**Comment by gabedwrds** [comment]
I think I just hit the same error myself, about 2/3 of the way through processing an AWS account. It looks like it started failing around the KMS stage on one run but continued failing through other services. `ulimit -Sn 1000` did resolve it for me as well (default was 256).

For what it's worth, I'm running Scout Suite 5.8.1 on macOS 10.14.6, also on corporate VPN but no proxy that I'm aware of.

**Comment by j4v** [comment]
I'm not seeing anything in this thread that we can really fix. Does look more like a network/local issue than anything else.

**Comment by andresvia** [comment]
I stumbled across this. maybe a note can be added to wiki?

https://github.com/nccgroup/ScoutSuite/wiki#basic-usage
