### ISSUE TITLE
Review "Global Services Logging Disabled" rule definition

### ISSUE THREAD

**Issue by alessandrogonzalez** [nccgroup/ScoutSuite#722]
The current "Global Services Logging Disabled" rule is being triggered for some trails even though there are other trails in the same account with global services logging enabled.

**To Reproduce**

My testing account has two active trails that log global services, and one that should log global services, but it is disabled. In this case, the report contains the "Global Services Logging Disabled" issue, highlighting the disabled trail.

**Comment by j4v** [comment]
Closing, this is fixed in `develop`.
