### ISSUE TITLE
Docker wiki has no details for OS X

### ISSUE THREAD

**Issue by dflatow** [nccgroup/ScoutSuite#723]
There's not a lot of documentation on the [docker wiki page](https://github.com/nccgroup/ScoutSuite/wiki/Docker-Image).

It only lists a single command:
```
docker run --rm -t \
-v /home/<user>/.aws:/root/.aws:ro \
-v "$(pwd)/results:/opt/scoutsuite-report" \
scoutsuite:latest \
aws
```

This command doesn't work on OS X and should be changed to:
```
docker run --rm -t \
-v ~/.aws:/root/.aws:ro \
-v "$(pwd)/results:/opt/scoutsuite-report" \
scoutsuite:latest \
aws
```

In addition I think this page would benefit from some more explanations. Also would be nice to list how to use the Docker file in the Readme.md

Thanks!

**Comment by j4v** [comment]
> This command doesn't work on OS X and should be changed to:

Thanks, will look into it.

> In addition I think this page would benefit from some more explanations. 

Such as?

> Also would be nice to list how to use the Docker file in the Readme.md

The readme is intentionally kept light, with most of the information being kept in the wiki.

**Comment by dflatow** [comment]
@j4v Some additional documentation around, for example: 

- the fact that the docker html report will be written to `$(pwd)/results`. Also I don't think the report is automatically opened...

- which user the aws CLI tool should be configured for. I'm assuming not the root account, but should a temporary IAM user be created and configured in the aws CLI tool?

**Comment by j4v** [comment]
> Also I don't think the report is automatically opened...

I don't think that's possible if you're running it in a container? 

> which user the aws CLI tool should be configured for. I'm assuming not the root account, but should a temporary IAM user be created and configured in the aws CLI tool?

That's really up to the user to decide.

**Comment by j4v** [comment]
Closing, no further work planned on our part. Feel free to submit a PR if you feel the project would benefit from something in this space.

**Comment by dflatow** [comment]
Awesome thanks :)

**Comment by j4v** [comment]
@dflatow forgot to mention I also updated the wiki with your linux & osx compatible command.
