### ISSUE TITLE
[GCP][KMS] 'KeyError: primary' when try fetch all cryptoKeys

### ISSUE THREAD

**Issue by vjviana** [nccgroup/ScoutSuite#730]
**Description**

When running ScoutSuite on the GCP platform, the step `Fetching resources for the KMS service` is returning the following exception **'_KeyError: primary_'**. After analyzing the code, I identified that the application is not prepared for the scenario where the status of the keys is not available, that is, the registry does not have a primary key version enabled.

![image](https://user-images.githubusercontent.com/38796462/80553718-3b8c1e80-89a1-11ea-8f8b-bb65a42cb127.png)

**To Reproduce**
- Create a Cryptographic key, without primary key enabled;

![image](https://user-images.githubusercontent.com/38796462/80553961-12b85900-89a2-11ea-83d9-6575efabcb27.png)
![image](https://user-images.githubusercontent.com/38796462/80554095-70e53c00-89a2-11ea-8bb4-24eb296096e6.png)
- Run ScoutSuite with this command: `scoutsuite gcp --service-account ./key/key.json --debug`;

**Additional Information**
- Part of the code that raises an exception;

![image](https://user-images.githubusercontent.com/38796462/80554583-0c2ae100-89a4-11ea-99e5-722a1a30fd82.png)

- Suggestion for a solution would be to add validation before trying to access the 'primary' property;

![image](https://user-images.githubusercontent.com/38796462/80554713-69269700-89a4-11ea-9594-df78fab45b3a.png)

**Comment by j4v** [comment]
Thanks @vjviana, will fix ASAP.

**Comment by vjviana** [comment]
You're welcome @j4v !!

**Comment by j4v** [comment]
@vjviana I've pushed your proposed fix to the `develop` branch, could you please test this resolves your issue?
