### ISSUE TITLE
Message: Regulatory compliance is not supported for subscription <redacted> as it has no standard pricing bundle 2020-05-13 18:34:54 ScoutSuite scout[115998] ERROR securitycenter.py L95: Failed to retrieve regulatory compliance standards: Azure Error: Subscription with no standard pricing bundle

### ISSUE THREAD

**Issue by munntjlx** [nccgroup/ScoutSuite#739]
**Describe the bug**

Please provide:

- ScoutSuite running with the following cli options:
 ./scout.py azure --all-subscriptions --tenant <redacted> --service-principal --client-id <redacted> --client-secret <redacted>
**To Reproduce**
```
 ./scout.py azure --all-subscriptions --tenant <redacted> --service-principal --client-id <redacted> --client-secret <redacted>
```
Running on debian 10.4 on azure, running from master branch.

**Comment by j4v** [comment]
I've seen this error a number of times, I don't think it's a bug though. You'll get that if you scan the Security Center service for a subscription that doesn't have the "with no standard pricing bundle".

**Comment by j4v** [comment]
Closing, this is not a bug.

**Comment by j4v** [comment]
Made this a debug message instead of an error since it fits better with the library output.
