### ISSUE TITLE
--user-account-browser authentication for Azure does not refresh after one hour

### ISSUE THREAD

**Issue by aus** [nccgroup/ScoutSuite#740]
**Describe the bug**

In long runs of scout, the authentication can expire and does not refresh. This only seems to apply to `--user-account-browser` authentication. The `--cli` authentication does not encounter this problem.  After exactly an hour, the following error is produced:

```
ERROR appservice.py L46: Failed to retrieve web app auth settings: (AuthorizationFailed) The client 'REDACTED' with object id 'REDACTED' does not have authorization to perform action 'Microsoft.Web/sites/config/list/action' over scope '/subscriptions/REDACTED/resourceGroups/REDACTED/providers/Microsoft.Web/sites/REDACTED/config/authsettings' or the scope is invalid. If access was recently granted, please refresh your credentials.
```
(This can happen on any service.)

**To Reproduce**

Run the following on a large Azure environment (so that it takes longer than an hour). I was using `--all-subscriptions` to make this a long run (probably not required if you can introduce delay in another way).

```
python scout.py azure --user-account-browser --all-subscriptions --tenant REDACTED
```

**Comment by j4v** [comment]
Thanks, I'd think there's a way for us to refresh the token, will look into it.

**Comment by j4v** [comment]
@aus I've implemented the token refresh for browser authentication (see https://github.com/nccgroup/ScoutSuite/pull/747). Could you please test by running the enhancement/azure-browser-auth-token-refresh branch?
