### ISSUE TITLE
False positive - "Bucket without logging enabled"

### ISSUE THREAD

**Issue by sivakums** [nccgroup/ScoutSuite#741]
In GCP, the access logs and data read/write logs are enabled for all the GCS buckets. But in the scout suite report, it shows as "Bucket without logging enabled".

**Comment by j4v** [comment]
Thanks, will look into it.

**Comment by j4v** [comment]
The check is fairly simple (https://github.com/nccgroup/ScoutSuite/blob/master/ScoutSuite/providers/gcp/resources/cloudstorage/buckets.py#L27), any way you can check this value at runtime?

**Comment by sivakums** [comment]
Hi Xavier

Yes, I checked this value for one of the buckets, the value was "None". I
will analyze more on the gsutil to understand what do they mean bucket
logging.

Regards
Sivakumar S

**Comment by j4v** [comment]
The command to check is:

```sh
$ gsutil logging get gs:// [bucketname]
```

Refer to https://cloud.google.com/storage/docs/access-logs.

Closing this now.
