### ISSUE TITLE
Facing issues while setting up Scoutsuite

### ISSUE THREAD

**Issue by ashishgavali10** [nccgroup/ScoutSuite#746]
Hi Team,

I'm Facing issues while setting up the ScoutSuite.
1. While installing with PIP I'm getting below error

ERROR: Could not find a version that satisfies the requirement scoutsuit (from versions: none)
ERROR: No matching distribution found for scoutsuit 

![Screen Shot 05-18-20 at 04 09 PM](https://user-images.githubusercontent.com/30225239/82204266-38da7480-9922-11ea-9967-b6db1688cf2a.PNG)

2. While installing with Git getting following issue.
 
ERROR: Command errored out with exit status 1:
     command: /tmp/build/45596e3a/ScoutSuite/venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-y0goeczu/policyuniverse/setup.py'"'"'; __file__='"'"'/tmp/pip-install-y0goeczu/policyuniverse/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-9d5n8szp
         cwd: /tmp/pip-install-y0goeczu/policyuniverse/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-y0goeczu/policyuniverse/setup.py", line 16, in <module>
        long_description=open(os.path.join(ROOT, "README.md")).read(),
      File "/usr/local/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xf0 in position 1008: ordinal not in range(128)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
25hERROR: Could not find a version that satisfies the requirement scoutsuit (from versions: none)
ERROR: No matching distribution found for scoutsuit

![Screen Shot 05-18-20 at 04 08 PM](https://user-images.githubusercontent.com/30225239/82204298-4263dc80-9922-11ea-9231-3655c055587a.PNG)

Attaching Screenshot for the reference, can you please help me to resolve this issues.

**Comment by j4v** [comment]
> ERROR: No matching distribution found for scoutsuit

That's a typo - scoutsuit**e**``

**Comment by ashishgavali10** [comment]
Hi j4v,

I corrected that typo, I'm still getting below error.

![Screen Shot 05-18-20 at 04 08 PM](https://user-images.githubusercontent.com/30225239/82215102-7516d080-9934-11ea-8f72-8a0cec27a42c.PNG)
.

**Comment by j4v** [comment]
There's still a typo in that screenshot though.

The unicode issue I've seen before and it's a local issue. Recreating the virtualenv should resolve.

Closing as I'm not seeing anything that indicates this is an issue with the project.
