### ISSUE TITLE
Link to Setup instructions from the main page

### ISSUE THREAD

**Issue by chris-armstrong** [nccgroup/ScoutSuite#750]
Clearly a lot of good work has gone into this project, but it's actually difficult to find the install link. I managed to find the wiki link casually referenced at the bottom of the README (the main thing shown on the github page), and then a link in the sidebar.

https://github.com/nccgroup/ScoutSuite/wiki/Setup should be linked in the README under a 'Installation' or 'Getting Started' heading.

**Comment by j4v** [comment]
Thanks for the input @chris-armstrong. How does https://github.com/nccgroup/ScoutSuite/tree/develop look?

**Comment by chris-armstrong** [comment]
Excellent!
