### ISSUE TITLE
ScoutSuite flags storage account incorrectly when 3 exceptions allowed

### ISSUE THREAD

**Issue by Dziubey** [nccgroup/ScoutSuite#763]
**Description**
When running ScoutSuite against our Azure infrastructure, an incorrect flag is given for the Trusted Microsoft Services Enabled rule for storage accounts.

We allow all 3 exceptions for our Azure storage accounts, as presented below:
1. Allow trusted Microsoft services to access this storage account
2. Allow read access to storage account loggin from any network
3. Allow read access to storage metrics from any network
![esceptions](https://user-images.githubusercontent.com/22967770/83386206-83f48d00-a3e2-11ea-8ee9-f1ebfee18dce.PNG)

However, ScoutSuite flags the storage account and says that the Trusted Microsoft Services are disabled.
![report](https://user-images.githubusercontent.com/22967770/83386441-00876b80-a3e3-11ea-9104-e2485127b50b.PNG)

**To Reproduce**

1. Create Azure storage account
2. Go to storage account -> Firewalls and virtual networks
3. Allow all three exceptions
4. Run ScoutSuite for the subscription where storage account has been deployed

The following CLI parameters have been used:
1. Azure
2. Subscription
3. Service-principal
4. Tenant
5. Client-id
6. Client-secret
7. Skip-aad

The full command executed to generate report:
python3 scout.py azure --subscription xxxx  --service-principal --tenant xxxx --client-id xxxx --client-secret xxxx --skip aad

**Additional context**

ScoutSuite version 5.8.1 has been used.
We use default rules and conditions.

**Comment by j4v** [comment]
Thank you @Dziubey, we'll look into it.

**Comment by ramimac** [comment]
@Dziubey Any chance you're able to run `az storage account show --name NAME --query 'networkRuleSet.bypass'`? This is the query primarily backing this findings, so it'll make debugging easier. 

Further background: for now we are checking if it is equal to `"AzureServices"` to pass the check. I'm not the Azure guy so it may be we need to broaden this check

**Comment by ramimac** [comment]
Awesome! Super helpful, I'll go get this rule refined.

**Comment by j4v** [comment]
Closing, fixed in `develop`.
