### ISSUE TITLE
Can we call methods of one resource in another resource?

### ISSUE THREAD

**Issue by Deepali-Potdar** [nccgroup/ScoutSuite#764]
Hello Team

I have added cloudwatch get_metric_statistics api in cloudwatch facade. API is as below:
get_metric_data_details = await run_concurrently(lambda: cloudwatch_client.get_metric_statistics(
                MetricName='DatabaseConnections',
                Dimensions=[
                    {
                        'Name': 'DBInstanceIdentifier',
                        'Value': database_name
                    },
                ],
                StartTime=start_time,
                EndTime=end_time,
                Period=3600,
                Statistics=[
                    'Average',
                ],
                Namespace='AWS/RDS',
                Unit= 'Count'
                )
            )

If I will put database_name as hard coded then this API works for single database and I am getting the response of this API. But I wanted to keep this database_name as dynamic. So can I call database names from the RDS instances.py in above mentioned API?

**Comment by j4v** [comment]
I don't understand the question. Please refer to https://github.com/nccgroup/ScoutSuite/wiki/Implementing-support-for-a-new-service#introduction for instructions on fetching AWS resources.

**Comment by Deepali-Potdar** [comment]
I am trying to develop below rule of AWS trusted advisor:
Amazon RDS Idle DB Instances
Checks the configuration of your Amazon Relational Database Service (Amazon RDS) for any DB instances that appear to be idle. If a DB instance has not had a connection for a prolonged period of time, you can delete the instance to reduce costs. If persistent storage is needed for data on the instance, you can use lower-cost options such as taking and retaining a DB snapshot. Manually created DB snapshots are retained until you delete them. Data for Amazon RDS instances created in the Asia Pacific (Seoul) region (sa-east-1) is not available. We are working to fix this issue as soon as possible.

Alert Criteria
Yellow: An active DB instance has not had a connection in the last 7 days.

Please let me know can I develop this rule in ScoutSuite?

**Comment by Deepali-Potdar** [comment]
Please could you refer below link:
https://www.cloudconformity.com/knowledge-base/aws/RDS/idle-instance.html#:~:text=Idle%20RDS%20Instance,your%20compliance%20level%20for%20free!&text=Identify%20any%20Amazon%20RDS%20database,of%20your%20monthly%20AWS%20bill.

Above link provides idea to develop the above mentioned rule.

**Comment by j4v** [comment]
Your question is very general, please refer to the wiki or look at the existing source code.

Generally speaking, as this service exists you'll need to:
- Add a method in https://github.com/nccgroup/ScoutSuite/blob/master/ScoutSuite/providers/aws/facade/cloudwatch.py to pull the info you're interested in.
- Add a resource in https://github.com/nccgroup/ScoutSuite/tree/master/ScoutSuite/providers/aws/resources/cloudwatch , call the facade method above and parse the result
- Create an HTML partial in https://github.com/nccgroup/ScoutSuite/tree/master/ScoutSuite/output/data/html/partials/aws to display the report
- Add the resource to https://github.com/nccgroup/ScoutSuite/blob/master/ScoutSuite/providers/aws/metadata.json so it gets displayed in the report
- Write your rule to https://github.com/nccgroup/ScoutSuite/tree/master/ScoutSuite/providers/aws/rules/findings and add it to the default ruleset (https://github.com/nccgroup/ScoutSuite/blob/master/ScoutSuite/providers/aws/rules/rulesets/default.json)

The https://github.com/nccgroup/ScoutSuite/wiki/Tools#process_raw_responsepy tool may also help you with some of the above.

**Comment by Deepali-Potdar** [comment]
Thanks for your reply. I will go through the above mentioned links.
