### ISSUE TITLE
GKE Coverage

### ISSUE THREAD

**Issue by sean-ersw** [nccgroup/ScoutSuite#769]
**Describe the bug**

- Given that there is a "Compute > Kubernetes engine" menu in the report and even a dashboard, I wonder why there is no findings for the GKE Cluster in the project? Is it just not implemented yet? Roles required for the Service Account that aren't documented? Or something else?

**To Reproduce**

- ScoutSuite/bin/scout gcp --service-account sa.json --project-id "$PROD_PROJECT_ID" --no-browser --report-dir "$CI_PROJECT_DIR/report"

**Additional context**

**Comment by j4v** [comment]
GKE is implemented and available via our SaaS offering (https://cyberstore.nccgroup.com/our-services/service-details/16/scout:-public-cloud-account-monitoring).

We will be releasing support for this service as part of the open source project in the near future.
