### ISSUE TITLE
Scoutsuite returns ScoutSuite asyncio[44839] ERROR Task exception was never retrieved future: ... #744

### ISSUE THREAD

**Issue by pablogarcialandeira** [nccgroup/ScoutSuite#772]
This thread was closed and resolved but The error has not been fixed dumps the same error if launched under csv file credentials with the command scout.py --csv-credentials. File.csv, though ultimately if you give the scanner result

**Comment by j4v** [comment]
Closing as this is potentially a duplicate. Please provide comments in https://github.com/nccgroup/ScoutSuite/issues/744#issuecomment-639525770, I'll reopen if we confirm this bug is still open.
