### ISSUE TITLE
Switch to pytest from nosetests

### ISSUE THREAD

**Issue by klauern** [nccgroup/ScoutSuite#776]
**Is your feature request related to a problem? Please describe.**

The Travis configuration doesn't specify installing `nose`(unmaintained) or `nose2` (forked) as a dependency to running tests, and nose itself doesn't have as much of a following or plugin infrastructure that pytest does.

**Describe the solution you'd like**

I would like tests to be run through `pytest` with the potential inclusion of some plugins related to parallelizing or simplifying how tests could be run:
* https://github.com/okken/pytest-check - allowing multiple failures to be collected per unittest
* https://pypi.org/project/pytest-xdist/ - parallelization and multi-platform testing

**Describe alternatives you've considered**

Nose is currently running, and I would *assume* nose2 is what is being used, but honestly it isn't specified anywhere, and isn't clear to me which to install.

**Additional context**

My thought on the idea is that if making the choice between upgrading to nose2 and pytest, pytest should be migrated over.  It doesn't look like a large change overall, and would have an added benefit of letting users install additional plugins for their own use-cases:

* https://github.com/Teemu/pytest-sugar - better output
* https://pypi.org/project/pytest-instafail/ - insta-fail
* https://github.com/anapaulagomes/pytest-picked - only run tests on changed files.

**Comment by j4v** [comment]
@klauern we're using `nose` (https://nose.readthedocs.io/en/latest/). 

Unit tests is definitely something we need to improve on, and I welcome a switch to `pytest`.

**Comment by j4v** [comment]
@klauern are you satisfied with the change in `develop` / can we close this?

**Comment by klauern** [comment]
Oh, for sure.
