### ISSUE TITLE
DEV branch, tools/aws_security_hub_export.py ImportError: attempted relative import with no known parent package

### ISSUE THREAD

**Issue by munntjlx** [nccgroup/ScoutSuite#778]
When running the new tool, I get the following error (in ScoutSuite directory when I run)

python tools/aws_security_hub_export.py -h 

```
Traceback (most recent call last):
  File "tools/aws_security_hub_export.py", line 3, in <module>
    from .utils import results_file_to_dict
ImportError: attempted relative import with no known parent package
```

**To Reproduce**

Please provide:

python tools/aws_security_hub_export.py -h

I was running in develop branch, and using python 3.7 with a virtualenv on mac (catalina os)

**Comment by j4v** [comment]
Thanks for raising @munntjlx, this should now be fixed.
