### ISSUE TITLE
False Positive in condition "containAtLeastOneMatching"

### ISSUE THREAD

**Issue by j4v** [nccgroup/ScoutSuite#781]
**Describe the bug**

The following rules:
- https://github.com/nccgroup/ScoutSuite/blob/develop/ScoutSuite/providers/aws/rules/findings/iam-inline-policy-for-role.json
- https://github.com/nccgroup/ScoutSuite/blob/develop/ScoutSuite/providers/aws/rules/findings/iam-managed-policy-for-role.json

Make use of the following condition:

```json
[
    "iam.policies.id.PolicyDocument.Statement.id.Resource",
    "containAtLeastOneMatching",
    ".*[*].*"
]
```

This regex isn't very precise, and flags statements such as:

```json
{
  "Action": [
    "iam:GetRole",
    "iam:PassRole",
  ],
  "Effect": "Allow",
  "Resource": [
    "arn:aws:iam::*:role/aws-service-role/config.amazonaws.com/*"
  ]
}
```

**Comment by alessandrogonzalez** [comment]
I think we should define what should be highlighted with this rule. Before, it highlighted all occurrences where Resource = '*', now, all occurrences where Resource contains a '*', so both approaches could have their advantages and disadvantages.

Should your example be flagged?

**Comment by j4v** [comment]
Closing, this is addressed in `develop`.
