### ISSUE TITLE
test_utils_sns and cloudwatch won't work

### ISSUE THREAD

**Issue by klauern** [nccgroup/ScoutSuite#782]
**Describe the bug**

In looking at the tests for ScoutSuite, it appears that neither https://github.com/nccgroup/ScoutSuite/blob/master/tests/test-utils_cloudwatch.py nor https://github.com/nccgroup/ScoutSuite/blob/master/tests/test-utils_sns.py will work out of the box.  In fact, they import utility functions from core that aren't there.

If this is part of the proprietary tool, these tests should be moved out of this repository, but if not, there's some source code missing that needs to be added back in.

**To Reproduce**

```
nosetests --with-coverage tests/test_utils_cloudwatch.py
nosetests --with-coverage tests/test_utils_sns.py
```

**Additional context**

In trying to add more tests to this suite, all tests should be passing, and those that aren't should be removed for the benefit of contributors to add in the gaps where possible.

**Comment by j4v** [comment]
These are legacy tests from https://github.com/nccgroup/Scout2, which likely where never fully functional (hence why they aren't included in the travis configuration).

What's not working can likely be removed, as they haven't been touched in years.

**Comment by j4v** [comment]
Closing, @JJmako has taken care of this.
