### ISSUE TITLE
sqlite output is broken

### ISSUE THREAD

**Issue by klauern** [nccgroup/ScoutSuite#788]
**Describe the bug**

When I run ScoutSuite with the output format as `-sqlite`, it creates a database that isn't actually parseable:

```
sqlite> .tables
unnamed
sqlite> .schema unnamed
CREATE TABLE IF NOT EXISTS "unnamed" (key TEXT PRIMARY KEY, value BLOB);
sqlite> select * from unnamed;
sg_map|
subnet_map|7>
provider_code|
provider_name|
environment|N.
result_format|
partition|
account_id|
last_run|
metadata|
services|
service_list|
service_groups|gN
```

I don't know if this is the expected output, but it's not very usable, and each of the keys is just a blob of text, so there's not really any massaging of data into anything resembling a database.

**Comment by j4v** [comment]
Correct, it's a highly experimental feature that isn't complete.

**Comment by j4v** [comment]
It's part of a long-term milestone https://github.com/nccgroup/ScoutSuite/issues/226 which we haven't dedicated resources to in a while.

**Comment by klauern** [comment]
I've been trying to find good resources for parsing large JSON, but I can't find anything that is very useful.  `jq` is great, but if you don't know what the structure of the JSON is to begin with, it's hard to get a feel for what you're looking for.

I'm concerned as ScoutSuite's corpus of checks has grown, even the default size of a bare run against the `default.json` ruleset returns a very large file that's difficult to parse as-is.

I've been looking at fx (https://medium.com/@antonmedv/discover-how-to-use-fx-effectively-668845d2a4ea), and that seems to be getting me closer, but I'd be open for any other suggestions.

I've even tried parsing the output with `sqlitebiter` (https://github.com/thombashi/sqlitebiter), but it seems to fail parsing the raw JSON (first line omitted, of course).

**Comment by j4v** [comment]
The issue is the use of JSON in itself, and I don't think there's any "easy fix". In most cases the size of the JS/JSON is manageable so we haven't felt too much pressure to change.

The sqlite currently stores the whole blob as a single field. For that option to work we'll need to split it, but that will require changes in the tool itself which we can't support with our current resources.

**Comment by j4v** [comment]
> I'm concerned as ScoutSuite's corpus of checks has grown, even the default size of a bare run against the default.json ruleset returns a very large file that's difficult to parse as-is.

I'm not too concerned about this, because the rules themselves don't make much of a difference, only the resources being fetched. And as we already cover the base resources (i.e. the ones that are likely to be in very large numbers), I don't foresee that as a growing issue.
