### ISSUE TITLE
Bug: Poor implementation of Azure NSG ports

### ISSUE THREAD

**Issue by j4v** [nccgroup/ScoutSuite#793]
See https://github.com/nccgroup/ScoutSuite/issues/698#issuecomment-645229279.

Need to improve this implementation.

**Comment by ramimac** [comment]
ref to relevant code: https://github.com/nccgroup/ScoutSuite/blob/master/ScoutSuite/providers/azure/resources/network/security_groups.py

**Comment by j4v** [comment]
This has been resolved in `develop`.
