### ISSUE TITLE
Unsupported AWS RDS instance types

### ISSUE THREAD

**Issue by j4v** [nccgroup/ScoutSuite#794]
We need to review the RDS instance types supported.

We added support for Aurora in https://github.com/nccgroup/ScoutSuite/pull/696, but it was also raised that the https://github.com/nccgroup/ScoutSuite/blob/develop/ScoutSuite/providers/aws/rules/findings/rds-instance-no-minor-upgrade.json rule didn't support Oracle Enterprise Edition instances. 

There might be additional occurrences of this.

**Comment by j4v** [comment]
> it was also raised that the https://github.com/nccgroup/ScoutSuite/blob/develop/ScoutSuite/providers/aws/rules/findings/rds-instance-no-minor-upgrade.json rule didn't support Oracle Enterprise Edition instances.

For this specific case, the issue is that the rule explicitly states instance types, which doesn't include Oracle (and potentially others).

**Comment by ramimac** [comment]
Oracle and SQL Server are the two missing from the list as of right now.

[Amazon RDS on SQL Server doesn't support automatic minor version upgrades](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_UpgradeDBInstance.SQLServer.html)

Oracle **supports** automatic minor version upgrades.

I would personally flip the rule to explicitly exclude SQL Server. This means that any newer engines added _may_ cause false positives if they don't support minor version upgrades. Generally, I philosophically prefer false positives to false negatives, in cases like this where one or the other will be necessary for platform extensions.

@j4v if you're in agreement, I'll make this change

**Comment by j4v** [comment]
Sounds good @ramimac

**Comment by ramimac** [comment]
Closing, now fixed in `develop`
