### ISSUE TITLE
Incorrect resource paths in AWS ELB partial

### ISSUE THREAD

**Issue by j4v** [nccgroup/ScoutSuite#795]
Looks like the paths in ScoutSuite/output/data/html/partials/aws/services.elb.regions.id.vpcs.id.elbs.html for security groups, instances and subnets is wrong. This seems to be cause by having `services.elb` in the paths, instead of `services.ec2` and `services.vpc`.

**Comment by j4v** [comment]
In the security groups partial, for ELBs in SGs we display the internal ID, not the LBs name. Please fix this when addressing this issue.

**Comment by j4v** [comment]
Also, for ELBv2 Network LBs hide the `Security Groups` element, as it doesn't apply. See https://aws.amazon.com/premiumsupport/knowledge-center/security-group-load-balancer/.

**Comment by ramimac** [comment]
> Paths for security groups
Done.

> In the security groups partial, for ELBs in SGs we display the internal ID, not the LBs name
/output/data/html/partials/aws/services.ec2.regions.id.vpcs.id.security_groups.html -> resource_list

> Paths for instances and subnets is wrong
Done.

> ELBv2 Network LBs hide the Security Groups element, as it doesn't apply

Will need to add a helper bc AFAIK handlebars doesn't allow for equality operations. 

{{#if (eq Type "network")}}

**Comment by ramimac** [comment]
@j4v fixes for everything but "for ELBs in SGs we display the internal ID, not the LBs name" are in https://github.com/nccgroup/ScoutSuite/tree/bugfix/elb_partial.

I'm not familiar enough with Handlebars and the context we're in at that point to fix the remaining issue.

**Comment by j4v** [comment]
> for ELBs in SGs we display the internal ID, not the LBs name

Just means we're displaying `id`, instead of `name`.

**Comment by ramimac** [comment]
> Just means we're displaying id (which is the unique ID we've generated during the execution, not something AWS is returning), instead of name.

Understood. However right now we're just passing and using `this`. I just don't know enough about Handlebars context to get from there to the actual name :laughing:. Tried passing in `name` as an additional hash parameter, tried `this.name` directly, and couple other random guesses :man_shrugging:

**Comment by lowSoA** [comment]
> for ELBs in SGs we display the internal ID, not the LBs name

Fixed in `abe329449d62193230a824b6e8b7b47d6b97a3e9`, had to make a small change in the provider to pass the necessary information to the partial.

**Comment by j4v** [comment]
Closing, this is fixed in `develop`.
