### ISSUE TITLE
GCP Organization/Project/Region/Zone implementation

### ISSUE THREAD

**Issue by j4v** [nccgroup/ScoutSuite#80]
The implementation of organization/project/region/zone configuration architecture should be improved.

The implementation of `providers/gcp/configs/base.py` is less then ideal and should be improved to be similar to AWS RegionConfig.

Resources should be split by Project, meaning that the project will be in the resource's path, i.e. `services.cloudsql.projects.{id}.instances.{id}` instead of `services.cloudsql.instances.{id}`.

This should also allow grouping resources by project in the left navigation pane. Currently, when scanning a whole organization resources for different projects are all mixed in together.

**Comment by rtomlinson-latacora** [comment]
Would part of this be allowing a service account to scan all the service accounts that it has access to? I saw that this occurs for a user account with organization level access to all projects, but didn't see a way to allow this for service accounts.

**Comment by rtomlinson-latacora** [comment]
By adding a service account in one project as a service account in another project you're able to give cross project access to a single service account.

https://stackoverflow.com/questions/35479025/cross-project-management-using-service-account
https://cloud.google.com/sdk/gcloud/reference/projects/list

**Comment by j4v** [comment]
That's a neat trick, thanks for sharing.

This should already work with Scout, just authenticate with a service account and specify the project to scan with `--project-id`.

**Comment by j4v** [comment]
> Was just curious if it already had that functionality.

I'm not sure but it's possible that if you run it as a SA and specify an org/project it will work, I'd have to re-check how the discovery is implemented. Shouldn't be hard to implement though, I didn't take that case into account as I didn't think it was possible.

**Comment by rtomlinson-latacora** [comment]
I recall running ScoutSuite with a service account and specifying an org, but it only scanned the single account. My memory is a little hazy on that now. I went ahead and opened up an issue and would be happy to look at implementing the feature as well.

**Comment by misg** [comment]
To my knowledge, this has been implemented as part of refactoring #183 (and up in the `develop` branch). I let you double check @j4v and make the call for closing this issue.

**Comment by j4v** [comment]
Yep, this should now be implemented in `develop`.
