### ISSUE TITLE
Azure: Filter findings in JSON scan results by Resource Group

### ISSUE THREAD

**Issue by 0xRoger** [nccgroup/ScoutSuite#812]
After performing a scan against an Azure environment, I am trying to extract the findings belonging to a specific Resource Group only from the _results.json_ export.

However, there doesn't seem to be a straight-forward way to filter all findings by their Resource Group.

For the findings (items) in each of the different services, the Resource Group associated with them is obtained in a different way from the JSON output. Sometimes it is included in the item ID's of the affected items, or in most cases you obtain an item ID and have to run a separate query to obtain Resource Groups.

**Example:**
"virtualmachines": {
            "disks_count": 2,
            "filters": {},
            "findings": {
                "virtual-machines-disk-encryption": {
                    "checked_items": 2,
                    "dashboard_name": "Disks",
                    "description": "Disks Lacking Encryption",
                    "flagged_items": 2,
                    "id_suffix": "encryption_enabled",
                    "items": [
                        "virtualmachines.subscriptions.xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx.disks.48xxxxxxxxxxxxxxxxxxxx.encryption_enabled",
                        "virtualmachines.subscriptions.xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx.disks.a4xxxxxxxxxxxxxxxxxxxx.encryption_enabled"
                    ],
                    "level": "warning",
                    "path": "virtualmachines.subscriptions.id.disks.id",
                    "rationale": "Encrypting disks ensures that their entire content is fully unrecoverable without a key and thus protects the volume from unwarranted reads.",
                    "service": "Virtual Machines"
                },
                "virtual-machines-extensions-installed": {
                    "checked_items": 1,
                    "dashboard_name": "Instances",
                    "description": "Virtual Machine Extensions Installed",
                    "flagged_items": 1,
                    "id_suffix": "extensions",
                    "items": [
                        "virtualmachines.subscriptions.xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx.instances.8fxxxxxxxxxxxxxxxxxxxx.extensions"
                    ],
                    "level": "warning",
                    "path": "virtualmachines.subscriptions.id.instances.id",
                    "rationale": "Azure virtual machine extensions are small applications that provide post-deployment configuration and automation tasks on Azure virtual machines. These extensions run with administrative privileges and could potentially access anything on a virtual machine. The Azure Portal and community provide several such extensions.",
                    "service": "Virtual Machines"
                }
            },

**or**

"network": {
            "application_gateways_count": 1,
            "application_security_groups_count": 0,
            "filters": {},
            "findings": {
                "network-security-groups-rule-inbound-RDP": {
                    "checked_items": 10,
                    "dashboard_name": "NSGs",
                    "description": "Security Group Rules Allowing Inbound RDP Access",
                    "display_path": "network.subscriptions.id.security_groups.id",
                    "flagged_items": 1,
                    "items": [
                        "network.subscriptions.xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx.security_groups.2fxxxxxxxxxxxxxxxxxxxx.security_rules./subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/**resourceGroups/scoutRG**/providers/Microsoft.Network/networkSecurityGroups/scoutNSG/securityRules/RDP"
                    ],
                    "level": "warning",
                    "path": "network.subscriptions.id.security_groups.id.security_rules.id",
                    "rationale": "Description: RDP (port 3389) inbound access should not be allowed to a network security group. References: CIS Microsoft Azure Foundations v1.0.0 6.1",
                    "service": "Network"
                },

It would be very useful to have a unified way for every scanned item to easily match it with its Resource Group, being able to report only the results belonging to a specific Resource Group.

I have seen there is an open issue to allow Scout to scan specific Resource Groups planned for future version 5.10.
I imagine in order to implement this feature, the issue of filtering the results by Resource Group will be covered.
https://github.com/nccgroup/ScoutSuite/issues/661

Version affected 5.8
Component: JSON results export

**Comment by j4v** [comment]
As you mention at the bottom of the post, this is something we are working on. We've recently added the RGs as fields for each resource (https://github.com/nccgroup/ScoutSuite/issues/660), but that means you'll have to go through each affected item to check to which RG it belongs to.

As part of https://github.com/nccgroup/ScoutSuite/issues/661, we'll be adding a "node" to the Azure resource tree for RGs, which will allow scanning specific RGs and should simplify what you describe.

I'm closing this as I don't see anything new to what's mentioned in the 2 other issues.
