### ISSUE TITLE
Add ScoutSuite user agent

### ISSUE THREAD

**Issue by j4v** [nccgroup/ScoutSuite#817]
Cloud providers review the user agent of API requests for a number of purposes. We should ensure that we configure the tool to send a recognizable user agent.

This should apply to all cloud providers.

**Comment by darumaseye** [comment]
For AWS It could be done adding a [**botocore.config.Config**](https://botocore.amazonaws.com/v1/documentation/api/latest/reference/config.html) obj as parameter during the call of **boto3.session.Session.client**. As stated in the [docs](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/core/session.html#boto3.session.Session.client), with Config object of botocore module the SDK can be managed at low level, setting also Region and user agent. 
The present code:
https://github.com/nccgroup/ScoutSuite/blob/e5dd01dab08ed8d887736cfcee068c1b8895d4a1/ScoutSuite/providers/aws/facade/utils.py#L81-L98
could be modified like this.
```
def get_client(service: str, session: boto3.session.Session, region: str = None):
         if region:
             user_agent_config = Config(region_name=region,
                                        user_agent="ScoutSuite/5.9 (https://github.com/nccgroup/ScoutSuite)")
         else:
             user_agent_config = Config(user_agent="ScoutSuite/5.9 (https://github.com/nccgroup/ScoutSuite)")
         try:
             return AWSFacadeUtils._clients.setdefault(
                 (service, region), session.client(service, config=user_agent_config))
         except Exception as e:
             print_exception('Failed to create client for the {} service: {}'.format(service, e))
             return None
```
I hope it works, unluckly i can't test it now.
I didn't find a maintinable way to do this with others providers that don't have a low level sdk like boto3. Is there a way edit sdk settings at http level?

**Comment by j4v** [comment]
> I didn't find a maintinable way to do this with others providers that don't have a low level sdk like boto3. Is there a way edit sdk settings at http level?

I'm sure all of the SDKs have a way (documented or not), we'll just have to dig into each individually!

**Comment by j4v** [comment]
Implemented in `develop`.
