### ISSUE TITLE
GCS Bucket - Public access with "allUsers" not detected

### ISSUE THREAD

**Issue by sivakums** [nccgroup/ScoutSuite#820]
There is a GCS bucket with public access for "allUsers" with "Storage Object Viewer" role did not get detected in the scout suite run report. We checked the report, the bucket was scanned but didnt get flagged under the category.

**To Reproduce**

Create a gcs bucket with public access and run the scout suite.

**Comment by j4v** [comment]
Thanks, will look into it.

**Comment by j4v** [comment]
Thanks for raising this, the issue should now be resolved in the `develop` branch.
