### ISSUE TITLE
images.py not iterable Azure

### ISSUE THREAD

**Issue by dataatsky** [nccgroup/ScoutSuite#822]
**Describe the bug**

Scout version: 5.8.1
Cloud: Azure

When running scout against a specific Azure subscription we get the following error as seen below. Do let us know if you need more information.

- The exact CLI parameters used to run Scout Suite.
- ./scout.py azure --tenant xxx-xxx-xxx-xxx --subscriptions xxx-xxx-xxx-xxx-xxxx --user-account-browser

- Any specific configuration within the cloud account which might have lead to the issue.
- Nothing specific

**Additional context**

Traceback:

2020-07-27 01:21:12 ubuntu asyncio[2937] ERROR Task exception was never retrieved
future: <Task finished coro=<Images.fetch_all() done, defined at /home/victor/Documents/test/ScoutSuite-5.8.1/ScoutSuite/providers/azure/resources/virtualmachines/images.py:12> exception=TypeError("'NoneType' object is not iterable",)>
Traceback (most recent call last):
  File "/home/victor/Documents/test/ScoutSuite-5.8.1/ScoutSuite/providers/azure/resources/virtualmachines/images.py", line 14, in fetch_all
    id, image = self._parse_image(raw_image)

Thank you

**Comment by dataatsky** [comment]
This error does not seem to reproduce in 5.9

**Comment by j4v** [comment]
> This error does not seem to reproduce in 5.9

This has been fixed in the latest release.
