### ISSUE TITLE
Exported report too big to be open

### ISSUE THREAD

**Issue by dataatsky** [nccgroup/ScoutSuite#826]
**Describe the bug**

I have a scanned a subscription and the output report is more than 500Mb. As such it takes a long time to open or it does not open because it gets stuck. Is there anyway to reduce the size when outputting it?

Cloud is Azure and the command is anything with the "--report-dir" argument.

**Additional context**

Scout 5.8.1

**Comment by j4v** [comment]
This is most likely https://github.com/nccgroup/ScoutSuite/issues/793, as well as https://github.com/nccgroup/ScoutSuite/issues/226.
