### ISSUE TITLE
Upcoming Deprecation of Microsoft Azure Active Directory Graph [2022]

### ISSUE THREAD

**Issue by alexionescu** [nccgroup/ScoutSuite#829]
**Describe the bug**

According to https://github.com/nccgroup/ScoutSuite/wiki/Azure the tool requires the `Azure Active Directory Graph API Directory.Read.All` permission.

On July 24, 2020 Microsoft has published an announcement intending they are deprecating this endpoint on June 30th, 2022.

> Upgrade your applications to use Microsoft Graph. We’re no longer adding new features to Azure AD Graph and starting June 30th, 2022 we will no longer provide any technical support or security updates. Instead we recommend you use Microsoft Graph, which is where we will continue to invest. Supporting APIs that are currently available in Azure AD Graph API are now available in Microsoft Graph. In addition, Microsoft Graph supports many new Azure AD data sets and features that are not available in Azure AD Graph.
> 
> Key Points:
> 
> Major: Retirement
> Timing: June 30, 2022
> Action: review and assess
> How this affects your organization:
> You are receiving this message because our reporting indicates one or more of your applications are using Azure AD Graph. 
> Applications will no longer receive responses from the Azure AD Graph endpoint after June 30th, 2022.
> How to prepare for this change:
> To update your applications to use Microsoft Graph, follow our migrate [Azure AD Graph apps to Microsoft Graph guide](https://docs.microsoft.com/en-us/graph/migrate-azure-ad-graph-overview?view=graph-rest-1.0).
> 
> To learn more review the [Update your applications to use Microsoft Authentication Library and Microsoft Graph API blog post](https://techcommunity.microsoft.com/t5/azure-active-directory-identity/update-your-applications-to-use-microsoft-authentication-library/ba-p/1257363).

**Comment by j4v** [comment]
Thanks for raising this, we'll have to take it into account ASAP.

Up to now we've favored Azure Active Directory Graph over Microsoft Graph as it actually exposes more stuff and allows for more authentication mechanisms (such as username/password execution). But if it's going to be deprecated in the near-ish future, we have to take it into account.

**Comment by praetorian-harry** [comment]
I see that this issue was closed. Has work been done to migrate to use the Microsoft Graph instead of Azure Active Directory Graph?

If so, the [Azure wiki page](https://github.com/nccgroup/ScoutSuite/wiki/Azure) should be updated to reflect the new permissions required.

**Comment by j4v** [comment]
> Has work been done to migrate to use the Microsoft Graph instead of Azure Active Directory Graph?

Yes, this is implemented in https://github.com/nccgroup/ScoutSuite/pull/1166. We're waiting on Microsoft to resolve an issue before we can merge/release.

> If so, the Azure wiki page should be updated to reflect the new permissions required.

This is in progress.

**Comment by j4v** [comment]
@praetorian-harry this is now updated - https://github.com/nccgroup/ScoutSuite/wiki/Azure#permissions

**Comment by praetorian-harry** [comment]
@j4v thank you! So this change will take effect with v6, which is yet to be released?

**Comment by j4v** [comment]
Not exactly, the changes are both in https://github.com/nccgroup/ScoutSuite/pull/1166 (uses the current report generation) and v6 (https://github.com/nccgroup/ScoutSuite/pull/1290).
