### ISSUE TITLE
External Attack Surface not calculated for GCP 

### ISSUE THREAD

**Issue by royharoush** [nccgroup/ScoutSuite#830]
Hi, 
For AWS reports there's a section in various menus called "external attack surface". 
![image](https://user-images.githubusercontent.com/8113056/89781574-4b78da00-db1c-11ea-840f-3672a942951a.png)

It doesn't exists for GCP.
Any chance to add it to GCP report as well ? 
Thanks ! 
Roy

**Comment by j4v** [comment]
Closing as a duplicate of https://github.com/nccgroup/ScoutSuite/issues/189.
