### ISSUE TITLE
Add flag to bypass the launch of browser

### ISSUE THREAD

**Issue by roboweaver** [nccgroup/ScoutSuite#835]
**Is your feature request related to a problem? Please describe.**

At the end of the run, the report HTML opens in the browser, this is annoying when trying to scan multiple accounts. 

**Describe the solution you'd like**

Add a flag to bypass launching of browser like "--quiet" or "--no_launch"

When the flag is passed into the script, there is no attempt to launch the browser

**Describe alternatives you've considered**

Updating the codebase and submitting a PR :) 

**Additional context**

**Comment by ramimac** [comment]
@roboweaver have you tried/are you aware of the --no-browser flag? If you've given that a shot, can you clarify in what way it's broken or not meeting your needs?

**Comment by roboweaver** [comment]
OK, looks like this flag exists as `--no_browser` - I will try that. Seems like what's missing is the documentation for the flags.

**Comment by roboweaver** [comment]
BTW there appear to be lots of flags that don't show up in the help

**Comment by roboweaver** [comment]
scout aws --no_browser --regions us-west-1 us-west-2 us-east-1 us-east-2 eu-west-1 eu-central-1

usage: scout [-h] [-v] {aws,gcp,azure,aliyun,oci} ...
scout: error: unrecognized arguments: --no_browser

**Comment by roboweaver** [comment]
never mind I should have read your post instead of pulling it from the code :)

**Comment by roboweaver** [comment]
List of flags would be useful

**Comment by ramimac** [comment]
@roboweaver FYI flags are listed in the provider help (not at the top level `scout -h`)

i.e
```
$ scout aws -h
usage: scout aws [-h] [-f] [-l] [--max-rate MAX_RATE] [--debug] [--quiet]
                 [--logfile [LOG_FILE]] [--update] [--ruleset [RULESET]]
                 [--no-browser] [--max-workers MAX_WORKERS]
                 [--report-dir REPORT_DIR] [--report-name REPORT_NAME]
                 [--timestamp [TIMESTAMP]]
                 [--services SERVICES [SERVICES ...]] [--list-services]
                 [--skip SKIPPED_SERVICES [SKIPPED_SERVICES ...]]
                 [--exceptions [EXCEPTIONS]] [--result-format {json,sqlite}]
                 [--serve [DATABASE_NAME]] [--host HOST_IP] [--port HOST_PORT]
                 [-p PROFILE | --access-keys]
                 [--access-key-id AWS_ACCESS_KEY_ID]
                 [--secret-access-key AWS_SECRET_ACCESS_KEY]
                 [--session-token AWS_SESSION_TOKEN]
                 [-r REGIONS [REGIONS ...]]
                 [-xr EXCLUDED_REGIONS [EXCLUDED_REGIONS ...]]
                 [--ip-ranges IP_RANGES [IP_RANGES ...]]
                 [--ip-ranges-name-key IP_RANGES_NAME_KEY]

optional arguments:
  -h, --help            show this help message and exit

Scout Arguments:
  -f, --force           Overwrite existing files
  -l, --local           Use local data previously fetched and re-run the
                        analysis.
  --max-rate MAX_RATE   Maximum number of API requests per second
...
  --no-browser          Do not automatically open the report in the browser.
```
