### ISSUE TITLE
Feature Request : Include tag information for IAM Users

### ISSUE THREAD

**Issue by rams3sh** [nccgroup/ScoutSuite#838]
**Is your feature request related to a problem? Please describe.**
User Resource lacks tags.

**A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]**

There are some use case for me where certain tags are exempted from a compliance rule and others are not.
Due to lack of tags information being captured as part of IAM user resource, am unable to implement such rule checks.

**Describe the solution you'd like**
Expected output for iam users in result json :- 

**Describe alternatives you've considered**

I use a custom stand alone script to audit such cases alone separately.

**Additional context**

None

**Comment by rams3sh** [comment]
Missed the expected output in the original issue.

Below the expected json output :- 
![image](https://user-images.githubusercontent.com/5143597/91644746-a4bd9480-ea5c-11ea-91e5-11a99c4c210f.png)

**Comment by j4v** [comment]
Closing, this is implemented in `develop`.
