### ISSUE TITLE
Feature Request : Include tag information for IAM Roles

### ISSUE THREAD

**Issue by rams3sh** [nccgroup/ScoutSuite#841]
**Is your feature request related to a problem? Please describe.**
Role Resource lacks tags.

**A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]**

There are some use case for me where certain tags are exempted from a compliance rule and others are not.
Due to lack of tags information being captured as part of IAM role resource, am unable to implement such rule checks.

**Describe the solution you'd like**
Tags to be part of the AWS IAM Roles.

**Describe alternatives you've considered**

I use a custom stand alone script to audit such cases alone separately.

**Additional context**

None

**Comment by rams3sh** [comment]
This tag requirement is a need for me across all resources that support tags. Would I need to raise individual feature requests individually for each service and resource ?

It would be nice to have this attribute captured across all supported resource. This can be availed by multiple custom tag based rules. Would definitely be very useful.

**Comment by ramimac** [comment]
This is all technically tracked via #627 I believe. However, adding tags to a single resource is fairly "easy" (versus figuring out and implementing a way to do so automatically across the board.) So, personally, "individual feature requests individually for each service and resource" would really clutter the issue tracker, but if there are certain key resources missing where this is a common blocker, it may be worth it's own issue in case it can be addressed individually (instead of waiting for someone to tackle #627)

**Comment by ramimac** [comment]
As a quick example of how I'd go about adding tag information for IAM roles (I don't have the time to code this up right now, but maybe this pseudocode will help you or someone else file a PR)

1. The resource and facade for IAM Roles are https://github.com/nccgroup/ScoutSuite/blob/master/ScoutSuite/providers/aws/resources/iam/roles.py, https://github.com/nccgroup/ScoutSuite/blob/master/ScoutSuite/providers/aws/facade/iam.py

2. The facade calls https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/iam.html#IAM.Client.list_roles to get this information, which already contains the list of tags

3. So, we don't need to change the facade, just add the tags to the resource dict. We do this elsewhere, for example for elbv2:

```
if 'Tags' in load_balancer and load_balancer['Tags']:
    load_balancer['tags'] = {x['Key']: x['Value'] for x in load_balancer['Tags']}
    load_balancer.pop('Tags')
```

4. Then just make sure the Tags are rendered in the partial (https://github.com/nccgroup/ScoutSuite/blob/master/ScoutSuite/output/data/html/partials/aws/services.iam.roles.html)

```
        {{#if tags}}
            <div class="list-group-item">
                <h4>Tags</h4>
                <ul>
                    {{#each tags}}
                    <li class="list-group-item-text"><samp>{{@key}}</samp>: <samp>{{this}}</samp></li>
                    {{/each}}
                </ul>
            </div>
        {{/if}}
```

**Comment by rams3sh** [comment]
Thats good one. In that case , I will try making a list of resources that support tags but are not present currently in the scoustsuite report. With that we may have a number to work on. 

Also going forward, it would be nice to consider getting tags as one of the mandatory methods (if that resource supports) for each new addition of services / resources so that new ones may not be touched or reworked on.

**Comment by ramimac** [comment]
Closing as fix was merged!
