### ISSUE TITLE
No rules for ElastiCache

### ISSUE THREAD

**Issue by b3ll0v1c** [nccgroup/ScoutSuite#844]
It looks like a service for ElastiCache has been created but there are no rules for it. Can you please confirm before embark myself into attempting to create some rules that test for encryption in transit and at rest?

I saw there is an elasticache directory with some classes in it in the resources directory but I didn't see any json file in the findings directory related to elasticache. Thank you.

**Comment by j4v** [comment]
That is correct, the service is partially supported but no rules have been written. Feel free to submit a PR!
