### ISSUE TITLE
GCP - Default Firewall Rule in Use

### ISSUE THREAD

**Issue by ramimac** [nccgroup/ScoutSuite#845]
**Describe the bug**

The  GCP Compute Engine Default Firewall Rule in Use should check that the rules are not disabled. 

Additionally, the Facade and Resource are incorrectly marking Firewall rules as disabled.

For example:

`gcloud compute firewall-rules list --project PROJECT`

```
NAME          NETWORK  DIRECTION  PRIORITY ALLOW DENY  DISABLED

default-allow-https  default  INGRESS    1000      tcp:443    False
```

However the report shows Status:Disabled.

[The documentation](https://cloud.google.com/compute/docs/reference/rest/v1/firewalls) does say "When set to true, the firewall rule is not enforced and the network behaves as if it did not exist. If this is unspecified, the firewall rule will be enabled.". I'm wondering if `unspecified` is getting treated as disabled.

**Comment by j4v** [comment]
> Additionally, the Facade and Resource are incorrectly marking Firewall rules as disabled.

Did you try `develop`? Some improvements were made as part of https://github.com/nccgroup/ScoutSuite/issues/770.

**Comment by ramimac** [comment]
Good call, can confirm that has been fixed in develop. 

It doesn't look like the finding itself takes the Status into account yet, but at least now the context is accurate to make that call on looking through the report!

**Comment by j4v** [comment]
Closing, this is implemented in `develop`.
