### ISSUE TITLE
No rules for AWS Lambdas

### ISSUE THREAD

**Issue by b3ll0v1c** [nccgroup/ScoutSuite#850]
Just wanted to confirm that there are no written rules at this time for ASW Lambdas, only a resource. Thanks.

**Comment by ramimac** [comment]
Correct, there are not public rules for AWS Lambda. 

As a higher-level pointer, the easiest way to answer these questions (ex. #844 as well) would be to check the set of findings in the develop branch: https://github.com/nccgroup/ScoutSuite/tree/develop/ScoutSuite/providers/aws/rules/findings
