### ISSUE TITLE
AWS Test: Unused Security Group Test not looking at CodeBuild

### ISSUE THREAD

**Issue by PaulDMendoza** [nccgroup/ScoutSuite#856]
Unused security group is not looking at CodeBuild builds that are configured to use it.

![image](https://user-images.githubusercontent.com/1039795/93029507-2d494280-f5d0-11ea-8baa-3ea8a83ca7af.png)

![image](https://user-images.githubusercontent.com/1039795/93029552-8618db00-f5d0-11ea-9557-07e8b229cf2a.png)

**To Reproduce**
Create a CodeBuild build configured to use the security group.

**Comment by ramimac** [comment]
This is a duplicate of #620 - thank you for providing the screenshots though!
