### ISSUE TITLE
Number of buckets checked for AWS S3 `Get Actions Authorized to All Principals` is inaccurate

### ISSUE THREAD

**Issue by pseudo-name** [nccgroup/ScoutSuite#857]
I have 200 AWS S3 buckets, and 61 of them have a bucket policy attached. The Scout Suite report says that 99 buckets were checked for this rule. How is that possible?

**Comment by j4v** [comment]
The count is for policy statements. I'll update the rule accordingly, thanks.

**Comment by pseudo-name** [comment]
Thanks for the quick response @j4v. I assume by "policy statements" you mean Sids? That value matches more closely, but it's still off by a few. If I download the s3.csv file from the Scout Suite report and search for "Sid" I get 95 matches. Do you know why there is a discrepancy?
