### ISSUE TITLE
Azure Leverage ADAL for authentication

### ISSUE THREAD

**Issue by j4v** [nccgroup/ScoutSuite#863]
The current Azure authentication uses deprecated methods (see https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-authenticate?tabs=cmd#deprecated-authenticate-with-userpasscredentials). We should refactor the `authentication_strategy.py` to fully leverage ADAL.

This is a pre-requisite for https://github.com/nccgroup/ScoutSuite/issues/862, and also relates to https://github.com/nccgroup/ScoutSuite/issues/829.

Look at https://github.com/Azure/msrestazure-for-python/issues/129 and https://github.com/AzureAD/azure-activedirectory-library-for-python/wiki/Acquiring-Tokens-with-username-and-password for reimplementation of username/password authentication flow.

**Comment by j4v** [comment]
Look at ROADtools' (https://github.com/dirkjanm/ROADtools/blob/master/roadlib/roadtools/roadlib/auth.py) implementation, as they are doing exactly that.

**Comment by xnkevinnguyen** [comment]
Since  ADAL is replaced by MSAL, we will migrate to MSAL for authentication.
