### ISSUE TITLE
Typo in AWS *world-policy* finding rationale

### ISSUE THREAD

**Issue by sushantmimani** [nccgroup/ScoutSuite#880]
**Describe the bug**

There are typos in the rationale field in the following files:

- ScoutSuite/providers/aws/rules/findings/s3-bucket-world-policy-arg.json
- ScoutSuite/providers/aws/rules/findings/s3-bucket-world-policy-star.json
- ScoutSuite/providers/aws/rules/findings/ses-identity-world-policy.json
- ScoutSuite/providers/aws/rules/findings/sns-topic-world-policy.json
- ScoutSuite/providers/aws/rules/findings/sqs-queue-world-policy.json

**Comment by j4v** [comment]
Closed by https://github.com/nccgroup/ScoutSuite/pull/881.
