### ISSUE TITLE
PyPi version is still 5.9.1

### ISSUE THREAD

**Issue by djcater** [nccgroup/ScoutSuite#885]
**Describe the bug**
The version of ScoutSuite on PyPi is still version 5.9.1: https://pypi.org/project/ScoutSuite/

The latest release on GitHub is version 5.10.0: https://github.com/nccgroup/ScoutSuite/releases

Having the newer version on PyPi would be useful for people to be able to install the package with `pip` without first having to download the source code and install via `requirements.txt`.

**Comment by j4v** [comment]
This has been resolved, thanks.
