### ISSUE TITLE
Add support for AWS CloudFront rule checking secure content distributions

### ISSUE THREAD

**Issue by yangsec888** [nccgroup/ScoutSuite#899]
**Is your feature request related to a problem? Please describe.**

It would be nice to create rule to fast check secure distribution of sensitive web contents (served by CloudFront service)

**Describe the solution you'd like**

Once the CloudFront assets is pulled down, create corresponding rule to fast check secure distribution over https only. 

**Describe alternatives you've considered**

None 

**Additional context**

a. ScoutSuite would need to call out AWS api for cloudfront assets first (dependency) 
b. Once the rule check is developed, it would also need corresponding views created in the dashboard

**Comment by j4v** [comment]
Closing to remove clutter, this will be tracked under https://github.com/nccgroup/ScoutSuite/issues/898.
