### ISSUE TITLE
Add support for AWS CloudFront in Navigation menu and Finding View

### ISSUE THREAD

**Issue by yangsec888** [nccgroup/ScoutSuite#900]
**Is your feature request related to a problem? Please describe.**

Refer to issue 890. Once the rule engine flag insecure content distribution, we also need menu change /  view partial(s) to display the finding(s).

**Describe the solution you'd like**

a) Need help location navigation menu and insert the new AWS service.
b) Need help create view partial to display the finding and assets. 

**Describe alternatives you've considered**

None.

**Additional context**

Following existing AWS audit workflow.

**Comment by j4v** [comment]
Closing to remove clutter, this will be tracked under https://github.com/nccgroup/ScoutSuite/issues/898.
