### ISSUE TITLE
Add support for multi-account config

### ISSUE THREAD

**Issue by kbroughton** [nccgroup/ScoutSuite#901]
**Is your feature request related to a problem? Please describe.**

Currently Scout reports if AWS Config is not configured. I believe this would give a false positive with the current checks as it is possible to set config up with multi-account.

**Describe the solution you'd like**

The logic for config should be modified to also check if there are any aggregate authorizations. If so, then 
```
aws --profile $SOURCE_PROFILE configservice describe-aggregation-authorizations --region $REGION
```
will return a non-empty list.

https://github.com/nccgroup/ScoutSuite/blob/master/ScoutSuite/providers/aws/rules/findings/config-recorder-not-configured.json

**Describe alternatives you've considered**

Not sure how else it could be done. Perhaps through existence of S3 buckets
It might also be possible to find a role created in the target (source) account, but I didn't see AWSServiceRoleForConfigMultiAccountSetup
There might also be an access analyzer log for  config-multiaccountsetup service, but I didn't check.

**Additional context**

I did the following experiment. Org and child accounts with no config. Added Config to Org. Via Org, added the AWS account ID for child. In child account, `configservice describe-configuration-recorders` returns a null list, but after accepting the pending aggregate request via `configservice put-aggregation-authorization`, you can discover the aggregation with ` configservice describe-aggregation-authorizations`

**Comment by j4v** [comment]
> I believe this would give a false positive with the current checks as it is possible to set config up with multi-account.

That's correct, and is the case for a number of services that can be centralized within an organization. Scout currently has no visibility on anything other than the account against which it's run.

> Not sure how else it could be done. 

If you're confident a finding is a false positive or don't want to raise it every time you run a scan, you can use an [exceptions file](https://github.com/nccgroup/ScoutSuite/wiki/Creating-and-Using-an-Exceptions-File).

Support for AWS Organization is already tracked under https://github.com/nccgroup/ScoutSuite/issues/249 so I'll close this as a duplicate.

**Comment by kbroughton** [comment]
would you be interested in a PR to accommodate the checks mentioned?

**Comment by j4v** [comment]
> would you be interested in a PR to accommodate the checks mentioned?

Of course, we're always happy to accept PRs.
