### ISSUE TITLE
HTTP webapp Azure rules have the same condition

### ISSUE THREAD

**Issue by dataatsky** [nccgroup/ScoutSuite#921]
**Describe the bug**

Version: Scout 5.10

Hi,

HTTP webapp Azure rules have the same condition in the following files: 

- appservice-http-2-disabled.json 
- appservice-outdated-http-version.json

Therefore we are getting a match for these 2 rules when running Scout. Can you please modify them or remove one of them as both seem to lead to the same result? I mean, if there's an oudated HTTP version is because HTTP 1.1 is being used instead of version 2. At the same time, http2 is disabled because HTTP 1.1 is in use. To me they look redundant.

A clarification on this matter should be done.

Thank you

**Comment by j4v** [comment]
Thanks for raising, we'll review ASAP.

**Comment by j4v** [comment]
Closing, this is implemented in `5.10.2`.
