### ISSUE TITLE
Azure rule TLS mismatch

### ISSUE THREAD

**Issue by dataatsky** [nccgroup/ScoutSuite#922]
**Describe the bug**

Version: Scout 5.10

Hi, 

In the rule "appservice-tls-v1-supported.json" I've realized that matches if the webapp is using HTTPS only ("appservice.subscriptions.id.web_apps.id.https_only"). However in the description of the rule, states that should be the TLS version running. On Azure this can be 1.0,1.1 or 1.2 being the latter the recommended one. This rule is checking for HTTPS instead of the TLS version and should be changed accordingly.

Thank you

**Comment by j4v** [comment]
Thanks for raising, we'll review ASAP.

**Comment by j4v** [comment]
Closing, this is now fixed in `5.10.2`.
