### ISSUE TITLE
Azure rule appservice-outdated-version-dotnet mismatch

### ISSUE THREAD

**Issue by dataatsky** [nccgroup/ScoutSuite#923]
**Describe the bug**

Version: Scout 5.10

Hi,

The rule appservice-outdated-version-dotnet.json results in a mismatch/false positive when using the .NET Core as first choice instead of the .NET Framework.  If we run the command "`az webapp config show --resource-group xxxxx --name xxxx`", we can see the output in the attached image.
<img width="498" alt="CLI_Command_NET" src="https://user-images.githubusercontent.com/35199771/98532312-d1263600-2281-11eb-9a9b-556b7d90ebd8.png">

While the .NET Framework is version 4.0, the linuxfxVersion is: "DOTNETCORE|3.1". Now, if we open the webapps.py file we see that goes first with the fxversion instead of the .NET Framework. Therefore if it gets a result in the fxversion field, it will be used in the rule and it will result in a mismatch.
![imagen](https://user-images.githubusercontent.com/35199771/98532630-3e39cb80-2282-11eb-9fef-2e30619bf833.png)

As a quick fix, you should change the order in the script so .net_framework_version goes first than linux_fx_version.
Another solution could be to treat the .NET Core and .NET framework as separate programming languages in your code.

Thank you

**Comment by j4v** [comment]
Thanks @dataatsky, will look into it. The APIs for this are a mess.

**Comment by j4v** [comment]
> Another solution could be to treat the .NET Core and .NET framework as separate programming languages in your code.

This is the case though, if you look at the first `if` statement you can see that we set the `programming_language`, which will be `dotnetcore` in the case you describe.

.Net (will not get flagged):

![sc_2020-12-03_14h07m39s](https://user-images.githubusercontent.com/4206926/101022067-2ac40c80-3571-11eb-9c73-3507f1adf130.png)

.Net Core (will not get flagged):

![sc_2020-12-03_14h07m35s](https://user-images.githubusercontent.com/4206926/101022107-38799200-3571-11eb-80ad-19cf5db3c00b.png)

Are you running the latest version? Will close for now as an invalid issue, feel free to reopen if we're missing something.
