### ISSUE TITLE
Is there a documented guide on how I can programmatically use ScoutSuite after importing the library?

### ISSUE THREAD

**Issue by roshanpty** [nccgroup/ScoutSuite#932]
I am looking for a way to programmatically access the functions within ScoutSuite to run scans based on a logic defined by my script rather than running scout cli. Do you have the available methods documented somewhere?

**Comment by j4v** [comment]
You can invoke `run` (https://github.com/nccgroup/ScoutSuite/blob/master/ScoutSuite/__main__.py#L83) directly.
