### ISSUE TITLE
Question: Create rule for CIS v1.1.0 benchmark 2.3

### ISSUE THREAD

**Issue by Nik006** [nccgroup/ScoutSuite#936]
I am new to scout Suite and I am trying to create rule for "Ensure ASC Default policy setting "Monitor System Updates" is not "Disabled". For that I have to do some changes in services.
But unable to find the correct methods for it in azure SDK for python documentation.
What is the bestway to find correct methods?

Than you!

**Comment by Nik006** [comment]
Its urgent. please any one can help  me out?

**Comment by j4v** [comment]
It's under Security Center so you'll want to look into the https://pypi.org/project/azure-mgmt-security/ library (`securitycenter` facades and resources in Scout). I'm not 100% that it's supported by the SDK though.

**Comment by j4v** [comment]
Looking at the CIS benchmark, it mentions `policyAssignments` which I can find under `azure-mgmt-resource` (https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/resources/azure-mgmt-resource/azure/mgmt/resource/policy/v2019_09_01/operations/_policy_assignments_operations.py), maybe that library would work?

**Comment by j4v** [comment]
Closing as this is a question.
