### ISSUE TITLE
GCP scanning ignores IAM service if IAM API not enabled in the target project

### ISSUE THREAD

**Issue by timretout** [nccgroup/ScoutSuite#943]
@j4v filling out yet another bug to cover this IAM thing I mentioned in #940 - I haven't quite got this one straight in my head, which I usually look to do _before_ filing bugs, so please bear with me while I spam the issue tracker!  Thank you for all the work you do on this. :)

**Describe the bug**

When scanning GCP projects which do not have the IAM API enabled, no IAM results are reported.  However, we know all projects have IAM roles.

When I comment out the Service Usage API check, I get results reported for all projects, regardless of whether the IAM API is enabled in that project.  This may be because I'm running ScoutSuite in its own GCP project (in a separate organization) so it always has access to the IAM API?

This shows that it is possible to scan IAM permissions without the IAM API being enabled for the target project.

In general, I am concerned that just because a service API is not enabled for a project, this does not mean that that service is not used by that project - potentially this might extend beyond IAM.

**To Reproduce**

Scan a project without the IAM API enabled.  Observe no results.

Comment out the service usage API checks in facade/base.py.  Run the scan again and get results.  (May depend on running ScoutSuite from another project that has the IAM API enabled?)

**Comment by j4v** [comment]
I'm surprised by this one, I'd have thought the IAM service would always be enabled since, as you mention, there are always roles assigned.

> When I comment out the Service Usage API check, I get results reported for all projects,

That makes sense, all we need is to treat IAM as a special case.

> In general, I am concerned that just because a service API is not enabled for a project, this does not mean that that service is not used by that project - potentially this might extend beyond IAM.

Yep, I don't really understand how it can be disabled, I've never seen a project without any roles or SAs.

**Comment by timretout** [comment]
Here's my understanding of what is going on:

![scoutsuite-gcp-apis](https://user-images.githubusercontent.com/145734/101285705-8810c580-37de-11eb-8ee7-f8006488f4f7.png)

When I create a new GCP project, the IAM API is not enabled by default. I see this list enabled:

<img width="217" alt="Screenshot 2020-12-06 at 16 19 22" src="https://user-images.githubusercontent.com/145734/101285759-d625c900-37de-11eb-83dd-5c57dbfcc41a.png">

Similarly, the Cloud SQL component ("sql-component.googleapis.com") is enabled by default, but not the Cloud SQL Admin API ("sqladmin.googleapis.com") needed to scan it.  This is already accounted for in the list in facade/base.py - so there's a difference between the APIs needed to scan the project vs. whether the actual service is enabled in the project.  The IAM API is more like the Cloud SQL Admin API in this respect.

**Comment by j4v** [comment]
Closing, this is merged in `develop`.
