### ISSUE TITLE
AWS IAM acm:DescribeCertificate error

### ISSUE THREAD

**Issue by AntonUspehov** [nccgroup/ScoutSuite#946]
**Describe the bug**
Non-actual example of typical AWS IAM policy - [documentation](https://github.com/nccgroup/ScoutSuite/wiki/AWS-Minimal-Privileges-Policy)
Errors after ScoutSuite execution:
```
ERROR acm.py L21: Failed to describe acm certificate: An error occurred (AccessDeniedException) when calling the DescribeCertificate operation: User: arn:aws:iam::REDACTED:user/REDACTED is not authorized to perform: acm:DescribeCertificate on resource: arn:aws:acm:REDACTED:REDACTED:certificate/REDACTED
```

**To Reproduce**
```sh
scout aws --no-browser
```

**Additional context**
Have to add `acm:DescribeCertificate` to AWS typical policy in the [documentation](https://github.com/nccgroup/ScoutSuite/wiki/AWS-Minimal-Privileges-Policy) to avoid the issue.

**Comment by j4v** [comment]
Thanks for raising this @antonpavlov856
