### ISSUE TITLE
FPs in "Insecure TLS Version Supported" Azure Finding

### ISSUE THREAD

**Issue by j4v** [nccgroup/ScoutSuite#949]
https://github.com/nccgroup/ScoutSuite/blob/master/ScoutSuite/providers/azure/rules/findings/appservice-tls-v1-supported.json raises FPs for apps with `1.2` as the minimum version.

**Comment by lowSoA** [comment]
Can't reproduce the issue. App Services with 1.2 as the minimum TLS version don't get flagged by the rule, 1.0 and 1.1 do.

The [resource processing](https://github.com/nccgroup/ScoutSuite/blob/89e74256fb9d784b6f5dc3ebc2555232fc836624/ScoutSuite/providers/azure/resources/appservice/web_apps.py#L72) and [condition in the rule](https://github.com/nccgroup/ScoutSuite/blob/89e74256fb9d784b6f5dc3ebc2555232fc836624/ScoutSuite/providers/azure/rules/findings/appservice-tls-v1-supported.json#L20) seem fine.

**Comment by j4v** [comment]
This is a FP, the issue was fixed by https://github.com/nccgroup/ScoutSuite/issues/922.
