### ISSUE TITLE
azure report for encrypted disk

### ISSUE THREAD

**Issue by tetlika** [nccgroup/ScoutSuite#952]
version 5.10.2 has a bug - it shows that disk with default encryption is not encrypted while az tools show it is encrypted:

here are screenshots from az and scoutsuite:

<img width="384" alt="Screenshot 2020-12-16 at 17 30 54" src="https://user-images.githubusercontent.com/270471/102377632-31b53b00-3fc5-11eb-90d0-62475850df39.png">
<img width="772" alt="Screenshot 2020-12-16 at 17 32 17" src="https://user-images.githubusercontent.com/270471/102377636-32e66800-3fc5-11eb-8d32-966f3b5740b4.png">

**Comment by j4v** [comment]
I've confirmed this is happening, will look into it.

**Comment by tetlika** [comment]
thanks for confirmation @j4v

**Comment by lowSoA** [comment]
I've tried to reproduce the issue but it seems to report correctly the encryption type of the disks. I'm currently running the `master` branch, and it correctly reported `EncryptionAtRestWithPlatformKey`, `EncryptionAtRestWithCustomerKey` and `EncryptionAtRestWithPlatformAndCustomerKeys`.

The code for [getting the encryption type](https://github.com/nccgroup/ScoutSuite/blob/89e74256fb9d784b6f5dc3ebc2555232fc836624/ScoutSuite/providers/azure/resources/virtualmachines/disks.py#L41) is correct and [the finding condition](https://github.com/nccgroup/ScoutSuite/blob/89e74256fb9d784b6f5dc3ebc2555232fc836624/ScoutSuite/providers/azure/rules/findings/virtual-machines-disk-encryption.json#L38) also.

**Comment by j4v** [comment]
This is now fixed in `develop`. Make sure you update the dependencies.
