### ISSUE TITLE
ELBSecurityPolicy-FS-1-2-Res-2020-10 is not recognized

### ISSUE THREAD

**Issue by ericrichtert** [nccgroup/ScoutSuite#955]
AWS released ELBSecurityPolicy-FS-1-2-Res-2020-10 as a TLS policy. This one is a "Older SSL/TLS Policy" for ScoutSuite. That's not correct.

**Comment by j4v** [comment]
Thanks, will review/merge the PR ASAP.

**Comment by j4v** [comment]
Closing, this is fixed in `develop`.
