### ISSUE TITLE
Question: Does scout suite automatically refresh temporary credentials after 1 Hr?

### ISSUE THREAD

**Issue by dsph** [nccgroup/ScoutSuite#962]
I'm running scout-suite in an EC2 instance (with Role A), if we start a scan by assuming a role (Role B - Ec2 role has permission to assume this role) added in AWS config file. In this scenario, does scout suite automatically take care of creating new credentials once they expire after one hour? If not, is there anyway to perform a scan that might take more than 1Hr in this way? 

Please note that I can only use the credentials of EC2 role and not a user credentials. We cannot increase the session duration more than 1 Hr in the config due to the limit on role chaining.

**Comment by j4v** [comment]
It should, boto3 handles the authentication and as per their documentation (https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html#assume-role-provider):

```
Within the ~/.aws/config file, you can also configure a profile to indicate that Boto3 should assume a role. When you do this, Boto3 will automatically make the corresponding AssumeRole calls to AWS STS on your behalf. It will handle in-memory caching as well as refreshing credentials as needed.
```
