### ISSUE TITLE
ScoutSuite vs NCC Scout

### ISSUE THREAD

**Issue by ash-sidss** [nccgroup/ScoutSuite#969]
Hi 

Is there any difference in the core engine (or rulesets) between Github ScoutSuite & NSS Scout ?
https://cyberstore.nccgroup.com/our-services/service-details/16/cloud-account-monitoring 

Or does NSS Scout just provides additional management and reporting interface on top of Scoutsuite ?

Thanks
A

**Comment by thommor** [comment]
Hi @ash-sidss,

The core rule engine is the same between the two platforms. However NCC Scout uses a proprietary set of rules which is not available in ScoutSuite.
