### ISSUE TITLE
Add Support for Cloud Memorystore Instances

### ISSUE THREAD

**Issue by 4ndygu** [nccgroup/ScoutSuite#977]
**Is your feature request related to a problem? Please describe.**

I would like to expand coverage within ScoutSuite by adding rules to cover Cloud Memorystore Instances.

**Describe the solution you'd like**

This would be an extension to existing resources that extend coverage from Cloud SQL to Cloud Memorystore.

**Describe alternatives you've considered**

Currently, the only alternatives are to write other scanners or manual inspection..

**Additional context**

**Comment by j4v** [comment]
> I would like to expand coverage within ScoutSuite by adding rules to cover Cloud Memorystore Instances.

Great, feel free to submit a PR with this enhancement.

**Comment by 4ndygu** [comment]
@j4v Thanks! Pushed the PR here: https://github.com/nccgroup/ScoutSuite/pull/978. Will wait and see test results.

**Comment by j4v** [comment]
> I'm facing a small rendering issue

You'll want to add the resources to https://github.com/nccgroup/ScoutSuite/blob/master/ScoutSuite/providers/gcp/metadata.json for them to render in the report.

**Comment by 4ndygu** [comment]
Thanks! Working on that now :)

**Comment by 4ndygu** [comment]
Rendering should now work. Thank you for the help! I wonder if it would make sense to add the metadata comments into the Wiki.

**Comment by j4v** [comment]
> it would make sense to add the metadata comments into the Wiki

Added (https://github.com/nccgroup/ScoutSuite/wiki/HowTo:-Create-a-custom-partial-for-new-resources#introduction)!
