### ISSUE TITLE
[Section 3] Implement CISv1.2.0 Storage Accounts on Azure

### ISSUE THREAD

**Issue by xnkevinnguyen** [nccgroup/ScoutSuite#986]
- [ ] 3.1 Ensure that 'Secure transfer required' is set to 'Enabled' (Automated)
- [ ] 3.2 Ensure that storage account access keys are periodically regenerated (Manual)
- [ ] 3.3 Ensure Storage logging is enabled for Queue service for read, write, and delete requests (Manual)
- [ ] 3.4 Ensure that shared access signature tokens expire within an hour (Manual)
- [ ] 3.5 Ensure that 'Public access level' is set to Private for blob containers (Automated)
- [ ] 3.6 Ensure default network access rule for Storage Accounts is set to deny (Automated)
- [ ] 3.7 Ensure 'Trusted Microsoft Services' is enabled for Storage Account access (Manual)
- [ ] 3.8 Ensure soft delete is enabled for Azure Storage (Automated)
- [ ] 3.9 Ensure storage for critical data are encrypted with Customer Managed Key (Automated)
- [ ] 3.10 Ensure Storage logging is enabled for Blob service for read, write, and delete requests (Manual)
- [ ] 3.11 Ensure Storage logging is enabled for Table service for read, write, and delete requests (Manual)

**Comment by j4v** [comment]
The following should already be implemented:
- 3.1
- 3.2
- 3.5
- 3.7
