### ISSUE TITLE
Cannot run Scout --  google.resumable_media.requests subpackage missing

### ISSUE THREAD

**Issue by bhargav-nunna** [nccgroup/ScoutSuite#99]
ImportError: ``requests >= 2.18.0`` is required by the ``google.resumable_media.requests`` subpackage.
It can be installed via
    pip install google-resumable-media[requests].

But When I try to install it : 

❯❯❯ pip install google-resumable-media[requests].                                                                               ✘ 1
zsh: no matches found: google-resumable-media[requests].

**Comment by j4v** [comment]
This seems to be a local issue unrelated to Scout. It is recommended to use a virtualenv to minimize dependency errors.
